### ISSUE TITLE
Custom checkbox styling issue

### ISSUE THREAD

**Issue by JeroenAdam** [elastic/search-ui#1005]
Hi, I'm using search UI and Elasticsearch, great experience so far.

I'm trying to get the checkboxes replaced with custom styled checkboxes. Normally that's done by hiding the checkbox and replacing with empty boxes and checkmarks through CSS. But my issue is that the checked/unchecked state is not shown. The clicks do their work as it should. 

![image](https://github.com/elastic/search-ui/assets/16437621/b00ad6e8-c1a3-4e17-97e6-3ad42e4dbfe7)

If I bring back the default checkboxes:
![image](https://github.com/elastic/search-ui/assets/16437621/c8121956-e728-4bd3-af95-f43abb20c1b0)

I found an example of this: https://demo.broadleafcommerce.org/hot-sauces?mfg=Blair%27s

**Comment by joemcelroy** [comment]
I suggest looking into overriding the view component of the Facet. See docs for more information https://docs.elastic.co/search-ui/guides/customizing-styles-and-html#customizing-html
