### ISSUE TITLE
support for additional non search ui query pramerters and/or hash url with TrackUrlState

### ISSUE THREAD

**Issue by dankoz51** [elastic/search-ui#1006]
Using TrackUrlState does not allow for existing url parameters or the url has to persist. It completely replaces them.

It would be nice if additional URL parameters were written back the URL so that we can use them for additional program logic. Additionally the hash part should persist as well for the same reason.

Saving additional urls to local data works but does not allow the url to have this info.  Other than that we would have to hack into the library.

![image](https://github.com/elastic/search-ui/assets/2367731/7f3e9597-b2d9-494f-9938-c32b9c784bec)

**Comment by joemcelroy** [comment]
Sorry for delay in replying. Have you seen the `RoutingOptions` configuration? Here you will be able to override the default serialise / parsing of the url. This will allow you to preserve some params which you manage outside of Search UI.  https://docs.elastic.co/search-ui/api/core/configuration#routing-options
