### ISSUE TITLE
live demo is broken and local run also has issues

### ISSUE THREAD

**Issue by swimhiking** [elastic/search-ui#1008]
Live demo TypeScript error:
  TypeError
  (0 , $csb__ic_apm_rum_core.observeUserInteractions) is not a function

Local run error:
  path C:\temp\practice\search-ui\packages\react-search-ui
  npm ERR! command failed
  npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build
  npm ERR! > @elastic/react-search-ui@1.20.2 build
  npm ERR! > npm run clean && npm run build-js
  npm ERR!
  npm ERR!
  npm ERR! > @elastic/react-search-ui@1.20.2 clean
  npm ERR! > rimraf lib

**Comment by sammy-b-123** [comment]
I'm also experiencing the same issues. Did you work out a way around it?

**Comment by ColeDCrawford** [comment]
Same - both the demos at https://docs.elastic.co/search-ui/guides/using-with-vue-js and https://docs.elastic.co/search-ui/overview seem to be broken.

**Comment by TattdCodeMonkey** [comment]
#1010 Should resolve the react issue with the live demo.

The vue issue seems to be different and I will try to look into it separately as well as the typescript issue.

**Comment by joemcelroy** [comment]
Now merged and working. Thanks for the spot! https://codesandbox.io/p/sandbox/github/elastic/search-ui/tree/main/examples/sandbox?file=%2Fsrc%2Fpages%2Felasticsearch%2Findex.js

**Comment by ColeDCrawford** [comment]
Thanks @joemcelroy - is there a separate issue for the problem with the Vue demo?
