### ISSUE TITLE
Code Sandbox "out of credits" error for nextjs integration  documentation 

### ISSUE THREAD

**Issue by jackfrosty908** [elastic/search-ui#1014]
**Describe the bug**
When you visit the next integration guide [here](https://docs.elastic.co/search-ui/guides/nextjs-integration), the code sandbox example is showing an out of credits error 

**To Reproduce**

Go to https://docs.elastic.co/search-ui/guides/nextjs-integration
Scroll to bottom of page

**Expected behavior**
Code sandbox example should be working

**Screenshots**
![image](https://github.com/elastic/search-ui/assets/58316526/709e0dca-9fc8-4b4b-9c5c-6e320258e31f)

**Comment by JasonStoltz** [comment]
I'm guessing this is related to Codesandbox's recent pricing changes: https://www.codesandbox.community/c/api-billing-updates/upcoming-pricing-billing-changes.

Interestingly, I don't see the same error message.
