### ISSUE TITLE
Upgrade peer-dependencies in react-search-ui to React & React-DOM version 18.2.0

### ISSUE THREAD

**Issue by ThunbergOlle** [elastic/search-ui#1027]
Hello! 👋  I'm migrating a project to react version 18.2 and saw that we receive peer-dependency warnings when installing about elastic/search-ui only supporting up to react version 18.0.0. Reading the changelogs for version [18.1](https://github.com/facebook/react/blob/main/CHANGELOG.md#1810-april-26-2022) and [18.2](https://github.com/facebook/react/blob/main/CHANGELOG.md#1820-june-14-2022) there does not seem to be any newly introduced changes affecting this repository. 

Is it possible for to update the [peer-dependencies to version 18.2](https://github.com/yakhinvadim/search-ui/blob/3533b13d44e00767fed2717a833998c2afd05313/packages/react-search-ui/package.json#L38-L41)? 😄

**Comment by joemcelroy** [comment]
Yes thanks for letting us know!

**Comment by joemcelroy** [comment]
released in 1.21.1
