### ISSUE TITLE
CodeSandbox demo examples have error

### ISSUE THREAD

**Issue by Nikki-Jones** [elastic/search-ui#1030]
**Describe the bug**
There is an error on all of the demo examples for search-ui https://github.com/elastic/search-ui?tab=readme-ov-file#examples

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://codesandbox.io/p/sandbox/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=%2Fsearch-as-you-type&file=%2Fsrc%2Fpages%2Fsearch-as-you-type%2Findex.js
2. View error: "Error Missing one or more of required options: endpoint, collectionName, apiKey" on load

**Expected behavior**
Error is resolved.

**Screenshots**
<img width="1538" alt="Screenshot 2024-03-21 at 3 03 26 PM" src="https://github.com/elastic/search-ui/assets/20132633/238e716a-d127-4a6f-bff6-316c65bc6592">

**Comment by yansavitski** [comment]
Hey
Thank you for your bug report. That issue has been fixed
[Link To Sandbox](https://codesandbox.io/p/sandbox/github/elastic/search-ui/tree/main/examples/sandbox?from-embed=&initialpath=%2Fsearch-as-you-type&file=%2Fsrc%2Fpages%2Fsearch-as-you-type%2Findex.js)
