### ISSUE TITLE
Pagination styling changed after upgrade

### ISSUE THREAD

**Issue by jennifer122105** [elastic/search-ui#1032]
**Describe the bug**
After upgrading to v1.21 from v1.20, we noticed a perhaps unintended change in pagination styling. See images below. 

**To Reproduce**

Pagination styling is different w/ upgrade (e.g. hovering over jump button to next 5 pages or borders around previous and next page buttons). 

**Expected behavior**
Similar look and feel to prior version.

**Screenshots**
Pre-upgrade:
![image](https://github.com/elastic/search-ui/assets/3492315/680d07e1-3611-4b64-af30-47f07bd6e13c)

After upgrade:
![image](https://github.com/elastic/search-ui/assets/3492315/265b4a30-d930-4c23-a8c4-b8fcc248f9a5)

**Which backends and packages are you using:**
Backend: Elasticsearch 
Packages: react-search-ui, react-search-ui-views, search-ui-elasticsearch-connector

**Comment by miguelgrinberg** [comment]
I can reproduce this problem and will investigate.

**Comment by jennifer122105** [comment]
Wondering if this fix still in progress or if we should expect it to be patched soon?

**Comment by joemcelroy** [comment]
thanks for highlighting this. Will pick it up this week.

**Comment by joemcelroy** [comment]
opened a new PR for this work https://github.com/elastic/search-ui/pull/1041

**Comment by joemcelroy** [comment]
released under 1.21.2.
