### ISSUE TITLE
Unclear and verbose typing for HoC functions

### ISSUE THREAD

**Issue by cpebble** [elastic/search-ui#1035]
**Describe the bug**
When using Search UI and following [Creating Components](https://docs.elastic.co/search-ui/guides/creating-your-own-components) by default Typescript will complain about the function implicitly using "Any" type.

I couldn't find info on type annotations in documentation or in the examples, however the only way i found to annotate the `withSearch` function was as follows:
```typescript
import { SearchDriverActions } from "@elastic/search-ui"
type ESSearchBarProps = {searchTerm: string, setSearchTerm: SearchDriverActions["setSearchTerm"]};
function _ESSearchBar({searchTerm, setSearchTerm}: ESSearchBarProps) {
```
Using the `SearchDriverActions["setSearchTerm"]` instead of just being able to import `SetSearchTermOptions` from "lib/esm/actions/setSearchTerm.d.ts" seems opaque to me, however this might fall back to my inexperience.
In any case it would be nice with documentation on how to properly annotate these types in the guide. 

I can update the documentation if you don't feel like prioritizing the work, however then i would like confirmation that this is how to properly annotate

**Which backends and packages are you using:**
Packages: [react-search-ui, search-ui]

**Comment by Samiul-TheSoccerFan** [comment]
@cpebble : We are looking into the issue and will get back to you soon.

**Comment by Samiul-TheSoccerFan** [comment]
@cpebble : The props could be states or actions for `core, react, and application` (same as actions) and that is why we expect developers to define their own types (if they want). Thats why we do not have any plan to make any changes in the documentation. However, we will gladly review any PRs that comes with a suggestion/fix.

This might be a better approach:
```
type ESSearchBarProps = Pick<SearchContextState, 'searchTerm' | 'setSearchTerm'>
```
