### ISSUE TITLE
Nextjs Integration guide is not working with Nextjs App Router

### ISSUE THREAD

**Issue by fireswork** [elastic/search-ui#1037]
I can't use next/router with Nextjs's app router, but if i use next/navigation, it will have many different behaviors
![image](https://github.com/elastic/search-ui/assets/14501987/7d943168-d77d-4eae-a389-f58189ea5470)

**Comment by fireswork** [comment]
Is it possible to rewrite nextjs integration guide with next/navigation or add a app router's case? 🙏

**Comment by saarikabhasi** [comment]
Thank you for reporting the issue. We will look into it.
