### ISSUE TITLE
Styles not exported

### ISSUE THREAD

**Issue by joemewes** [elastic/search-ui#1044]
**Describe the bug**
An error occurs when following the docs to import styles for @elastic/react-search-ui-views.

`Package path ./lib/styles/styles.css is not exported from package...see exports field in ... /node_modules/@elastic/react-search-ui-views/package.json)`

Is it related to this commit/update https://github.com/elastic/search-ui/pull/1043/commits/1b5dfd285fbd56d86a642278720128e500113cc8?

```
import "@elastic/react-search-ui-views/lib/styles/styles.css";
```

**To Reproduce**

1. Install and follow implementation guide from the docs.

**Expected behavior**
React UI components will render as styled.

**Which backends and packages are you using:**
Packages: [@elastic/react-search-ui-views]

**Comment by joemewes** [comment]
I think adding the following resolves the issue:
```
"./lib/styles/styles.css": {
    "import": "./lib/styles/styles.css",
    "require": "./lib/styles/styles.css"
  }
```

**Comment by miguelgrinberg** [comment]
@joemewes Thanks, and sorry. I missed the styles which also need to be exported. Fix coming soon.
