### ISSUE TITLE
[elasticsearch-connector] base filters are incorrectly applied twice

### ISSUE THREAD

**Issue by applicity** [elastic/search-ui#1062]
**Describe the bug**
When defining base filters as part of the search configuration they are applied twice into the query.  If the base filter is a "none" query the second time it is applied then it will be applied as a "must" and therefore you get zero results.

**To Reproduce**

Define a search query with a filter like this: 

```
...
filters: [{ field: 'uri', values: ['one'], type: 'none' }]
```

The elastic search query is built as:

```
{
  "bool": {
    "filter": [
      {
        "bool": {
          "must_not": [
            {
              "term": {
                "subject_uri": "one"
              }
            }
          ]
        }
      },
      {
        "bool": {
          "filter": [
            {
              "term": {
                "subject_uri": "one"
              }
            }
          ]
        }
      }
    ],
    "must": []
  }
}

``` 

**Expected behavior**

I would expect the query only to have the filter added once, and in the case of the "none" version that this be the must_not version.

**Which backends and packages are you using:**
Backend: [Elasticsearch]
Packages: [react-search-elasticsearch-connector]

**Comment by Samiul-TheSoccerFan** [comment]
@applicity : Can a live code example be shared to reproduce this issue? It might help us to understand the problem better.
