### ISSUE TITLE
Cookie don't send using ElasticsearchAPIConnector

### ISSUE THREAD

**Issue by T-iny** [elastic/search-ui#1064]
**Describe the bug**
The cookie in the network request is missing.
The host is a REST API wrapper.
**To Reproduce**

1. Setup
 - Connector: const connector = new ElasticsearchAPIConnector(
    {
      host: process.env.NEXT_PUBLIC_ELASTIC_CONNECTOR_HOST,
      index,
      connectionOptions: {
        headers: {
          Authorization: `Bearer ${authState?.accessToken?.accessToken}`,
        },
      },
    },
    }
  );

- Config: const [config] = useState<SearchDriverOptions>({
    alwaysSearchOnInitialLoad: true,
    apiConnector: connector,
    searchQuery: {}...

- Driver: const driver = new SearchDriver(config);

SearchProvider: - <SearchProvider
      config={{
        ...config,
        apiConnector: new ElasticsearchAPIConnector({
          host: process.env.NEXT_PUBLIC_ELASTIC_CONNECTOR_HOST,
          index,
        }),
      }}
      driver={driver}
    >

**Expected behavior**
The cookie send with request.
**Screenshots**

**Which backends and packages are you using:**
Backend: [custom]
Packages: [ElasticsearchAPIConnector]

Please review. Thanks!

**Comment by saarikabhasi** [comment]
Hi, The `ElasticsearchAPIConnector` use constructs elasticsearch query and the requests do not use cookies. If you would like to use cookies, it should be handled in your application.

**Comment by T-iny** [comment]
Thanks for your answer @saarikabhasi .  The connector manage the request itself. I have set a Bearer Token in the header in the ElasticsearchAPIConnector. But I can not catch the 401 error, Is there any way to catch the 401 error and refresh token? Or is there any way to get the http response?
The code I used is like this.
 <SearchProvider key={userInfo} config={config} driver={driver}>
        <WithSearch
          mapContextToProps={({ ...props }) => ({ ...props })}
          key={userInfo}
        >
          {(searchContextState: SearchContextState) => {
            const results = removeRaw(searchContextState.results);
            const {
              searchTerm,
              current,
              resultsPerPage,
              removeFilter,
              filters,
              setSearchTerm,
              clearFilters,
              isLoading,
              totalResults,
            } = searchContextState;

**Comment by saarikabhasi** [comment]
You could try catching errors in your server side code. We currently have example in our doc on [how to integrate with node.js](https://www.elastic.co/docs/current/search-ui/api/connectors/elasticsearch#nodejs-integration).
