### ISSUE TITLE
Cannot convert undefined or null to object error when using multiple indices

### ISSUE THREAD

**Issue by swimhiking** [elastic/search-ui#1065]
**Describe the bug**
When query with multiple indices, I also need to sort the final results with different attributes for each index; when the searched attribute not exist on the "Cannot convert undefined or null to object " error

**To Reproduce**
create an ES config with multiple indices
add sort attribute only exist for this index
launch search ui component, error will display on the web

**Comment by saarikabhasi** [comment]
Hey, Thank you raising the ticket. To investigate further,  could you please share which [search ui connector](https://www.elastic.co/docs/current/search-ui/api/connectors/app-search) are you using ?

**Comment by swimhiking** [comment]
Hey , I using ElasticSearchAPIConnector from '@elastic/search-ui-elasticsearch-connector';

**Comment by saarikabhasi** [comment]
Thank you. Could you please share the error response from the `_search` query ? 
 
I tried setting up `ElasticSearchAPIConnector` with the multiple indices and added sort on a field that exists in only one index and I was able to sort the documents.
```
const connector = new ElasticsearchAPIConnector({
  cloud: {
    id: "<elastic-cloud-id>" // cloud id found under your cloud deployment overview page
  },
  index: "index_name1,index_name2", // added my index
  connectionOptions: {
   headers: {
   Authorization: `Bearer ${key}`,
    },
   }
});

// sorting component
<Sorting
  sortOptions={[
    {
      name: "Relevance",
      value: "",
      direction: ""
    },
{
    name: "testField",  // this field only exist in index_name2
    value: [
      {
        field: "testField",
        direction: "asc"
      }
    ]
  },
  ]}
/>
```

**Comment by swimhiking** [comment]
above code  wont get any errors, but will return incomplete data, in following case it will miss all index_name3 data; In order to simulate errors;  we can put this:

const connector = new ElasticsearchAPIConnector({
  cloud: {
    id: "<elastic-cloud-id>" // cloud id found under your cloud deployment overview page
  },
  index: "index_name1,index_name2", // added my index
  connectionOptions: {
   headers: {
   Authorization: `Bearer ${key}`,
    },
   }
});

// sorting component
<Sorting
  sortOptions={[
    {
      name: "Relevance",
      value: "",
      direction: ""
    },
{
    name: "testField",  // this field only exist in **index_name2**
    value: [
      {
        field: "testField",
        direction: "asc"
      }
    ]
  },
{
    name: "testField3",  // this field only exist in **index_name3**
    value: [
      {
        field: "testField3",
        direction: "asc"
      }
    ]
  },
  ]}
/>

Then the errors will be:
web page console error:
  cannot find testField3 from index_name2
  cannot find testField from index_name3

**Comment by saarikabhasi** [comment]
Can you try setting all the index names including `index_name3`  in `index` param of `ElasticsearchAPIConnector`? 

For example: 
 ElasticsearchAPIConnector({
  cloud: {id: "<elastic-cloud-id>"},
  **index: "index_name1,index_name2,index_name3", // added my index**
  connectionOptions: {
   headers: {
   Authorization: `Bearer ${key}`,
    },
   }
});

The `ElasticSearchAPIConnector` constructs Elasticsearch query based on the constructor value. In this case when searching multiple indices, it creates Elasticsearch query to [search with multiple indices ](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multiple-indices.html).

**Comment by swimhiking** [comment]
Yes, of course; I didn’t describe all good things that set properly and correctly, only mentioning how to simulate the errors; right now we have to set/add one common attribute cross all 7-8 indices to avoid this problem.

**Comment by saarikabhasi** [comment]
Hey, are you getting the error in the result component? 
Is the result component relying on a field that doesn't exist all the indices ?
