### ISSUE TITLE
trackurlState 设置了false之后，url 还是有参数

### ISSUE THREAD

**Issue by zbsguilai** [elastic/search-ui#1067]
Why is there still a parameter for filtering conditions on the page after setting trackurlState to false?
After setting false, won't the URL save the parameters

**Comment by Samiul-TheSoccerFan** [comment]
Hi @zbsguilai ,

I updated the `config` defined [here](https://codesandbox.io/p/sandbox/github/elastic/search-ui/tree/main/examples/sandbox?file=%2Fsrc%2Fpages%2Fsearch-as-you-type%2Findex.js&from-embed=&initialpath=%2Fsearch-as-you-type) and was able to hide the URL parameters.

```
const config = {
  debug: true,
  alwaysSearchOnInitialLoad: true,
  apiConnector: connector,
  hasA11yNotifications: true,
  trackUrlState: false,
 }
 
 <SearchProvider config={config}>
 .....
 </SearchProvider>
  ```

If you are already setting the value and passing it in `SearchProvider`, please send us a code example (preferably in CodeSandBox) so we can do a deeper investigation.
