### ISSUE TITLE
Just wondering when ElasticSearch UI library will upgrade to React version 18

### ISSUE THREAD

**Issue by swimhiking** [elastic/search-ui#1068]
We using Elasticsearch ui library for our search results display, and recently  we upgrade our React version to 18 and found some warning messages mentioned deprecated API from search components; so wondering any plan to upgrade Elasticsearch ui library to using  React18? thank you very much!

**Comment by Samiul-TheSoccerFan** [comment]
Hi @swimhiking , We do not have any immediate plan to upgrade to React 18. Just to clarify, you have started to see these warning messages when you bump your own `search-ui` project to React 18? Is there a way to look at the code or do you have any example available?

**Comment by swimhiking** [comment]
Thanks Samiul, 

we using micro-services , about 10 UI services with the global search component using Elasticsearch UI; the code almost we copy from sample , we use ElasticSearchAPIConnector; and we got some warning after upgrade to React 18 , warning message sample see attached image; thanks
![ES-UI-WarningMsg1](https://github.com/user-attachments/assets/a7b37c5a-7447-4896-be5e-099a1c6fcd9a)
