### ISSUE TITLE
BooleanFacet component

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#108]
The following gist contains a simple example of a boolean facet filter component, as well as a gif demonstrating the behavior.

https://gist.github.com/JasonStoltz/4d26d41cfa354fdbf7b6bcd2978516f5

I would like to turn this into an available option for Facet filters. This would be another "view" available for the "Facet" component, similar to "SingleLinksFacet", "SingleSelectFacet", and "MultiCheckboxFacet".

A BooleanFacet component would assume that the value being filtered on is either a field with "true" / "false" string values, or literal `true` / `false` boolean values.

A BooleanFacet field would not list the values as facets, they would have a single link or check box to apply the "true" value.

The implementor of this PR does not need to worry about apply exact CSS styles. We can provide styles after the PR is merged.

**Comment by Kacppian** [comment]
Hey Jason, would this be a good issue to look at?

**Comment by JasonStoltz** [comment]
@Kacppian I think this one is a good first issue, but I think this one might be better: https://github.com/elastic/search-ui/issues/337

**Comment by Jfelix61** [comment]
Hey Jason, will be trying this!

**Comment by JasonStoltz** [comment]
@Jfelix61 Great!

**Comment by yakhinvadim** [comment]
Closed in https://github.com/elastic/search-ui/pull/383
