### ISSUE TITLE
Integration between search-ui and elastic-charts?

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/search-ui#111]
Seems that there is some demand to expose Kibana-style visualizations to the public internet, bypassing authentication.  We currently have some iframe/proxy techniques to make that happen, but no OOTB support.  Wondering if AppSearch would be appropriate for such a use-case by exposing [Elastic Charts](https://github.com/elastic/elastic-charts#readme) in the same way search-ui exposes the search API.

**Comment by JasonStoltz** [comment]
Love the idea @PhaedrusTheGreek. Placed it in our backlog, will plan to do some sort of spike on this in the near future.

**Comment by JasonStoltz** [comment]
Closing, this issue is stale.
