### ISSUE TITLE
Proposal for Web Based version of Search UI

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#117]
The React version of Search UI requires the following:

1. You need be using React in your project.
2. You need all of the tooling to build a react project, which can be quite hefty.

A Web Based version of Search UI would effectively be a wrapper around the React version, that you could include directly via a script tag.

1. You could use this in any project. React dependency would be bundled into `search-ui.js` bundle.
2. No extra tooling required.

So for example, on a web page, if you simply wanted to use a search-ui autocomplete search box, you could do so easily, with minimal configuration:

```
<script src="http://path/to/search-ui.js" />
<script src="http://path/to/search-ui.css" />

<script>
SearchUI.config({
  // some config here
});

SearchUI.searchBox('#search-box', {
  autocompleteResults: true
});
</script>

<body>
  <input type="text" id="search-box"/>
</body>
```

From an implementation standpoint, I believe we'd be wrapping our components somewhat like this:

```
// Assume a single driver was created when we initialized Search UI

// Grab relevant data and actions from the driver state and render the component
const searchTerm = driver.state.searchTerm;
const setSearchTerm = driver.actions.setSearchTerm;
const element = document.getElementById("#search-box"));
ReactDOM.render(<SearchBox searchTerm={searchTerm} setSearchTerm={setSearchTerm} />, element);

// Any time a user interacts with a component it will trigger an action, which triggers a state update in the driver, which we'll handle by re-rendering with the updated state.
driver.subscribeToStateChanges(state => {
  ReactDOM.render(<SearchBox searchTerm={state.searchTerm} setSearchTerm={setSearchTerm} />, element);
})
```

**Comment by byronhulcher** [comment]
I have no idea of the viability of this, but it could be worthwhile looking into https://preactjs.com/, which has a smaller size than React, for bundling w/ search-ui.  Upside could be some KB saved, downside could be preact-specific bugs that would surface in this bundled version.  Their goal is 1:1 parity with React using he same API (they just added hooks! https://github.com/developit/preact/issues/1247#issuecomment-469339665)
