### ISSUE TITLE
Filterable Facet Lists

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#131]
Have `Facet` component that has a text box at the top which lets you live filter facet filter options. This filtering would all be done client side. This would help finding facet values to apply when the list of facet options are very long.

This would be another "view" available for the "Facet" component, similar to "SingleLinksFacet", "SingleSelectFacet", and "MultiCheckboxFacet".

Something to consider for an i18n perspective, is that when searching for "e", "e" should match "e" or "é".

Example: https://www.hendel.com/tecnologia/televisores.html

![latest](https://user-images.githubusercontent.com/1427475/56578372-89ef2c00-659b-11e9-8787-b3e9d96d0230.gif)

**Comment by m-sureshraj** [comment]
@JasonStoltz I can implement this feature. 👍

**Comment by JasonStoltz** [comment]
Thank you @m-sureshraj, I'm excited to hear that. We have a Gitter set up for this projects, feel free to ask any questions there and we will be quick to respond: https://gitter.im/elastic-search-ui/community.

**Comment by m-sureshraj** [comment]
Hi, I have already joined the Gitter group. 🙂 Thanks @JasonStoltz

**Comment by m-sureshraj** [comment]
@JasonStoltz https://github.com/elastic/search-ui/pull/248
