### ISSUE TITLE
Integration instructions for integrating with Redux and React Router

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#14]
This will likely be tied closely to Managed Mode

**Comment by scheiblr** [comment]
This would be very interesting, as we currently have the issue, that the search overwrites the react router path, e.g. when I click on a facet option. Is there a way to solve this, so that the GET variables get appended to the current URL and do not replace the entire path?

**Comment by JasonStoltz** [comment]
@scheiblr Could you open up a separate issue with some more detail?

**Comment by scheiblr** [comment]
sure, done: https://github.com/elastic/search-ui/issues/461
