### ISSUE TITLE
Allow a user to hide the button on SearchBox

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#163]
```jsx
<SearchBox inputView={ ( { getTextInputProps, getSubmitButtonProps } ) => (
    <input {...getTextInputProps({
       placeholder: "Search your documents",
       // You can inject or override whatever attributes you want here
     })} />
    <input {...getSubmitButtonProps({
       className: "some custom class"
       // You can inject or override whatever attributes you want here
     })} />
) } />
```

So I would replace the `inputProps` with an `inputView` function. You could then arrange the text input and submit button however you'd like. You could choose to omit the button completely in this case. Or, you could choose to apply a class, or whatever you'd like. You could inject an icon if you needed to do that... this would give you the maximum amount of flexibility I believe.

The only thing you would need to do is make sure when you are applying attributes to either element, that you are applying them through `getTextInputProps ` or `getSubmitButtonProps`. Those functions will make sure any props are applied that MUST be applied for them to work correctly, but also give you the opportunity to mix in your own.

**Comment by katydecorah** [comment]
I was thinking that this could be implement as an object, `buttonProps`, that gets passed to the button much like `inputProps`. This way the button can be customize with class names. In my use case, I would hide the button, but passing props would make the component highly customizable.

**Comment by JasonStoltz** [comment]
@katydecorah The approach I had in mind looks something like this:

```jsx
<SearchBox inputView={ ( { getTextInputProps, getSubmitButtonProps } ) => (
    <input {...getTextInputProps({
       placeholder: "Search your documents",
       // You can inject or override whatever attributes you want here
     })} />
    <input {...getSubmitButtonProps({
       className: "some custom class"
       // You can inject or override whatever attributes you want here
     })} />
) } />
```

So I would replace the `inputProps` with an `inputView` function. You could then arrange the text input and submit button however you'd like. You could choose to omit the button completely in this case. Or, you could choose to apply a class, or whatever you'd like. You could inject an icon if you needed to do that... this would give you the maximum amount of flexibility I believe.

The only thing you would need to do is make sure when you are apply attributes to either element, that you are applying them through `getInputProps` or `getSubmitButtonProps`. Those functions will make sure any props are applied that MUST be applied for them to work correctly, but also give you the opportunity to mix in your own.

Does that makes sense?

@scottybollinger and @zumwalt I think this would solve a lot of your issues with this component as well.

**Comment by katydecorah** [comment]
> Does that makes sense?

@JasonStoltz yes, that implementation ticks all my boxes and makes the component even more customizable 💯
