### ISSUE TITLE
Consider renaming options for `SortOption` 

### ISSUE THREAD

**Issue by byronhulcher** [elastic/search-ui#189]
from https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/src/types/SortOption.js: 
```
const SortOption = PropTypes.shape({
  // A display name, like "Name"
  name: PropTypes.string,
  // A field name, like "name".
  value: PropTypes.string,
  // asc or desc
  direction: PropTypes.oneOf(["asc", "desc", ""])
});
```

I think I think the use of `name` and `value` is confusing.  Perhaps `title` and `field`? I want to make sure we're consistent though, so if this is a pattern we use elsewhere I want to make sure we're considering all its implementations.

**Comment by JasonStoltz** [comment]
Hey @byronhulcher. I chose "name" and "value" because it matches the terms most often used for dropdown options. However, "field" does seem more appropriate than "value", and "title" seem better than name. I like this proposal.

**Comment by byronhulcher** [comment]
Ahhh the form thing makes sense.  I think it makes sense to keep it in that case.
