### ISSUE TITLE
Ability to tab through results in autocomplete

### ISSUE THREAD

**Issue by katydecorah** [elastic/search-ui#190]
When I try to tab or arrow down during autocomplete the list disappears. I think it would be helpful for keyboard-only users to have the ability to tab through these results.

**Comment by JasonStoltz** [comment]
Hi @katydecorah.

What version of this library are you using, and would you be able to post a code snippet?

The `SearchBox` component with `autocompleteResults` enabled uses https://github.com/downshift-js/downshift out of the box, which is WAI-ARIA compliant and supports keyboard navigation, so it *should* be working for you.

**Comment by katydecorah** [comment]
@JasonStoltz my mistake, looks like arrow down is working as expected 🙇‍♀️
