### ISSUE TITLE
Ability to opt-out of certain parameters tracked in URL state

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#199]
The use case is something like this:

As a developer, I want to hardcode certain parameters and thus would not like them to be exposed in the URL.

From an implementation perspective, it IS possible to hardcode parameters by configuring them in the `searchQuery` option.

Example:
```
    <SearchProvider
      config={{
        apiConnector: connector,
        searchQuery: {
          resultsPerPage: 6
        },
      }}
    >
```

This hardcodes the value to 6, so it is always sent as 6 on API requests.

However, "size" (the corresponding URL parameter) is still exposed in the query string, though it is no longer functional.

**Comment by m-sureshraj** [comment]
Hi @JasonStoltz 

I would like to contribute to the Search-UI, but I haven't worked with the Search-UI components before & not much familiar with repo codebase yet (I'm working on it). I guess I can start with a small task.

Thanks.

**Comment by JasonStoltz** [comment]
@m-sureshraj This issue might actually be a little tricky. I'm unsure of exactly how this should work at this point, so it will require a bit of thought. You're welcome to play around with it and submit a PR as a proposal.

However, I also marked some other issues with the "Good first issue" tag. These are issues isolated to specific components, which I think is a good place to start with Search UI. https://github.com/elastic/search-ui/labels/good%20first%20issue

This one, in particular I think would be a great first issue: https://github.com/elastic/search-ui/issues/60.

There is a contributor guide here to help get you set up and started: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#search-ui-contributors-guide.

There is a gitter set up for chat about the project: https://gitter.im/elastic-search-ui/community. Feel free to post there if you need help.

**Comment by m-sureshraj** [comment]
Thanks for the detailed response @JasonStoltz. I can pick up the #60

**Comment by JasonStoltz** [comment]
https://github.com/elastic/search-ui/issues/790
