### ISSUE TITLE
Significant performance issues

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#223]
There are significant performance issues in a demo use case internally at Elastic.

The setup is Gatsby + Styled components. The render time for `Facet` components on the page seem to be very computationally expensive.

With autocomplete enabled, each facet is rendering twice, for each state update associated with an autocomplete query.

There are few possible things that could being going on here:

1. Facet should be memoizing some sort of computation that it performs.
2. Facet is performing some logic that could be simplified.
3. Facet (and other components) should implement "componentShouldUpdate".
4. There is something inefficient about the interaction between styled components and this library.

**Comment by JasonStoltz** [comment]
https://www.codebeast.dev/usestate-vs-useref-re-render-or-not/

**Comment by JasonStoltz** [comment]
branch: `performance-spike`

**Comment by m-sureshraj** [comment]
@JasonStoltz 

> The setup is Gatsby + Styled components. The render time for Facet components on the page seems to be very computationally expensive.

A demo repo would be very helpful.

**Comment by JasonStoltz** [comment]
@m-sureshraj For sure. I'm working on a PR for this now, I'll illustrate the issues in more depth there!

**Comment by JasonStoltz** [comment]
@m-sureshraj https://github.com/elastic/search-ui/pull/249
