### ISSUE TITLE
Schema for `Result` objects is too strict

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#256]
Currently does not allow for nested objects.

May also not allow for other valid types, like Boolean, etc.

**Comment by conor909** [comment]
Does anyone know if this has been released?   I can't seem to use nested objects in the responses in react-search-ui

`v1.2.0`

**Comment by JasonStoltz** [comment]
@conor909 It was, can you be more specific? What are you using this with, App Search or Elasticsearch? What does the object look like.

**Comment by JasonStoltz** [comment]
And yes, this was released in 0.11

**Comment by conor909** [comment]
Im using the example project in `examples/elasticsearch` and I'm testing it with the json file in `examples/elasticsearch/data/national-es-bulk-index.json` which works great.

But if I change the structure of the JSON to have a nested object, then it breaks because it can't find the path to the `raw` property.

**Comment by JasonStoltz** [comment]
@conor909 This PR loosened the schema for the that Results type. However, the out of the box `Results` view component *does* expect the data to be formatted in a particular way. The view unfortunately does not currently communicate that properly in it's prop types: https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/src/Result.js#L102

You would need to provide a custom view for your application.

Here's a description of custom view: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#component-views-and-html.

And an example you can use for reference: https://codesandbox.io/s/video-games-tutorial-with-images-5wsqs.

**Comment by conor909** [comment]
@JasonStoltz ah I see, thanks for that clear info!
