### ISSUE TITLE
core-js error

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#262]
Error:
./node_modules/@elastic/react-search-ui-views/es/index.js
Module not found: Can't resolve 'core-js/modules/es6.array.copy-within' in '/Users/kellen/Repos/swiftype/video-game-search/node_modules/@elastic/react-search-ui-views/es'

Potential fix... remove @babel/polyfill and just use core-js directly: https://babeljs.io/docs/en/babel-polyfill

https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelpolyfill

**Comment by wizawuza** [comment]
downgrading to core-js version 2.6.5 worked for me.
