### ISSUE TITLE
When state is pushed, the UI does not seem to respond.

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#269]
https://github.com/swiftype/demo-asecom/issues/12

This, I think, could be a problem. What if a user does want to push a new state the URL with a new query string. We had this case in an ecommerce demo, where from the main search bar in the header, the autocomplete was configured to navigate to "?q={search_term}". This was using Gatsby, so that was ultimately a called to `pushState`, which we are currently explicitly filtering out.

https://github.com/elastic/search-ui/blob/0cc15c2e1e66305d2f91dc3b0918c02e85919c52/packages/search-ui/src/URLManager.js#L128-L130

I think we should instead be detecting that if the push state call is our OWN push state call, then we want to return early. This could possibly done by pushing some additional state that we could inspect.

**Comment by JasonStoltz** [comment]
This turned out not to be an issue with Search UI. It is a Router issue (gatsby, react router, etc.). They will not reload / remount a route navigation to the current route, even if the query string parameters have changed. The only work-around I could suggest for something like that is to use the query string parameter as a key on the Route to force a remount. Example here: https://codesandbox.io/s/react-router-with-search-ui-rsgxn.

**Comment by marcvangend** [comment]
I have a similar issue with Search UI and React Router - hope you can guide me in the right direction. My situation is the same in that I need a route change when I start a search, but the difference is that it is triggered by the Search UI search box instead of a link.

The project I'm working on needs a search bar in the header, on all pages. To make that work, I moved the <SearchProvider> up a level. In simplified form, the app structure is like this:
```jsx
<Router>
  <SearchProvider
    config={{...}}
  >
    <div className="page-wrapper">
      <PageHeader/>
      <Switch>
        <Route exact path="/" component={Home}/>
        <Route exact path="/about" component={About}/>
        <Route path="/search" component={Search}/>
      </Switch>
      <PageFooter/>
    </div>
  </SearchProvider>
</Router>
```
The SearchBox component is rendered inside PageHeader, while the search results are rendered in the Search component. With the debug option on, I can see that the search box correctly triggers a search request and the state is updated with results.

Now the problem is that when the search box is submitted, I need to be redirected to the /search route. I can't figure out how to make that happen. The search box only appends the query parameters to whatever the current route is. 

I tried solving this with an onSubmit handler on the SearchBox component and doing a ``history.push(`/search/?q=${term}`)`` (`history` being the object returned by React Router's [`useHistory()`](https://reacttraining.com/react-router/web/api/Hooks/usehistory)) but that didn't really work because it adds an additional entry in the browser history stack.

Please let me know if this should have been a separate issue.

**Comment by JasonStoltz** [comment]
> I tried solving this with an onSubmit handler on the SearchBox component and doing a history.push(`/search/?q=${term}`) (history being the object returned by React Router's useHistory()) but that didn't really work because it adds an additional entry in the browser history stack.

Hmmm, I don't understand what the problem is here? I would expect that to add a history item.

**Comment by marcvangend** [comment]
> Hmmm, I don't understand what the problem is here? I would expect that to add a history item.

Sorry I didn't explain clearly. Of course you would expect history.push to add a history item, but Search UI itself _also_ adds to the history. In other words, if you are on the /about page and you start a search for "foo" in the search bar, you are first redirected to /search, and then immediately to /search?q=foo&size=n_20_n. Now when you go back in history, you go back to /search, not to /about as the user would expect.

**Comment by JasonStoltz** [comment]
Ah, OK, that should have been fixed in 1.3.1: https://github.com/elastic/search-ui/releases/tag/v1.3.1

What version of Search UI are you using?

**Comment by marcvangend** [comment]
We are on version 1.3.2, with react 16.13.0 and react-router-dom 5.1.2. Development started very recently so we have very recent versions of pretty much everything. Would it help if I try to set up an example on codesandbox? (Never did that before but I guess I should be able to.)

**Comment by JasonStoltz** [comment]
That would be helpful

**Comment by marcvangend** [comment]
Thank you for looking into this. Here is a minimalist code sandbox that demonstrates the problem I'm trying solve: https://codesandbox.io/s/busy-haibt-c3vwv. As you can see, the search box triggers a search requests and alters the url, but you don't get redirected to the search page.

**Comment by llermaly** [comment]
Similar problem here. I'm trying to render a details page after clicking a result keeping the search box but when I trigger a search inside the details page attach ?q=test to /details/id/

**Comment by marcvangend** [comment]
@JasonStoltz since we now have a codesandbox and multiple users reporting the same issue, would that be reason to reopen this issue?

**Comment by JasonStoltz** [comment]
Let me dig in right now and see if I can figure out what is happening

**Comment by JasonStoltz** [comment]
@marcvangend I modified your code sandbox, check it out: https://codesandbox.io/s/modest-night-dx1gu

I think this is the way you need to handle a global search box.

1. Have a separate SearchProvider for your global search box. 
1. Implement a onSubmit on your global search box which does a history.push to /search?q=searchTerm
1 Make sure your global search box has trackUrlState turned off
1. Have a separate SearchProvider for your Search Page
1. Make sure you add a `key` to your /search route so that it is re-rendered when the search term changes

This is how we've dealt with this in the past. If this is insufficient for some reason, let me know.

**Comment by JasonStoltz** [comment]
Also, typically, even if there is a search bar in the global header, sites will often times have a separate search bar embedded within the search page. They typically two serve two separate purposes:

1. Global header search bar ... take a user from other parts of the website to the search page with a search term populated
2. embedded search bar ... a more prominent search bar that users will use for refinement, or if they navigate directly to `/search`

That's my 2 cents.

**Comment by marcvangend** [comment]
Thanks @JasonStoltz, I will definitely check out your code in more detail as soon as I have the time. At first glance, your solution looks clean and works as expected.

**Comment by jmsuhy** [comment]
FYI - if you happen to be trying to use window.searchUI in your code and you turn debug off - then window.searchUI is no longer set.  I.E.  It's just there for debugging.    I was not sure if that is what you were talking about.

Check out the SearchDriver.js file.   

if (this.debug) {
      console.warn(
        "Search UI Debugging is enabled. This should be turned off in production deployments."
      );
      window.searchUI = this;
    }
