### ISSUE TITLE
I'd like to use/display the score (`_meta.score`) in results

### ISSUE THREAD

**Issue by FokkeZB** [elastic/search-ui#274]
I'd like to use/display the result scores in the views, but `_meta` is explicitly filtered out by:

https://github.com/elastic/search-ui/blob/121616c4d6647a9f4bc059869d620c083e0b90eb/packages/search-ui-app-search-connector/src/responseAdapter.js#L57

Is there another way to get the score? Could we _not_ filter `_meta` or at least `_meta.score` out?

**Comment by JasonStoltz** [comment]
@FokkeZB I think you're right that we should not filter out `_meta`. Will be pushing a new release of this library in the next day or two, I will include this as a fix.
