### ISSUE TITLE
I'd like to tell if a result is curated/promoted

### ISSUE THREAD

**Issue by FokkeZB** [elastic/search-ui#275]
I'd like to mark results that have been curated/promoted as such, but other than `_meta.score` being `1` (which I can't use due to #274) there doesn't seem to be a way.

I realize this may be more an API than a `search-ui` related question, so feel free to forward the issue to the relevant team.

**Comment by JasonStoltz** [comment]
@FokkeZB I'm doing some investigation now.

**Comment by JasonStoltz** [comment]
Entered an issue with the core project. Will update here if I hear more.

**Comment by JasonStoltz** [comment]
Since score is now exposed in results, I believe this should be possible by looking for score == 1.

**Comment by FokkeZB** [comment]
A separate boolean prop might be more explicit, but that'd be an API change. This'll do!

**Comment by JasonStoltz** [comment]
Yes, that's true. As always, thank you for taking the time to open up this issue and give us feedback. ❤️
