### ISSUE TITLE
WithSearch under conditionally rendered components return previous instead of current state

### ISSUE THREAD

**Issue by FokkeZB** [elastic/search-ui#279]
# Steps to reproduce

Code: https://codesandbox.io/s/search-ui-national-parks-example-3qb66
Recording: https://zappy.zapier.com/F2516A6C-523A-4F14-B6CE-C94DF9A26859.mp4

1. Open https://3qb66.csb.dev/?q=Rocky&size=n_20_n
2. Notice how the conditionally rendered components do not list the results, while the unconditional one does.
3. Start changing the search term to _Mountain_
4. Notice how while you type the component both conditional components get updated to render the "old" results.
5. Hit enter to kick off the new search.
6. Notice how the unconditional and the component rendered conditionally on `wasSearch` do render the new results, but the other conditional component (which while `isLoading` doesn't render) still shows the old ones.
7. GOTO 3) 😉 

# Theory

I think this is due to how `WithSearch` used within these components/containers subscribes to changes when it gets constructed:

https://github.com/elastic/search-ui/blob/ba689c64f28ae65b84064be903367687e7547c7f/packages/react-search-ui/src/withSearch.js#L52

If the component gets constructed it somehow gets the previous instead of the current state.

**Comment by FokkeZB** [comment]
Perhaps this could be related to #269?

**Comment by JasonStoltz** [comment]
@FokkeZB The behavior we're seeing here is the same behavior I've seen in #269, so that is very possible.

**Comment by JasonStoltz** [comment]
That is definitely the case. Tracing through, it looks something like this:

For: http://localhost:3000/?q=rocky&size=n_1_n

1. SearchProvider mounts
2. SearchProvider triggers an action
   a. State is updated with initial search term, "rocky" and "results: []"
   b. Notifies subscribers (but nothing is subscribed yet)
3. `Unconditional component` mounts with current state ("rocky" and "results: []") and subscribes to changes
4. SearchProvider triggers an action
   a. State is updated with "results: [a, b, c]"
   b. State is updated with "wasSearched: true"
   c. Notifies subscribers (but only `Unconditional component` is subscribed)
5. `Conditional component` mounts. When it mounts, it initializes with what *should* be the current state. It retrieves that state from "context.driver.getState()", which was updated in "4a". Logically, it sounds correct, but for whatever reason it is returning a reference to the old state.

**Comment by JasonStoltz** [comment]
OK, I have a fix for this. I basically just need to swap these two lines:

https://github.com/elastic/search-ui/blob/ba689c64f28ae65b84064be903367687e7547c7f/packages/search-ui/src/SearchDriver.js#L275-L276

Will see if I can post an explanation of WHY that matters shortly.

**Comment by FokkeZB** [comment]
Ah, I think I see why swapping those fixes it. Currently, if informing existing subscribers causes them to render new components, those will initialize with the old state. If you swap the lines, they will initialize with the new state.

**Comment by JasonStoltz** [comment]
Yes, I think you are right.
