### ISSUE TITLE
Merge component reference and storybook

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#281]
Currently, there is a storybook just for reacth-search-ui-views. There is also a component reference in the README. These should be consolidated into a single storybook in `react-search-ui`, that can be deployed on included in the docs site.

**Comment by yakhinvadim** [comment]
We decided to not merge them. The source of truth for component API will be README and the storybook will remain just for the sake of developing new components. It will probably not be updated over time.
