### ISSUE TITLE
Add Typescript bindings

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#289]
Someone will want these, and it will also help us document our own API.

For reference: https://github.com/elastic/eui/commit/1c837b7d1e5dd1371c9e5c5a3733a437b034bd09#diff-f8ac36caa03f828bf516460a9156f08c

**Comment by harsimranb** [comment]
I am planning on using this package in a large TypeScript project, and typescript bindings will be very helpful.

**Comment by alexanderatallah** [comment]
It's been a couple months - just wanted to check if this is being worked on! It's a big part of our decision to use it. Right now, we have to type out things like "Result" manually, otherwise it's very easy to make errors (e.g. when a field is null in our elasticsearch index, or when results aren't being serialized correctly).

**Comment by JasonStoltz** [comment]
@alexanderatallah It is not being worked on currently, but I understand the need.

**Comment by alexanderatallah** [comment]
@JasonStoltz I submitted some type definitions for react-search-ui. Do these look ok? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41605

**Comment by JasonStoltz** [comment]
@alexanderatallah 

That's great! A few questions... I'm new to TypeScript.

- Did you generate these or hand code them? If generated, how did you generate them?
- I started doing some work to add these definitions directly to this project by adding a `.d.ts` file directly to the top of each package. If I do this, what happens to the types defined in the `@types`? Do they become obsolete?

**Comment by JasonStoltz** [comment]
@alexanderatallah I have a Draft PR up for what I have so far: https://github.com/elastic/search-ui/pull/458. I wonder if it would make more sense to add your changes to this?

**Comment by alexanderatallah** [comment]
@JasonStoltz I hand-coded the types. Yeah it’s a little bit better to add the definitions to the main repo, since it’s more likely that they’ll stay in sync. Not sure about this but adding a tslint command call to the tests might be able to tell when something new got exported that isn’t typed.

I’ll open a PR against yours

**Comment by JasonStoltz** [comment]
This is already in progress

**Comment by radhikanarang24** [comment]
Hey
Just wanted to check if we have TypeScript support available with Search UI?

**Comment by JasonStoltz** [comment]
Not yet

**Comment by subsocialdev** [comment]
> This is already in progress

Hey @JasonStoltz, would you mind sharing with us the progress on adding TypeScript support, please?

If it's not ready, what is the best working draft so we could start using it today?

**Comment by JasonStoltz** [comment]
We had a WIP here that I never had the chance to finish: https://github.com/elastic/search-ui/pull/458/files.

I haven't had the time to pursue this recently, unfortunately.

**Comment by torquemad** [comment]
Would appreciate this feature request.

**Comment by JasonStoltz** [comment]
This is being actively worked on in:
https://github.com/elastic/search-ui/issues/613
https://github.com/elastic/search-ui/issues/612
https://github.com/elastic/search-ui/issues/611
https://github.com/elastic/search-ui/issues/610
https://github.com/elastic/search-ui/issues/609

**Comment by joemcelroy** [comment]
Over the last few weeks, we have been converting the project into typescript. This has allowed us to generate typescript definition files for our packages. 

Today we have release this series of changes as a beta in 1.10.0-rc.0 🥳  

Please let us know of any issues on github so we can make sure its stable before it goes to stable release :)

**Comment by yakhinvadim** [comment]
Version **1.10.0-rc.1** is now available!

Since **1.10.0-rc.0** we've improved some types and added type definitions for `search-ui-site-search-connector` package.

As always, please let us know if you have any feedback.
