### ISSUE TITLE
I don't think our stylesheet should rely on a hosted font

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#293]
Currently, an network request is made for https://fonts.googleapis.com if you include the search-ui CSS in a project.

I think this should be inlined if it needs to be a dependency.

https://github.com/elastic/search-ui/blob/121616c4d6647a9f4bc059869d620c083e0b90eb/packages/react-search-ui-views/src/styles/themes/reference-ui/_base.scss#L9

Any thoughts on this?

**Comment by yakhinvadim** [comment]
I think we shouldn't import fonts inside the library. That will allow users to import fonts the way they need it. For example, they might want to import them from their own CDN, or they might want to use display-font property inside their font-face declaration for performance reasons - there was no option to do that in Google Fonts until only a month ago. There could be other reasons to do that.

That would not take much from users, they'll just need to insert the import line anywhere in their own code. But it will give flexibility and performance.

Even the Material UI library, which very highly depends on Roboto asks users to install the font themselves: https://material-ui.com/getting-started/installation/#roboto-font

**Comment by constancecchen** [comment]
Yep, I think [Google Font's new `font-display` support](https://www.zachleat.com/web/google-fonts-display/) alone is a good reason to have users self-link. Performance++ :)

My suggestion/personal preference would be having the default font for Search UI just be [system fonts](https://css-tricks.com/snippets/css/system-font-stack/) (e.g. San Francisco for Mac, Segoe for Windows). Simple, good-looking, and consistent for many users.

**Comment by zumwalt** [comment]
The system font stack we usually use looks something like this: `font-family: system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;`
