### ISSUE TITLE
There should be a clearer relationship between the `disjunctiveFacets` option, and the `any` filter type on facets.

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#306]
> disjunctiveFacets wasn’t very prominently documented, but the filterType="any" behavior wasn’t working as expected (it was hiding other filters when it shouldn’t have been) until I figured out I needed to add this config field.

**Comment by JasonStoltz** [comment]
https://github.com/elastic/search-ui/issues/428 will be implemented to solve this issue.

**Comment by doostinharrell** [comment]
@JasonStoltz I've run into this as well on a project. I have configured `disjunctiveFacets` in my config object and I've added `filterType="any"` to all of my facet components but I'm still seeing values being hidden across facets when making selections. 

**You noted:**
`disjunctiveFacets wasn’t very prominently documented, but the filterType="any" behavior wasn’t working as expected (it was hiding other filters when it shouldn’t have been) until I figured out I needed to add this config field.`

What configuration did you need to implement that solved this for you?

**Comment by JasonStoltz** [comment]
Sorry, this issue had a poor description. I think I was quoting from another conversation quickly to capture the essence of the problem here.

My points was that it is somewhat of a pain to have these two separate sources of configuration when trying to implement facets ... the "facets"/"disjunctiveFacets" configuration in the query, and then the filterType="any" in the individual Facet components. It's a convoluted set up to get what is effectively the default behavior for facets on the internet.

For reference though, I think it is documented fairly clearly in this section of the docs: https://docs.elastic.co/search-ui/api/react/components/facet#example-of-an-or-based-facet-filter
