### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by yakhinvadim** [elastic/search-ui#330]
Now all texts in search-ui components are in English. It is possible to use custom text in components, but you have to provide your own view to achieve that. That could be too much for a single string change. We need to allow users to pass props to our view component that would change the text inside it.

For static texts, that don't depend on any variables, this should be solved by passing a string prop:
```
<MultiCheckboxFacet
  slotShowMoreOptionsText="+ Mostrar más opciones"
  {...otherProps}
/>
```
Example of static text: https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/src/MultiCheckboxFacet.js#L91

For dynamic texts that depend on variables, we'd need a function:
```
<PagingInfo
  slotPagingInfoText={({searchTerm, begin, end, total}) => `Mostrando ${begin} - ${end} de ${total} para: ${searchTerm}`}
  {...otherProps}
/>
```
Example of dynamic text: https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/src/PagingInfo.js#L9

**Comment by JasonStoltz** [comment]
I like that this is very simple and explicit. It would be easy to integrate this with other more sophisticated i18n libraries, like https://github.com/i18next/react-i18next.

That might look something like:

```
<MultiCheckboxFacet
  slotShowMoreOptionsText={t("moreMessage")}
  {...otherProps}
/>
```

OR

```
<PagingInfo
  slotPagingInfoText={({searchTerm, begin, end, total}) => t('someMessage', {begin, end, total, searchTerm}}
  {...otherProps}
/>
```

We should probably accept a Node or a String, as people could want to include html in their strings. Or, use the Trans component from react-i18n for example:

```
<MultiCheckboxFacet
  slotShowMoreOptionsText={<Trans><H1>Welcome to React</H1></Trans>}
  {...otherProps}
/>
```

**Comment by mauricesnip** [comment]
Any updates on this matter? The ["+ More" button](https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/src/MultiCheckboxFacet.js#L79) and [many](https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/src/MultiCheckboxFacet.js#L77) [more](https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/src/MultiCheckboxFacet.js#L65) textual parts are hardcoded in English.
