### ISSUE TITLE
A non-react guide to Search UI

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#332]

**Comment by andymac4182** [comment]
I am looking to do exactly this to replace InstantSearch from Algolia. Can you point me in the right direction? We need a ui to drop into static websites this looks like a great option.

**Comment by yakhinvadim** [comment]
Hey Andrew! 

The best place to start with this would probably be a [README](https://github.com/elastic/search-ui/tree/master/packages/search-ui) of `search-ui` core package. 
We also have a [Vue.js example](https://github.com/elastic/vue-search-ui-demo), that works directly with the headless core. In that repo, take a look in [this file](https://github.com/elastic/vue-search-ui-demo/blob/master/src/components/SearchSection.vue) -- all the interactions with  `search-ui` happen there.

If something is not clear -- feel free to ask a question here, or in our [Gitter](https://gitter.im/elastic-search-ui/community), we can reply there pretty quickly.

Hope it helps!

**Comment by kjetilhp** [comment]
is there (or will there be) a similar example for Angular? (or is something like https://github.com/microsoft/angular-react the way to go..)

**Comment by yakhinvadim** [comment]
@kjetilhp Currently there're no Angular examples that I've known of, but we do consider creating more examples of Search UI.

I haven't used angular-react, so I can't say if it will work 🤷‍♂

**Comment by kjetilhp** [comment]
+1 for an Angular example 👍

**Comment by czmarcos** [comment]
@andymac4182 I'm in the same situation...Did you manage to replace algolia instant search js with elastic search (non-react solution)?

**Comment by codebunt** [comment]
If it is of any help here is a simple webcomponent version of search ui. https://github.com/codebunt/elastic-searchui-webcomponents . Since webcomponents are framework agnostic it can be used in angular or react.

**Comment by JasonStoltz** [comment]
@codebunt Very cool! Thank you for sharing!

**Comment by darrynhoskingluna** [comment]
I also came accross this while looking for an angular based implementation.
I did manage to figure out how to get it working through angular. 

https://github.com/dchosking/angular-search-ui-demo
* This is still mostly a work in progress but it is working so perhaps someone else might find it useful

**Comment by yakhinvadim** [comment]
@darrynhoskingluna That is awesome, thanks for sharing! Do you mind if we add a link to your demo in Search UI documentation?
