### ISSUE TITLE
Add "" to PagingInfo component

### ISSUE THREAD

**Issue by yakhinvadim** [elastic/search-ui#337]
Now if a user doesn't provide a search term it looks a little weird:
![image](https://user-images.githubusercontent.com/11838280/61223096-60552500-a6f2-11e9-9e32-6c6ca29e89f6.png)

It would look better with "":
![image](https://user-images.githubusercontent.com/11838280/61223116-69de8d00-a6f2-11e9-87be-b91d71bbf0ed.png)

**Comment by constancecchen** [comment]
Alternatively, would it also make sense to get rid of the `for` if we're purposely doing a blanket filter/category search term? e.g.,

`Showing 1-20 out of 2005:`

**Comment by Kacppian** [comment]
@constancecchen  I agree with you, removing "for" makes more sense. I just tried out both of them, I like removing the "for". Here's some screenshots - 

**Without `for`**
![Screenshot from 2019-07-20 01-25-06](https://user-images.githubusercontent.com/14990078/61562013-f63fd580-aa8d-11e9-855e-3cb7a577eaca.png)

**With quotes**
![Screenshot from 2019-07-20 01-25-28](https://user-images.githubusercontent.com/14990078/61562148-43bc4280-aa8e-11e9-9911-e40176261622.png)

**Comment by JasonStoltz** [comment]
@Kacppian I agree, removing the for entirely looks much better.

**Comment by Kacppian** [comment]
Awesome, I'll implement the change then. 

I see `lib/` `es/` and `src/` in the directories under `react-search-ui-views`. Could you please help me understand why that is the case? I'm a little lost. There are a bunch of PagingInfo.js files, do I have to make the same change across the files?

**Comment by Kacppian** [comment]
Do we remove just the word `for` and still show the `searchTerm` or we want to get rid of everything that follows `for`?

**Comment by Kacppian** [comment]
Submitted the PR

**Comment by JasonStoltz** [comment]
Closed by https://github.com/elastic/search-ui/pull/360
