### ISSUE TITLE
Make it more obvious in app-search-connector docs to use endpointBase option for SMAS

### ISSUE THREAD

**Issue by yakhinvadim** [elastic/search-ui#369]
See Gitter question: https://gitter.im/elastic-search-ui/community?at=5d37aeb1d618874164279e3d

**Comment by robhawkins** [comment]
@JasonStoltz it would be handy if `endpointBase` could be mentioned in the blog post

https://www.elastic.co/blog/how-to-build-great-react-search-experiences-quickly
