### ISSUE TITLE
endpointBase is not taken into account in AppSearchAPIConnector

### ISSUE THREAD

**Issue by consulthys** [elastic/search-ui#370]
When going through the tutorial shown in [How to Build Great React Search Experiences Quickly](https://www.elastic.co/blog/how-to-build-great-react-search-experiences-quickly) using a self-managed AppSearch instance (ES 7.3.0, AppSearch 7.3.0, Node 10.16.0), I hit the following issue when the `AppSearchAPIConnector` is being instantiated:

> Error: engineName, hostIdentifier, and searchKey are required

After searching a bit, I figured out that it should be possible to specify `endpointBase` instead of `hostIdentifier` for local AppSearch instance. Yet, it doesn't seem to work in my case.

Looking at the code for `AppSearchAPIConnector`, I see this:
https://github.com/elastic/search-ui/blob/47ff88775332c2bfcbc70ae7d7dfc9699cfa6c73/packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js#L58-L60

Looking further into how the `SwiftypeAppSearch` client is created, I was able to provide a dummy value for `hostIdentifier` to get past this error so that the client can be created and the `endpointBase` value can prevail:
https://github.com/swiftype/swiftype-app-search-javascript/blob/master/src/client.js#L50-L52

My connector configuration looks like this:

```
const connector = new AppSearchAPIConnector({
    searchKey: "search-xyz",
    engineName: "video-games",
    endpointBase: "http://localhost:3002",
    hostIdentifier: "blah"          <--- if I remove this line, it should work, but doesn't
});
```
Other similar issues:
* https://github.com/elastic/search-ui/issues/48
* https://github.com/elastic/search-ui/issues/83
* https://github.com/elastic/search-ui/issues/369

**Comment by yakhinvadim** [comment]
Hey Valentin,
Really appreciate that you described the issue in such detail and I'm glad you found a workaround for this. It looks like it shouldn't be hard to fix, so I expect it to get into the next Search UI version.

**Comment by Jfelix61** [comment]
I'll be adding this promptly! Thanks for the Issue, and the detail on it as yakhinvadim said.
