### ISSUE TITLE
Swapping 2 filter values

### ISSUE THREAD

**Issue by SwannLV** [elastic/search-ui#387]
Hello, thank you for your library, it helps me a lot.
Here is my issue:

I would like to be able to swap 2 values in my filter.
- I have tried using `removeFilter`, then `addFilter`, but this does'nt work because of the refresh of `removeFilter`. `addFilter` will never be played.
- I have tried to use `setFilter`, but this will clear all other filter values I have set

-> Is there any other way I could do that?
-> Would it be possible to have a `resfresh` option on `removeFilter` like in `setSearchTerm`?

Thank you very much

**Comment by JasonStoltz** [comment]
@SwannLV You are correct, and I believe I have a fix for this. I will try to push it out in the next day or two.

The fix for this is to "batch" actions before executing them.

**Comment by SwannLV** [comment]
@JasonStoltz waiting a lot for it, thank you 🙏😀

**Comment by JasonStoltz** [comment]
Closing in favor of https://github.com/elastic/search-ui/issues/65
