### ISSUE TITLE
Load extra buckets only when needed using Facet

### ISSUE THREAD

**Issue by SwannLV** [elastic/search-ui#388]
Hello,

I am using the `Facet` with a custom view, called `MultipleCheckboxWithYears`.
It does the same as the original `MultipleCheckboxFacet`, but has a select input added to each line, at the right of each checkbox, where you can select the number of years paired with the item you have checked.

My problem is: I would like to be able to display some buckets for every years of my select input.
I want to query those buckets only when I open my select input, and not after the response of the "regular" query, because it is slow and I am reaching the max number for buckets if I ask for the buckets for every years of every checkbox item.

Is it possible to do so?

Thank you very much.

**Comment by JasonStoltz** [comment]
@SwannLV It sounds like there's not first class support for what you're describing, but I'd bet we can figure out how to do it.

Do you have a visual you could share? I'm having trouble understanding what exactly you are trying to do.

**Comment by SwannLV** [comment]
![image](https://user-images.githubusercontent.com/2593258/64987190-fd863280-d8c8-11e9-8ac8-9f0d2f48b64e.png)
![image](https://user-images.githubusercontent.com/2593258/64987214-0aa32180-d8c9-11e9-8ed1-f74ee3aa8944.png)
![image](https://user-images.githubusercontent.com/2593258/64987291-2dcdd100-d8c9-11e9-8e58-9c6dee7f0d15.png)

**Comment by SwannLV** [comment]
I want to see the "skill 0" with 2 years of experience.
Here we can see that for each skill, I can display the number of result for years between 0 and 4, but i can't ask more buckets otherwise it reaches the limit.

I would like to be able to query the bucket for all the years for "skill 0" only when I open the select input.

**Comment by JasonStoltz** [comment]
@SwannLV Ah, ok. I see what you are saying. I've thought about this before, and even put an issue in to deal with this: https://github.com/elastic/search-ui/issues/285.

I'm going to take some time today to think about how you can work around this for now and I'll propose a solution for you.

**Comment by JasonStoltz** [comment]
@SwannLV How do you have your data modeled? Something like this?

```
jobs: [
  {
    skill: ["programming", "leadership"],
    programming_experience: 5, 
    leadership_experience: 20,
    account_experience: 0
  }
]
```

Also, are you using Elastic App Search?

The general gist of the solution I have for you is to override the "onSearch" handler in your driver: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#overriding-connector-handlers.

This documentation needs to be updated, because that `onSearch` parameter has a third parameter, "next", which lets it be used like middleware, so you have the opportunity to dynamically add additional "facets" (or "buckets" as you are referring to them) based on the currently selected filter values.

Here's a quick example of something I threw together. This basically checks if a user is filtering on a particular field, "category1", and if it is and the selected value is "Shirts", then it ALSO requests "category2" as a facet.

```
onSearch: async (state, queryConfig, next) => {
    

    // Check if the category1 facet is applied
    const category1 = state.filters.find(f => f.field === "category1");

    // Assuming that it is applied, and the "Shirts" value is selected, then
    // we'll also need to fetch the Category2 facets
    const category2Facets =
      category1 && category1.values.includes("Shirts")
        ? {
            category2: { type: "value" }
          }
        : {};
    
    const response = await next(
      {
        ...state,
        filters: state.filters
      },
      {
        ...queryConfig,
        facets: {
          ...category2Facets,
          ...queryConfig.facets
        }
      }
    );
    return response;
  }
```

The live example is here: https://codesandbox.io/embed/search-ui-conditional-facets-example-8qd6u

I believe you should be able to get this to work. Let me know if you have any questions.

**Comment by JasonStoltz** [comment]
This actually might work for you as well. It's slightly simpler: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#query-config. See the "conditionalFacets" option.

**Comment by SwannLV** [comment]
Thank you very much. 

I have tried to use `conditionalFacets` inside the config given to the `<SearchProvider />`,  but I can't figure out why I am not entering the function.

I had the same issue with `disjunctiveFacets`, no way to make it work.

And I only get 2 parameters for my onSearch.

Any idea? 

I am using 
```
"@elastic/react-search-ui": "1.0.0",
"@elastic/react-search-ui-views": "1.0.0",
"@elastic/search-ui": "^1.0.0",
```

**Comment by JasonStoltz** [comment]
Hey @SwannLV.

I understand now.

When using elasticsearch, you are using the library without a "Connector". If you are not using a "Connector", then none the configuration in https://github.com/elastic/search-ui/blob/master/ADVANCED.md#query-config will apply. This includes "disjunctiveFacets" and "conditionalFacets".

That means, if you want to implement any of those things, you'll need to do so in `onSearch`.

Additionally, you are right, if you are not using a connector, then the "onSearch" method will not receive that third parameter.

 Sorry, I'm realizing now that the docs are not very clear about this. Here is the relevant section: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#implementing-handlers-without-a-connector.

I will spend some time updating the elasticsearch example to include these two things. Hopefully that will help.

**Comment by JasonStoltz** [comment]
Closing in favor of: https://github.com/elastic/search-ui/issues/389
