### ISSUE TITLE
Disjunctive facets without the use of a connector

### ISSUE THREAD

**Issue by SwannLV** [elastic/search-ui#389]
Hello,

I would like to know how to implement a custom query for a Facet that would act like `disjunctiveFacets` would do. 
I don't use a connector so I can't use disjunctiveFacets option...

Thank you very much !

**Comment by JasonStoltz** [comment]
@SwannLV FYI, I've updated our elasticsearch example to include disjunctive faceting: https://github.com/elastic/search-ui/pull/395.

Hopefully that helps you along.

**Comment by SwannLV** [comment]
Thanks, I'll try that !

**Comment by JasonStoltz** [comment]
@SwannLV We'd really like to make the experience of using Search UI with elasticsearch much easier. If you have any feedback after using Search UI with elasticsearch, please share it with us!
