### ISSUE TITLE
Make isFilterable (searchbox) in facets dynamically updating options

### ISSUE THREAD

**Issue by axelhildingson** [elastic/search-ui#396]
A feature that would be great to have is a way to dynamically update options in facet based on the searchTerm in the search box of the facet. Especially when you have more than 250 different search options in the elastic. 

Something like: 
`<Facet field='type' label='Type' filterType='any' isFilterable={true} dynamic={true} />`
or a new Facet
`<DynamicFacet field='type' label='Type />`

**Comment by JasonStoltz** [comment]
Hi @axelhildingson. I want to make sure I understand correctly. I'm going to rephrase your question, let me know if this sounds correct:

You have a facet that has over 250 different values. Currently, you are returning all of them on a single API request, which can be very large.

Because you have so many facet values, you are using "isFilterable" to help users find the correct facet value to select.

To avoid having the large response with 250 different values, you would like to perform the "isFilterable" search server side.

**Comment by axelhildingson** [comment]
yes correct 👍 

The issue is that I have a lot more than 250 rather 10000. So the only way to access all of them is to filter on server-side. 

Here is an example from Algolia:
https://react-instantsearch.netlify.com/examples/e-commerce/
If you write something in a facet ( example brand ) will you get a response with new facets suggestion that you can choose from.

**Comment by JasonStoltz** [comment]
@axelhildingson Wow, yes, that is a lot. You are using Elastic App Search I assume? The 250 facet limit is possibly too low. We're talking about lifting that, but it sounds like that still wouldn't solve things for you. 10,000 is a lot. Out of curiosity, what type of data is in that field?

**Comment by axelhildingson** [comment]
Yeah it is, ( we use App search )
We are a company that sells second-hand clothes so we have a lot of unique items in our database which generate a lot of different brands and types 😫. 

As you said a higher limit is always good but will not solve the issue. Another nice feature that we would like to have that is similar to this issue is a hierarchical menu that filters on server-side.

**Comment by JasonStoltz** [comment]
@axelhildingson OK, so it sounds like you have the following issues:
1) You are unable to show 10,000+ facet values at once [App Search limitation]
2) You are unable to apply over 32 filters [App Search limitation]
3) You need to implement hierarchical facets.

Re: hierarchical facets, is something like this what you had in mind? https://swiftype.github.io/swiftype-app-search-hierarchical-facets-example/

**Comment by axelhildingson** [comment]
Yes, sound about right. 

2. unlimited... I can't an exact number but at least more than 5000.
3. The example is exactly what I am looking for, so ignore this for now. 

Do you have any eta on  1 and 2? we use self-hosted app search at the moment.

**Comment by JasonStoltz** [comment]
3. That example may be challenging to implement in Search UI, but I could help you figure it out.

I don't have an ETA on 1 and 2.

**Comment by axelhildingson** [comment]
I looked into problem 2 and found an alternative way that could solve the issue. The problem we have is that we want to filter and search on part of the index. For example, we want our customers to see and the filter on all items that they have purchased and not returned.

We want to have some kind of base filtering or initalState that will include just a part of the index and then filter on just that part.  The problem I found with initalState is the 32 options limitation and I can't find a way to make a filter that works like filter1=true or filter2=true.

I found a solution for now by adding text the search query and then filter the result. But a good way of solving this is the future is to add some kind base query in the config, this could be implemented with Query Parser Syntax which makes it possible to build something like `status:sent OR status:paid and  user:<username> AND NOT return:true`

**Comment by axelhildingson** [comment]
I have looked into problem 2 and the limitation that is an issue for us is the max limit of 1024 items in one array.

**Comment by JasonStoltz** [comment]
@axelhildingson What is the functional difference between those two queries? I'm pretty sure they are functionally equivalent.

**Comment by JasonStoltz** [comment]
What is the query you are attempting to apply?

**Comment by JasonStoltz** [comment]
I also wanted to pass this along, in case you hadn't seen it, though it sound like you are aware of the query limits already: https://swiftype.com/documentation/app-search/limitations#query-limits

**Comment by axelhildingson** [comment]
the functionality is the same but it is possible to add more filter options if you put them in an array (max 1024),  instead of separate objects (max 32 ). 

So one way of solving this is to add a configureFilter() function where you could configure your own filter setup.
