### ISSUE TITLE
Facets will break if a document includes an empty string

### ISSUE THREAD

**Issue by axelhildingson** [elastic/search-ui#401]
Facets will break if a document includes an empty string.

![Skärmavbild 2019-10-01 kl  12 05 32](https://user-images.githubusercontent.com/7069084/65953212-cc1e7280-e443-11e9-9349-3e2d0ef92881.png)

I think the issue is hidden here: 
https://github.com/elastic/search-ui/blob/ba689c64f28ae65b84064be903367687e7547c7f/packages/search-ui-app-search-connector/src/responseAdapter.js#L8

**Comment by JasonStoltz** [comment]
@axelhildingson What is the behavior you are expecting? I'm inclined to filter out facet values that have an empty string.

**Comment by axelhildingson** [comment]
I looked at the PR and this will solve the issue 👍
