### ISSUE TITLE
npm install doesn't work on Windows machine

### ISSUE THREAD

**Issue by Uxoos** [elastic/search-ui#406]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle root@~pretest: root@
6 info lifecycle root@~test: root@
7 verbose lifecycle root@~test: unsafe-perm in lifecycle true
8 verbose lifecycle root@~test: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;O:\ProgramLocal\ProjectsNodeJS\lerna-repo\node_modules\.bin;C:\Users\uxooo\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Windows\system32\WBEM;C:\Windows\system32\WBEM;C:\Windows\system32\WBEM;C:\Windows\system32\WBEM;C:\Windows\system32\WBEM;C:\Windows\system32\WBEM;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\uxooo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\cmd;C:\Users\uxooo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\Users\uxooo\AppData\Local\Microsoft\WindowsApps;C:\Users\uxooo\AppData\Roaming\npm
9 verbose lifecycle root@~test: CWD: O:\ProgramLocal\ProjectsNodeJS\lerna-repo
10 silly lifecycle root@~test: Args: [ '/d /s /c', 'lerna run test --stream --no-private' ]
11 silly lifecycle root@~test: Returned: code: 1  signal: null
12 info lifecycle root@~test: Failed to exec test script
13 verbose stack Error: root@ test: `lerna run test --stream --no-private`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid root@
15 verbose cwd O:\ProgramLocal\ProjectsNodeJS\lerna-repo
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error root@ test: `lerna run test --stream --no-private`
22 error Exit status 1
23 error Failed at the root@ test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by yakhinvadim** [comment]
Thanks, @Uxoos!

It looks like you're trying to develop search-ui locally on a Windows machine. Unfortunately, we do not support Windows for now. But you can install [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/faq) which search-ui should work fine with. We have a merged PR that have more info on this issue: https://github.com/elastic/search-ui/pull/361

Let me know if you have more questions.

**Comment by yakhinvadim** [comment]
I'm going to leave this open for more visibility.

**Comment by Uxoos** [comment]
RESOLVED. I change in every package.json files from
  "scripts": {..."build-js": ".\bin\build-js'",...}
to
  "scripts": {..."build-js": "babel src --out-dir lib --ignore '**/*.test.js' && babel src --out-dir es --ignore '**/*.test.js'",...}
Replace path to file => body of file.

**Comment by yakhinvadim** [comment]
I'm glad you found a workaround.

We'll still need to fix it, so I'll reopen this issue. Also, it might help other Windows users.
