### ISSUE TITLE
pagination previous and next page titles are in wrong language.

### ISSUE THREAD

**Issue by philwilliammee** [elastic/search-ui#407]
The pagination on the demo site has incorrect  language for the previous and next pages titles. The titles are always in Chinese 上一页 and 下一页 even when language and locale is set to English.
steps to reproduce:
- [ ] goto https://search-ui-stable.netlify.com/ from a lang="en" locale
- [ ] press enter in search bar to get all results
- [ ] scroll down to pagination footer
- [ ] hover over previous or next chevrons note title apears on hover with the wrong language (see image below)
![image](https://user-images.githubusercontent.com/4685094/66274703-535a5480-e84f-11e9-8619-17d8767d9efe.png)
- [ ] inspect `<li>` element notice title text value
```html
<li title="上一页" class="rc-pagination-disabled rc-pagination-prev" aria-disabled="true">
```

**Comment by yakhinvadim** [comment]
Hey, @philwilliammee, thanks for reporting this!
We fixed it in https://github.com/elastic/search-ui/pull/408 and you can expect to see changes in the next 1.3 release.
