### ISSUE TITLE
would you mind to provide a online demo?

### ISSUE THREAD

**Issue by xycloud** [elastic/search-ui#41]

**Comment by JasonStoltz** [comment]
Yes, this is definitely something we'll plan to provide in the future.

**Comment by xycloud** [comment]
hi @JasonStoltz , any progress?

**Comment by JasonStoltz** [comment]
Hi @xycloud, no progress on an online demo. The README is fairly comprehensive as is: https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/README.md. As we push towards a 1.0 release we will be putting some more thorough tutorials together as well as some online examples.

**Comment by JasonStoltz** [comment]
Hi @xycloud,

A demo has since been added to the README: https://search-ui-stable.netlify.com/

There is also a demo here: https://swiftype.com/search-ui

And an interactive demo here: https://codesandbox.io/embed/search-ui-national-parks-example-kdyms
