### ISSUE TITLE
Grouping documents breaks pagination & more

### ISSUE THREAD

**Issue by XigeTime** [elastic/search-ui#412]
The grouping features seems to break pagination, total results, and results per page when using the Reference UI or Search UI.

To reproduce, download the Reference UI/Search UI and apply a grouping rule to one of the fields:
`"group": {
    "field": "doc_group"
}`

The total results, and results per page sections represent the amount results had they not been grouped together, I think this is a little misleading as the amount of visible documents would be considerably less.

The pagination has the same issue. Due to the app thinking there are more results to be shown, it calculates more pages than you need, then some of the pages show blank as there actually aren't that many results.

---

Digging further, I have noticed that when using the grouping feature it won't return any more than 100 results, as opposed to the 1000 allowed when not using the grouping feature.

When making a search I am receiving "172" as the **totalResults** value, however I can only view 100 of them. If I set the results to 200 per page, the totalResults comes through as 172, but the amount of actual results being returned by the API is still 100.

Changing the size field on the group doesn't seem to affect this.

**Comment by yakhinvadim** [comment]
Thanks for opening this issue, @XigeTime! We'll explore this and come back to you at the beginning of the next week. 
If you find any more bugs or have feature suggestions, we'd love to hear about them too.

**Comment by XigeTime** [comment]
Hi @yakhinvadim & @JasonStoltz, thanks for looking into this issue.

It seems that the sort by field is also affected by this issue. Changing the sort works, however this is not reflected in search results, even after a refresh. When removing the group field, the sort by works as expected.

Please keep me updated, thanks, 
Harry.

**Comment by JasonStoltz** [comment]
Hey @XigeTime,

This is actually a known issue in App Search. Unfortunately, with the current "group" implementation, paging and sorting are both known to break or behave unexpectedly.

I do have a temporary solution for you. Add "collapse: true" in your group configuration:

```
"group": { "field": "doc_group", "collapse": true }
```

This *should* fix the issue you are experiencing with paging and sorting.

** There is one caveat to this ** - If the doc_group field you are grouping on can have multiple values, the field collapsing will not work correctly. You must ensure that document have one single values for `doc_group`.

Let me know if this helps!

**Comment by JasonStoltz** [comment]
@XigeTime I'm going to close this issue, as what I've suggested is the only workaround in App Search, and it's not technically an issue with Search UI. Hope you get it working!

**Comment by XigeTime** [comment]
Hi @JasonStoltz, thanks for looking into this for me!

I have applied the collapsing rule, and this seems to have fixed the issues with pagination!

Sort by still seems to have no affect on the results though which I can't figure out. Works when grouping is removed. Any ideas? I can send a link to our current App Search if this could help.

This seems to also ignore curations, which is less than ideal.

Is there somewhere I can open issues with App Search? Or follow the updates?

**Comment by JasonStoltz** [comment]
@XigeTime I entered an issue in App Search in our internal system about the issues with paging and sorting, I will find out for you what other channels are available for following along with App Search issues.

As for sorting, this is the demo I put together to illustrate this issue in the ticket. Note how in the source after you change "collapse" to true, the sorting starts to work correctly: https://codesandbox.io/s/app-search-grouping-issue-4xggl.

So, sorting should work for you. I think the only way I'll be able to help you out is if you can set up a code sandbox or send me a link to your current App Search.

**Comment by XigeTime** [comment]
Hi @JasonStoltz, sorry! The sorting seems to be working correctly now too. Seems it was an issue with my grouping rather than the sorting. Thank you very much for your help on that.

I can't seem to get Curations to work either, they show up fine when I disable the grouping. is this a known issue too, and is there a possible work around?

Many thanks, Harry.

**Comment by JasonStoltz** [comment]
@XigeTime Hey! Glad you got it working.

Curations will not currently work with grouping. I will ask around about a workaround.

> Is there somewhere I can open issues with App Search? Or follow the updates?

If you go through support and file a bug or Enhancement Request with them, they will create a request with a tracking number which you will be able to follow.

**Comment by JasonStoltz** [comment]
@XigeTime Also, to be fully transparent, the other issue you may run into with grouping is that if you are using Facets, the counts may not be correct. The counts will show the number of total results, while the paging and totals work off the total number of groups.

**Comment by XigeTime** [comment]
Hi @JasonStoltz, thanks for letting me know. Luckily, I had already removed these counts, so this shouldn't be an issue for me.

Please do let me know if you find a workaround for the curations!

Much appreciated
