### ISSUE TITLE
Trigger search after changing data externally.

### ISSUE THREAD

**Issue by phlash-zero** [elastic/search-ui#419]
I have wrapped search-ui component into another component. Data for this is set externally.
Is there a way to trigger search or re-render data everytime input data changes ?

If the config to Provider changes does is the search-ui re-rendered ?

**Comment by JasonStoltz** [comment]
Hi @phlash-zero, can you please post some code examples? I'm not sure I understand what you are asking.

And Provider only reads from config on mount. So you'd need to force a full remount when changing configuration. I think it would be unusual to need to do that, if you need to do that you may be trying to do something incorrectly.

I may be able to help but I'd need some code examples to illustrate.
