### ISSUE TITLE
Numeric filter fails from query parameters

### ISSUE THREAD

**Issue by omegahm** [elastic/search-ui#42]
I have a dataset which includes a numeric field `difficulty`.

I want to filter on this, so I add a filter with `addFilter("difficulty", 2)`. This works great and filters my result set with the difficulty of 2. It also adds `?fv-difficulty=2` to my query parameters. If I then refresh my page I get the following error: 

```
Error: [400] Filters contains invalid value for field: difficulty; must be a number, an array of numbers, or a range object with `to` and/or `from` keys
    at handleErrorResponse (swiftype_app_search.umd.js:362)
```

**Comment by omegahm** [comment]
I get the same error when using a filter with `location` (as documeted here https://swiftype.com/documentation/app-search/api/search/filters#geo-filters) 

```
Error: [400] Filters contains invalid distance for field: location; must be numeric
    at handleErrorResponse (swiftype_app_search.umd.js:362)
```

It works when first using it, but if I refresh the page, it's all of a sudden not a number anymore.

The query param here is e.g. `?fv-location%5Bcenter%5D=36.02508454879372%2C-116.84603691101076&fv-location%5Bdistance%5D=300&fv-location%5Bunit%5D=km&size=100`

**Comment by JasonStoltz** [comment]
Yes, unfortunately when we serialize a filter to the url, we lose any notion of its data type, and even the filter type. I'm going to try to change the query string conventions to maintain data type. So for value filters it'd be something like:

filter params have the format:
{f}{v}{n}-{someField}={100}
1 - "f" - meaning "filter"
2 - "v" - filter type, "r" range, "value", or "g" geo
3 - "n" - data type, "n" for number, "d" for date, nothing for default for filter type -- "text" for "value" filters and "geo" for "geo" filters.
4 - {someField} - field name
5 - {100} - field value to filter on. {lower}_{upper} if "range", {center}_{distance}_{unit} if "geo"

Examples:

"value" filters:
"fv-somefield=100" - "value" filter on "somefield" with "100" (text)
"fvn-somefield=100" - "value" filter on "somefield" with 100 (number)

"geo" filters (we don't have support for those yet):
"fg-somefield=36.02508454879372%2C-116.84603691101076_300_ km" - "geo" filter on "somefield" (geo)

"range" filters:
"frd-somefield=10-10-2019_11-10-2019" - "range" filter on "somefield" between "10-10-2019" and "11-10-2019" (date)
"frn-somefield=100_1000" - "range" filter on "somefield" with between 100 and 1000 (number)
