### ISSUE TITLE
Thumbnail support for Result component

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#425]
Add an "imageField" prop to the Result component which would let you specify a field from the result object to use to populate a thumbnail image. An example of what this might look like can be found here: https://codesandbox.io/s/video-games-tutorial-with-images-5wsqs.

https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/src/containers/Result.js

**Comment by PRASHANT1104** [comment]
@JasonStoltz can i work on this  ?

**Comment by JasonStoltz** [comment]
@PRASHANT1104 That would be great.

**Comment by PRASHANT1104** [comment]
@JasonStoltz So i have added the field of thumbnail image . What did you mean by  "let you specify a field from the result object to use to populate a thumbnail image" ?  I didn't get you , how do you wish to populate the thumbnail image ?

**Comment by JasonStoltz** [comment]
Ah, sorry, this ticket probably didn't have enough detail.

From a user perspective, they would code something like this

```
            <Results
              thumbnailField="imageUrl"
            />
```

A users data would look like the following:

```
{
  "id": "1",
  "imageUrl": "https://path.to/some/image.jpg"
}
```

Inside of the [Result](https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/src/Result.js) component, you would have logic that reads from the `thumbnailField` parameter and populates a thumbnail if it is present:

```
result[thumbnailField].raw && <img
          src={result[thumbnailField].raw}
          alt="thumbnail"
        />
```

The `thumbnailField` would need to be optional, so we would only display a thumbnail if it was present. If it was not present, the Result component would need to render as it does today. This is for backwards compatability.

Does that make sense?

**Comment by PRASHANT1104** [comment]
Yes .Thanks !

**Comment by rkalghatgi** [comment]
This is a really awesome example, I was looking for how to customize my own results view. One question regarding dangerouslySetInnerHTML={{ __html: result.name.snippet }} 

My data is a paragraph of text that describes a company's capabilities. Snippet is too short, I would like to return the whole paragraph with the search highlights as well. I tried using result.name.raw, but that did not provide the highlights. What would I use to show the entire text + highlights? Thanks!

**Comment by JasonStoltz** [comment]
Hey @rkalghatgi, with App Search, you cannot get the entire field with highlights. Snippets let you increase the size up to a max of 1000, if that helps.

You *could* write your raw value to the page and do the highlighting yourself. It's less effective that way as you don't have stemming. (i.e., if the match was on "park" but the user searched for "parks"). Also you need to trust your data extremely well if you're going to use `dangerouslySetInnerHTML` with `raw`. `snippet` values are sanitized, `raw` values are not.

Hope that helps!

**Comment by rkalghatgi** [comment]
Thanks. Why is snippet limited to 1000?

**Comment by JasonStoltz** [comment]
I think it's just an unusual use case. Most search experiences show you a "snippet" of matching text in a search result, and if you want to see more you click on a link to follow it through to a detail page.

If you want to continue this conversation let's move it elsewhere, I'd like to keep this issue focused on thumbnail support.
