### ISSUE TITLE
[Feature Request] A 'contains' filter type for filtering on Arrays of data

### ISSUE THREAD

**Issue by XigeTime** [elastic/search-ui#432]
Would be great if we could have a filter option that allows us to check if an array contains a value.

For example, a document has the field "colours" with the value of: ['blue', 'black', 'red']
I would like the ability to set a filter for colour, that will look through the array for a match.

So if we set the filter as { colour: 'black' }, it should return true, as black is a value inside the array.

**Comment by JasonStoltz** [comment]
Hi @XigeTime,

This is already possible, that is how filters work in App Search.

```
setFilter("colours", "black")
```

Unless I'm missing someth8ing.

**Comment by XigeTime** [comment]
Hi @JasonStoltz,

I just tried this, and could not get it to work?

The filter I have set is:
![image](https://user-images.githubusercontent.com/3460593/68153291-29bf4680-ff3d-11e9-97eb-b45f2443b76c.png)
This is set like you stated above, `setFilter('collection0', this.props.collection, "any");`

I have a document that should match if the filters should indeed work like that, but I get no results?
![image](https://user-images.githubusercontent.com/3460593/68153457-6723d400-ff3d-11e9-9746-b429853cb81e.png)

The field type is set to text if that helps.

Cheers

**Comment by JasonStoltz** [comment]
@XigeTime If your data was indexed as a javascript array, then that will work:

```
[
    "trythis",
    "blue",
    "howaboutthis"
  ]
```

If for some reason you indexed it as a stringified javascript array, then it won't work:

```
"[\"trythis\",\"blue\",\"howaboutthis\"]"
```

Beyond that I'm not sure what to tell you, the API is meant to accept arrays of strings and allow you to filter on individual array values.

Hope that helps,

Jason
