### ISSUE TITLE
IE11 error. 

### ISSUE THREAD

**Issue by axelhildingson** [elastic/search-ui#433]
Search-ui crash if you open it in IE11. 

I have seen multiple issues one of them is this,
![Skärmavbild 2019-11-04 kl  10 54 32](https://user-images.githubusercontent.com/7069084/68112393-83018880-fef1-11e9-9231-81236f401e50.png)

**Comment by yakhinvadim** [comment]
Hey @axelhildingson!

We officially support evergreen desktop browsers (Edge, Firefox, Opera, Chrome, Safari) and the latest Chrome for Android and iOS Safari.
Although it is possible to include opt-in polyfills, we think it's better to focus our efforts on improving Search UI for the majority of users with the browsers above.

Is this a dealbreaker for you?

**Comment by axelhildingson** [comment]
The issue I found is a dependency ( debounce-fn ) that does not compile the code to javascript ( not es6 ). I solve it for now with a post-install script but it would be great if we change it to another dependency.

**Comment by AndrewTziAnChan** [comment]
@axelhildingson Our team is running into an issue using search-ui that I think may be related to IE11. What did you specifically do to solve your issue?

**Comment by JasonStoltz** [comment]
Fixed by https://github.com/elastic/search-ui/pull/448.
