### ISSUE TITLE
Search-UI smart url forces extra history push

### ISSUE THREAD

**Issue by AndrewTziAnChan** [elastic/search-ui#434]
When going to a page with Swiftype, there is an extra browser history push on component load.

For example, on the [CodeSandbox ](https://codesandbox.io/s/national-parks-example-kdyms?fontsize=14)demo on the Readme for this project, the url navigates from

**https://kdyms.csb.app/**

to

**https://kdyms.csb.app/?size=n_20_n**

A browser back navigation action can be triggered and the url will change from **https://kdyms.csb.app/?size=n_20_n** to **https://kdyms.csb.app/** which does not seem like ideal behavior.

If I navigated from **google.com** to **https://kdyms.csb.app/**, I'd expect hitting the back button on the browser from **https://kdyms.csb.app/?size=n_20_n** to navigate back to **google.com**, not to **https://kdyms.csb.app/**.

**Comment by AndrewTziAnChan** [comment]
Need to investigate issue more.

**Comment by JasonStoltz** [comment]
@AndrewTziAnChan This is a valid issue, I'm glad you entered it. I actually have an issue in this project to capture it already.

**Comment by JasonStoltz** [comment]
https://github.com/elastic/search-ui/issues/176

**Comment by AndrewTziAnChan** [comment]
@JasonStoltz For additional details, I suspect part of the issue is due to our application's use of react-router-dom. Our application will route to a different component render like in the case of going from a home page to a search page. React router then of course keep that history, especially in the case when a history push is made by search-ui.

We can do forgo react router and use form.submit redirect to force a page load, but my team here wanted to know if you had any guidance for this issue?

**Comment by AndrewTziAnChan** [comment]
I've created a pull request for a change that we made on our fork.

#443

**Comment by FokkeZB** [comment]
@JasonStoltz any update on this issue? We're affected by it too.

https://zapier.com/help/search?q=apps > click any result > back 2x

**Comment by JasonStoltz** [comment]
@FokkeZB I apologize, I've been a bit busy lately 😫. I'll see if I can resolve this today, and if so I'll consider pushing it immediately in a patch release.

**Comment by JasonStoltz** [comment]
@FokkeZB @AndrewTziAnChan Should be fixed in 1.3.1

https://codesandbox.io/s/search-ui-national-parks-example-kdyms
