### ISSUE TITLE
Errors when rendering SearchProvider in IE11

### ISSUE THREAD

**Issue by AndrewTziAnChan** [elastic/search-ui#437]
When attempting to render the SearchProvider component within IE11, the following errors are shown as related:

Cannot modify non-writable property 'length'

Unable to get property 'tearDown' of undefined or null reference

Is there any guidance on how read these issues?

**Comment by AndrewTziAnChan** [comment]
This IE11 issue seems to stem from attempting to use Object.defineProperty within mimic-fn from within debounce-fn, specifically when assigning the property 'length' of the mimicking function. Only in IE11. I've created a pull request to use a simpler, less robust debounce function, but one that should work in IE11 given that the appropriate polyfills are imported.

#442

**Comment by andrew-chernous** [comment]
Hi, @AndrewTziAnChan I have the same issues with ie 11. Can you please provide advice about how temporary fix this problem?

**Comment by JasonStoltz** [comment]
https://github.com/elastic/search-ui/pull/442 closes this issue, will release in 1.3

**Comment by AndrewTziAnChan** [comment]
@andrew-chernous Along with the changes from this PR (use different debounce-fn in the DebounceManager), you'll probably need to include the appropriate polyfills. We use [create-react-app polyfills](https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill). Just install the **react-app-polyfill** module into your project and include the following imports into a top level index file.

```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
```

I think you could use just about any polyfill though.

**Comment by andrew-chernous** [comment]
@AndrewTziAnChan Thank you.
