### ISSUE TITLE
New URL filter scheme

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#44]
How do we represent search parameters from the App Search API in a query string? 

Challenge: need to flatten highly nested structure and maintain typing.

Reference: https://swiftype.com/documentation/app-search/api/search/filters

## API Schema

```
{
  “all”: [{
     // Range with type Number
     {"visitors": {
        "from": 1,
        "to": 100
     }},
     // Range with type Date
     {"date_established": {
       "from": "1900-01-01T12:00:00+00:00",
       "to": "1950-01-01T00:00:00+00:00"
     }},
     // Geo with type Geolocation
     {"location": {
       "center": "37.386483, -122.083842",
       "distance": 300,
       "unit": "km"
     }},
     // Value with type Text
     {"world_heritage_site": "true"},
     // Value with type Date
     {“created_date”: "1900-01-01T12:00:00+00:00"},
     // Value with Type Number
     {“visitors”: 100},
     // Combining with "all"
     {“category”: ”fun”},
     {“category”: ”healthy”}
     // Nested "or"s
     {“category”: [”gradeA”, “gradeB”]} 
  }],
  // Combining with "any"
  “or”: { … },
  // Combining with "none"
   “none”: { … },
}
```

## Proposed Query String Schema

f_{filterType}{valueType}{andAnyNone}{_sequence}_{fieldName}{[]}={value}

- filterType: 
  - “v” for Value
  - “r” for Range
  - “g” for Geo.
- valueType:
  - “t” for Text”
  - “d” for Date
  - “n” for Number
  - “g” for Geolocation
- andAnyNone: 
  - “a” for “and”
  - “o” for “any”
  - “n” for “none”
- _sequence: Nothing present if there is only one value, “_1” for the second, then “_2”, etc.
- fieldName
- value:
  - Value filters - just the value
  - Range filter - {low}_{high}
  - Geo filter - {center}_{distance}_{unit}

## Examples

Range with type Number

```
{"visitors": {
   "from": 1,
  "to": 100
}}
     
f_rna_visitors=1_100
```

Range with type Date

```
{"date_established": {
  "from": "1900-01-01T12:00:00+00:00",
  "to": "1950-01-01T00:00:00+00:00"
}}

f_rda_date_established=1900-01-01T12:00:00+00:00_1950-01-01T00:00:00+00:00
```

Geo with type Geolocation

```
{"location": {
 "center": "37.386483, -122.083842",
  "distance": 300,
  "unit": "km"
}}

f_gga_location=37.386483, -122.083842_300_km
```

Value with type Text

```
{"world_heritage_site": "true"}

f_vta_world_heritage_site=true
```

Value with type Date

```
{“created_date”: "1900-01-01T12:00:00+00:00"}
     
f_vda_created_date=1900-01-01T12:00:00+00:00
```

Value with Type Number

```
{“visitors”: 100},
 
f_vna_visitors=100
```

Combining with "all"

```
{"all": [
  {“category”: ”fun”},
  {“category”: ”healthy”}
]}

f_vta_category=fun&f_vta_category_1=healthy
```

Nested "or"s

```
{"all": [
  {“category”: ”fun”},
  {“category”: ”healthy”},
  {“category”: [”gradeA”, “gradeB”]} 
]}

f_vta_category=fun&f_vta_category_2=healthy&f_vta_category_3[]=gradeA&f_vta_category_3[]=gradeB
```

Combining with "any"

```
{"any": [
  {“category”: ”fun”},
  {“category”: ”healthy”}
]}


f_vto_category=fun&f_vto_category_1=healthy
```

None filters

```
{"none": [
  {“category”: ”fun”},
  {“category”: ”healthy”}
]}

f_vtn_category=fun&f_vtn_category_1=healthy
```

**Comment by omegahm** [comment]
I don't know if it's a problem anymore, but I remember at one point, the URI couldn't exceed a certain number of characters (2048 maybe or something?) I think this is also an important thing to keep in mind when designing this schema.

**Comment by JasonStoltz** [comment]
I received some great feedback from @orhantoy on this. He suggested simply placing the entire filters JSON in a query string parameter. I really like that approach for a couple of reasons:

1. Way less work now, and in the future if the filters schema changes
2. There is only one API for applying filters. No need to describe how applying filters via the URL works as opposed to via the JSON schema in API calls.

**Comment by JasonStoltz** [comment]
> he URI couldn't exceed a certain number of characters (2048 maybe or something?)

@omegahm That's a good point. Definitely something to consider for the future. I would think the query string would only approach that length in very extreme edge cases, and it would only be an issue for particular browsers.

**Comment by JasonStoltz** [comment]
So if we encode the JSON into a filters parameter (using the one from above as an example) it would look something like this: 

```
filters=%7B%22all%22%3A%5B%7B%22visitors%22%3A%7B%22from%22%3A1%2C%22to%22%3A100%7D%7D%2C%7B%22date_established%22%3A%7B%22from%22%3A%221900-01-01T12%3A00%3A00%2B00%3A00%22%2C%22to%22%3A%221950-01-01T00%3A00%3A00%2B00%3A00%22%7D%7D%2C%7B%22location%22%3A%7B%22center%22%3A%2237.386483%2C%20-122.083842%22%2C%22distance%22%3A300%2C%22unit%22%3A%22km%22%7D%7D%2C%7B%22world_heritage_site%22%3A%22true%22%7D%2C%7B%22created_date%22%3A%221900-01-01T12%3A00%3A00%2B00%3A00%22%7D%2C%7B%22visitors%22%3A100%7D%2C%7B%22category%22%3A%22fun%22%7D%2C%7B%22category%22%3A%22healthy%22%7D%2C%7B%22category%22%3A%5B%22gradeA%22%2C%22gradeB%22%5D%7D%5D%2C%22or%22%3A%5B%7B%22category%22%3A%22fun%22%7D%2C%7B%22category%22%3A%22healthy%22%7D%5D%2C%22none%22%3A%5B%7B%22category%22%3A%22fun%22%7D%2C%7B%22category%22%3A%22healthy%22%7D%5D%7D
```

It's fairly long, just about 900 characters, and very ugly to look at, but I think that's probably OK, honestly.

We might even be able to find a way to compress that a bit, since it's unreadable anyway.

**Comment by orhantoy** [comment]
The alternative I mentioned would look something like

```
?
filters[all][0][visitors][from]=1&
filters[all][0][visitors][to]=100
filters[all][1][date_established][from]=1900-01-01T12:00:00+00:00&
filters[all][1][date_established][to]=1950-01-01T00:00:00+00:00&
...
```

(Values are not encoded in the example)

**Comment by JasonStoltz** [comment]
I like that as well. The challenge for me I think would be distinguishing between numeric and string values.

i.e.,

For `filters[all][0][visitors]=1` ... is that a string value or a numeric value? I'd need to know that when deserializing from the URL

**Comment by orhantoy** [comment]
Just updated my comment with this:

> But then you lose the types unless you do something extra, like use the key `visitors$n` for numeric fields.

**Comment by JasonStoltz** [comment]
There might be a library that does that for me, serializes to the format you mention and maintains the type info. Would be cool to investigate.
