### ISSUE TITLE
The ability to hide certain fields

### ISSUE THREAD

**Issue by wjsbgsnwss** [elastic/search-ui#445]
I notice that the 'id' and 'title' fields are mandatory (because if I remove these two fields from the 'record._source' it will throw errors) for the results which makes sense. 

However, it is a duplicated information for title and most of the time it is not necessary to display the ID, at least in the scenario of Elasticsearch. 

How can I do this? I don't want to touch anything in the Results.js. If not possible, may I request a new feature of this: specify if the field is hidden or not.

**Comment by JasonStoltz** [comment]
It is not currently possible without customizing the Result view. I have an issue in to address this: https://github.com/elastic/search-ui/issues/426.
