### ISSUE TITLE
Can't reach support

### ISSUE THREAD

**Issue by FokkeZB** [elastic/search-ui#447]
:wave: @JasonStoltz!

When the Swiftype API was shortly unavailable on November 19th, we contact Swiftype support (via support@swiftype.com), but never got an answer. The Swiftype status page didn't list the incident, nor did the Twitter account. The only confirmation and update we got was by a colleague of yours on Twitter: https://twitter.com/xeraa/status/1196743171197280256.

We were glad that the issue was resolved, but the fact that we weren't able to reach support nor got any updates from Swiftype got us worried. What if such an outage took longer?

We are on the Pro plan, which according to https://swiftype.com/app-search/pricing should come with email support.

Any idea what we can/should expect when it comes to support and communication about outages?

Thanks!

- Zapier

**Comment by JasonStoltz** [comment]
@FokkeZB That is concerning indeed. I'm glad you reached out to me about this, I'll escalate this with support and see that you get an explanation!

**Comment by FokkeZB** [comment]
Thanks @JasonStoltz! The reason I opened this issue, and also the reason I was surprised not getting an answer from support, was that it was such a stark contrast with your response time! 👏

**Comment by JasonStoltz** [comment]
💪

**Comment by JasonStoltz** [comment]
Still waiting to hear about the support response, but I can see that there is an incident listed here on status.swiftype.com: https://status.swiftype.com/pages/history/5578eca31ae0f1de7300016c

**Comment by FokkeZB** [comment]
Interesting - we didn't see an incident on the status page when we got alerted around 10am UTC. ¯\_(ツ)_/¯

Anyway, did you hear back from support? We haven't. :(

**Comment by JasonStoltz** [comment]
I'm not sure how often that page gets updated. I'll follow up with your question about support.

**Comment by shanksy01** [comment]
Hi Fokke, we received Support Case 457683 created at 10:19 UTC on 19th Nov from a Fokke Zandbergen, with a reply to email address of contact@zapier.com.
 
Support responded twice to this case at 11:03 & 11:13 UTC on the same day and it auto closed after 10 days, due to no response.

Can you check back to see that the responses were in fact received by your MTA hosting the zapier.com email domain please?

**Comment by FokkeZB** [comment]
Thanks for looking into this @shanksy01! I'll dive into the mail logs.

**Comment by FokkeZB** [comment]
Mixed news @shanksy01 :) Turns out we did get a reply, but it seems your support system dropped whatever our system needs to recognize it as reply to the message we sent from our system and as a result it got ignored :( Now that we know, next time we'll use https://support.elastic.co.

What is not clear to me about https://www.elastic.co/support/welcome/swiftype is that the table seems to suggest that for pro, you don't get any support for urgent cases (like search being down). Am I reading that correctly?

**Comment by shanksy01** [comment]
Thanks @FokkeZB , if you send in an email (from an address that will receive responses) to support@elastic.co and reference the original case number (457683), we can link them up and send over the original responses (unless you want to provide your email in this github issue - please remember that this is an open repo).

Regarding the urgent case support, the website you referenced is accurate and further, there is this website that provides more detail in terms of what each subscription type provides:
https://swiftype.com/app-search/pricing

Hope this helps and if you have any further issues, please don't hesitate to get in contact via support@elastic.co

**Comment by shanksy01** [comment]
I should clarify, the table I dictates the response times Support will apply to the relevant severity of issue. It does not mean standard and pro subscribers are unable to raise Sev 1 or Sev2 issues, it just means all cases raised against a Standard or Pro subscription will be treated as Severity 3.

I hope that clears up any ambiguity here and if not, please let me know.
