### ISSUE TITLE
Marketing page update

### ISSUE THREAD

**Issue by andyg5000** [elastic/search-ui#450]
Just a heads up...

Your marketing page (https://swiftype.com/search-ui) states `npm install react-search-ui search-ui-app-search-connector` as the packages, but should be `npm install --save @elastic/react-search-ui @elastic/search-ui-app-search-connector` as defined in your read me.

<img width="555" alt="Screen Shot 2019-12-19 at 12 51 18 PM" src="https://user-images.githubusercontent.com/1800052/71196736-464dde80-225e-11ea-9b6f-b65d8d06cc97.png">

**Comment by JasonStoltz** [comment]
@andyg5000 Thanks for pointing this out!
