### ISSUE TITLE
search-ui/SearchDriver.js - the same requestSequencer is used for autocomplete and search requests

### ISSUE THREAD

**Issue by matu1104** [elastic/search-ui#452]
Hi,

I'm experiencing a bug when I use the search-ui library. When I type on the search bar, and press Enter quickly, the property isLoading change to True, and then it never gets back to False.

After digging into the code, I realized the issue is on [SearchDriver.js](https://github.com/elastic/search-ui/blob/master/packages/search-ui/src/SearchDriver.js#L124) The search driver is using the same requestSequencer for search and autocomplete requests. In consequence, what is happening is:

1. A query for the search is triggered with sequence number x
2. A query for autocomplete is triggered with a sequence number x+1
3. The query for search returns, but since the sequence number is less than the current seq number (x+1), then it is discarded.
4. The autocomplete query returns.
5. isLoading remains True forever.

I'm working on a fix right now. I would appreciate it if this can be validated as soon as possible since we have a major release in two weeks, and we wouldn't like to go live with this bug.

Thanks!

**Comment by JasonStoltz** [comment]
@matu1104 Thank you for reporting this. We can get this patched immediately.

**Comment by JasonStoltz** [comment]
@matu1104 Can you paste the snippet of code for your `SearchBox` component so we can see we props you have enabled?

**Comment by matu1104** [comment]
Sure,

`
      <SearchBox autocompleteSuggestions={true}
        inputView={({ getAutocomplete, getInputProps }: any) => (
          <>
            <div className={styles.searchBoxWrapper}>
              <input
                autoFocus
                {...getInputProps({
                  placeholder: 'Search HITs, Decorations, Beacons and more',
                  value: srcText,
                  onChange : (e: any) => {
                    setSrcText(e.currentTarget.value);
                  }
                })}
              />
              {getAutocomplete()}
            </div>
            <input type='submit' value='Search' />
          </>
        )}
        onSubmit={() => {
          setSrcText(srcText);
          props.history.push(`/search?q=${srcText}`);
        }}
        onSelectAutocomplete={(selection: { suggestion: string; }, defaultOnSelectAutocomplete: (arg0: any) => void) => {
          if (selection.suggestion) {
            setSrcText(selection.suggestion);
            props.history.push(`/search?q=${selection.suggestion}`);
          } else {
            defaultOnSelectAutocomplete(selection);
          }
        }}
      />
`

I'll open a PR once I finish the change.

**Comment by JasonStoltz** [comment]
Quick note about the steps to reproduce, in order to reproduce the autocomplete query needs to return first.

1. A query for the search is triggered with sequence number x
2. A query for autocomplete is triggered with a sequence number x+1
3. The autocomplete query returns and x + 1 is stored as the "latest response"
4. The query for search returns, but since the sequence number is less than the latest response (x+1), then it is discarded.

isLoading remains True forever.
