### ISSUE TITLE
Numerical field with zero value not supported

### ISSUE THREAD

**Issue by chriscressman** [elastic/search-ui#453]
I generated a reference UI with Elastic App Search and experienced the following problems when a document contained a numerical field with value `0`.

1\. The filter link text displays `[object Object]` instead of `0`:

![zero-filter-value](https://user-images.githubusercontent.com/362928/71741466-fc075880-2e2c-11ea-84d6-de3b394d871e.png)

2\. Clicking the filter link results in the following error:

```
An unexpected error occurred: [400] Filters must specify 'from' and/or 'to' in a range filter for field: inventory
```

3\. Zero values in results documents display as a blank value (no value is displayed):

![zero-value-in-result](https://user-images.githubusercontent.com/362928/71741485-045f9380-2e2d-11ea-8d5e-21640e2ee5e4.png)

__Steps to reproduce (within App Search):__

1. Create an engine
2. Create a schema field with type _number_
3. Index a document whose value for that field is `0`
4. Generate a reference UI
5. Observe the issues described above within the reference UI

**Comment by JasonStoltz** [comment]
@chriscressman Thanks for reporting this, I think this may have fixed the issue: https://github.com/elastic/search-ui/pull/424. The Reference UI is still on version 1.1 so we probably just need to update it in the Reference UI: v
