### ISSUE TITLE
React Router issue

### ISSUE THREAD

**Issue by scheiblr** [elastic/search-ui#461]
First of all thank you for the amazing package you provide as OS!

As we tried to integrate the search into a react-router-driven application some uncontrollable effects occurred. We are not sure if it's missing documentation, a but or a lack of knowledge of us.

The effect: 

1. The application has an endpoint http://localhost:3000/#/ which only shows the search field.
![image](https://user-images.githubusercontent.com/2667575/73179764-5934b800-4114-11ea-98a1-a231ab7aab01.png)

2. This search field works. When entering a keyword, the application forwards to http://localhost:3000/#/search/q/<searchterm>, in our example: http://localhost:3000/#/search/q/test.
![image](https://user-images.githubusercontent.com/2667575/73179896-91d49180-4114-11ea-9957-f6957a542324.png)

3. When we select a facet option now (here "aktuell") the search address becomes weird: the original url is replaced by a long variable list.
![image](https://user-images.githubusercontent.com/2667575/73180223-2d660200-4115-11ea-9ea3-325ad18ab8b2.png)

Now two questions arise: 

1. is it possible to change from ?q to a react router params as described [in this example](https://reacttraining.com/react-router/web/example/url-params).
2. is it possible to setup the entire search to not completely replace the react-router url, but add the varables to the url string

EDIT: Question 1 is not really an issue, just a general question, whereas question 2 is more an issue, we need to resolve, as the URL ends up falsified.

**Comment by scheiblr** [comment]
I investigated question 2 a bit further and changed the application to use ReactRouter with ?q instead of router params. Unfortunately, search-ui components seem not to get the GET variable (nothing in the search field). I have no clue how to change that behaivor.

![image](https://user-images.githubusercontent.com/2667575/73254094-0f081100-41be-11ea-8921-6d969989d7c5.png)

**Comment by scheiblr** [comment]
For now we solved it by calling 
```
window.location.href = `/?q=${encodeURIComponent(value)}`
```

instead of using the router's push function

```
props.history.push(`/search?q=${encodeURIComponent(value)}`)
```

**Comment by JasonStoltz** [comment]
I'm starting to look at this now.

First thing to point out, you can turn off this url syncing completely using the "trackUrlState" configuration.

Second thing, this will be much easier to talk about if we can get a codesandbox.io set up to replicate the problem. Are you able to do that quickly? If not, I can see if I can get one set up.

**Comment by JasonStoltz** [comment]
> is it possible to change from ?q to a react router params as described in this example.

Here's a bit of an example of what you'd need to do: https://codesandbox.io/s/react-router-with-search-ui-rsgxn

You would have to turn off Search UI's url tracking with `trackUrlState: false`.

You would read in the URL param using React Router, and convert it to `initialState` in Search UI.

This will work for you. The downside is that you will throw away all of the url state management that Search UI does out of the box.

**Comment by JasonStoltz** [comment]
It looks like a big part of your struggle is that our url management is throwing away the hash parameter, so HashRouter won't work with Search UI.

My main suggestion would be to use React Router to route to a `/search` page where Search UI is mounted. Then, simply let Search UI handle the the url management. Don't try to use `/q/{term}`, just use `?q={term}`.

**Comment by JasonStoltz** [comment]
The only concerning thing I see here is that you couldn't use `props.history.push(`/?q=${encodeURIComponent(value)}`)`. Why did you have to change from that to `window.location.href`?

**Comment by scheiblr** [comment]
That is a good question ;) It didn't overtook the `?q` into the search field and ignored it. When using it with `window.location.href` it worked. I assume some React internals to prevent some reloading which is required by internal management of search-ui? I had the impression the entire page completely reloads when using `window.location.href`.

**Comment by JasonStoltz** [comment]
@scheiblr I updated this example: https://codesandbox.io/s/react-router-with-search-ui-rsgxn.

There is a link you can click which uses `history.push`, which seems to work just fine.

Not sure what the differences is between what I'm doing here and what you are doing.

![latest](https://user-images.githubusercontent.com/1427475/73273480-07db0600-41b2-11ea-9023-7dbd6b99b0db.gif)

**Comment by JasonStoltz** [comment]
However, now that we're talking about it. I think there is potentially an issue with using `history.push` from within the same page that already has Search UI loaded.

Meaning, if you're on `/search` which mounts Search UI, and you manually do a `history.push('/search?q=canyon'), I do believe that Search UI currently does not detect this. This is why typically, when you're within a Search UI driven page. Typically we use the `setSearchTerm` action when you're on a Search UI page though. That issue is captured here: https://github.com/elastic/search-ui/issues/269.

**Comment by JasonStoltz** [comment]
I think the issue you were experience was simply that React Router will not reload / remount a route navigation to the current route, even if the query string parameters have changed. The only work-around I could suggest for something like that is to use the query string parameter as a `key` on the Route to force a remount. Example here: https://rsgxn.csb.app/search?q=although&size=n_20_n.

**Comment by JasonStoltz** [comment]
I'm going to close this issue, hopefully you have enough information to work through your issue. Thanks for reporting this.

**Comment by scheiblr** [comment]
Thank you very much for your quick help!
