### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by philwilliammee** [elastic/search-ui#463]
in development build I get the warning. I haven't tracked down exactly where its coming from it might be from my webpack compiler.
`componentWillReceiveProps has been renamed, and is not recommended for use.`
```log
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
```

**Comment by JasonStoltz** [comment]
Interesting, it must be from a dependency, I don't believe we use that anywhere.

**Comment by philwilliammee** [comment]
did a little tracking the warning is coming from react-select
The warning message also says:
`Please update the following components: Select`

```bash
$ npm ls react-select
mix-starter@1.0.0 c:\Users\psw58\Desktop\mySites\it_cornell\it-cornell\web\modules\custom\cwd_swiftype_search\src\app
`-- @elastic/react-search-ui-views@1.3.2
  `-- react-select@2.4.4 
```

It is referenced in multiple issues. https://github.com/JedWatson/react-select/issues/3720 and https://github.com/JedWatson/react-select/issues/3745 

It looks like the latest release 3.0.8 does not have a fix for this open issue.
