### ISSUE TITLE
Add defaultQuery to config in SearchProvider

### ISSUE THREAD

**Issue by DickyKwok** [elastic/search-ui#465]
I found it difficult when I want to query by some array of document IDs in default query.
I can now query by adding 
```
initialState: {
    searchTerm:
      "doc-5e3a9bb6a1f322f8d040573c OR doc-5e3a9bb4a1f3222dbe40547e OR doc-5e3a9bb2a1f322bd364052bf OR doc-5e3a9bb4a1f3222dbe405453 OR doc-5e3a9bb7a1f3225fa14057ef"
  },
```
in config 
However, there would be an error msg saying that 

> An unexpected error occurred: [400] Query is too long (maximum is 128 characters)

Are there any other way to query some documents by ID in default?

**Comment by JasonStoltz** [comment]
Yep, you can apply a filter on the ID field.
