### ISSUE TITLE
Facet filtering is not working when a global filter is applied inside `searchQuery`

### ISSUE THREAD

**Issue by Rynoh** [elastic/search-ui#470]
Facet filtering (on fields y, z) is not working when a global filter (field x) is applied inside `searchQuery`

**How to recreate**
* Create the UI code by using 'Reference UI' from your app search engine
* Inside `src/App.js` add a global filter
```js
const config = {
  searchQuery: {
    facets: buildFacetConfigFromConfig(),
    ...buildSearchOptionsFromConfig(),
    filters: [
      { field: "type", values: ["test_value"], type: "any" }
    ]
  },
  autocompleteQuery: buildAutocompleteQueryConfig(),
  apiConnector: connector,
  alwaysSearchOnInitialLoad: true
};
```
* Have some facets configured(Make sure the facets do not include `type` as a field)
* Since `alwaysSearchOnInitialLoad` is true your search will start as soon as page loads
* Click on any facet to see that results are not filtered

**Comment by JasonStoltz** [comment]
@Rynoh A fix for this is available in `1.4.0-rc.0`. If you get a chance to test it out, let me know how it works out for you.

**Comment by Rynoh** [comment]
@JasonStoltz my free trail expired so will not be able to test it.

**Comment by JasonStoltz** [comment]
@Rynoh No problem, thank you for reporting this issue.

**Comment by mdparthi** [comment]
@JasonStoltz  @Rynoh I am able to verify this issue and it works fine for me in my local. Actually I faced the same issue and gone through the community and found the ticket  https://gitter.im/elastic-search-ui/ .

**Comment by fahmimrabti10** [comment]
@JasonStoltz hello, when using the beforeSearchCall method to update existing filters. Facets  not working

**Comment by joemcelroy** [comment]
hi @fahmimrabti10, could you please share with me how you are using `beforeSearchCall` to update the existing filters please? I will try and replicate it on my end and see if I can fix a bug.

**Comment by fahmimrabti10** [comment]
hello @joemcelroy, this is  how i use  beforesearchcall:

'''const connector = new AppSearchAPIConnector({
  searchKey,
  engineName,
  hostIdentifier,
  endpointBase,
  beforeSearchCall: async (existingSearchOptions, next) => {
    
    const results = await next({
      ...existingSearchOptions,
    "filters": {
        "all": [
            {
                "any": [
                    {
                        "sector": treepath
                    },
                    {
                        "general_admin": treepath
                    },
                    {
                        "territory_admin": treepath
                    },
                    {
                        "sub_region_admin": treepath
                    },
                    {
                        "security_unit": treepath
                    }
                ]
            }
        ]
    } 
 });

    return results;
  }


});'''

**Comment by fahmimrabti10** [comment]
hi @joemcelroy this is how i use beforeSearchCall : 
```
const connector = new AppSearchAPIConnector({
  searchKey,
  engineName,
  hostIdentifier,
  endpointBase,
  beforeSearchCall: async (existingSearchOptions, next) => {
    
    const results = await next({
      ...existingSearchOptions,
    "filters": {
        "all": [
            {
                "any": [
                    {
                        "sector": treepath
                    },
                    {
                        "general_admin": treepath
                    },
                    {
                        "territory_admin": treepath
                    },
                    {
                        "sub_region_admin": treepath
                    },
                    {
                        "security_unit": treepath
                    }
                ]
            }
        ]
    } 
 });

    return results;
  }


});
```

**Comment by joemcelroy** [comment]
hey @fahmimrabti10 - could you create a new issue for this? Also specifying the version you're using of search-ui and try the latest version `v1.11.2` to see if it fixes anything. I did have a quick look at the unit tests and *should* work https://github.com/elastic/search-ui/blob/master/packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.ts#L405-L442

**Comment by fahmimrabti10** [comment]
hey @joemcelroy i tried the last verion of search-ui and i got the same problem 
<img width="586" alt="Capture" src="https://user-images.githubusercontent.com/36500608/165641730-b8a55a72-b222-4682-ac6e-8613f3193578.PNG">

**Comment by joemcelroy** [comment]
so v1.4.1 doesn't work, neither has v1.11.2 ? Could you make sure you are using v1.4.1 and not the latest? Print out `npm version`. Im curious tho - if your package version hasn't changed, what else changed to cause this issue?
