### ISSUE TITLE
Facets return problem using range filter

### ISSUE THREAD

**Issue by dioginis** [elastic/search-ui#474]
I'm trying to use the range filter to get a variable (which receives two values: 0 or 1), and I want to filter every element that has each of them as a value. It's showing the right number of results for each of them, but it's not filtering it. Nothing happens when I click on 0 or 1.  Does anyone know how can I fix it?

`is_venda: {
      //   range: {
      //     field: "is_venda",
      //     ranges: [{ from: 0, key: "TODOS" }, { from: 1, key: "APENAS VENDIDOS" }]
      //   }
      // }`

`export default function buildRequestFilter(filters) {
  if (!filters) return;

  filters = filters.reduce((acc, filter) => {
    if (
      [
        "cidades_nome",
        "is_package",
        "is_paid",
        "ops_status",
        "is_venda",
        "consultor"
      ].includes(filter.field)
    ) {
      return [...acc, getTermFilter(filter)];
    }
    if (["is_venda"].includes(filter.field)) {
      return [...acc, getRangeFilter(filter)];
    }
    return acc;
  }, []);`

**Comment by JasonStoltz** [comment]
I don't understand what the `buildRequestFilter` function is for.

Are you using App Search?

In Search UI, to use a Facet Filter, you do it like this:

https://github.com/elastic/search-ui/blob/master/ADVANCED.md#facet

```
<SearchProvider config={{
  ...otherConfig,
  searchQuery: {
    facets: {
     is_venda: { type: "value" }
    }
  }
}}>
  {() => (
    <Facet field="states" label="States" view={SingleSelectFacet} />
  )}
</SearchProvider>
```

**Comment by JasonStoltz** [comment]
Or if you want to use those range buckets, it could be something like this:

```
<SearchProvider config={{
  ...otherConfig,
  searchQuery: {
    facets:     {
      is_venda: [
        {
          type: "range",
          ranges: [
            { from: 0, to: 0, name: "TODOS" },
            { from: 1, to: 1, name: "APENAS VENDIDOS" }
          ]
        }
      ]
    }
  }
}}>
  {() => (
    <Facet field="is_venda" label="Is Venda" view={SingleSelectFacet} />
  )}
</SearchProvider>

```
