### ISSUE TITLE
Some fields are cut before ")"

### ISSUE THREAD

**Issue by Kilowogg** [elastic/search-ui#475]
Node : v10.19.0
NPM : 6.14.4

Hello,
In Search UI, some fields are cut before ")".
Example : field1 with value ["XXXXX (X/X)", "XXXXX (X/X)", "XXXXX (X/X)"]
This shows well in App Search administration but is cut after first ")" in Search UI.
After a search, it fully shows the field, with highlight, but still cut results from other matchs...
This is the code I'm using.
```
const configurationOptions = {
    ...
    searchQuery: {
...
        result_fields: {
...
            field1: {snippet: {size: 999, fallback: true}}
        },
        facets: {
...
            field1: { type: "value", size: 100 },
...
        }
    }
};
```
To solve this, I switched to
```
const configurationOptions = {
    ...
    searchQuery: {
...
        result_fields: {
...
            field1: {raw:{}}
        },
        facets: {
...
            field1: { type: "value", size: 100 },
...
        }
    }
};
```
But now, I've lost snipet highlight. But the field fully shows.

**Comment by JasonStoltz** [comment]
Ah, I see what you are saying.

Snippet highlighting will only ever work on 1 value. This is true for all of App Search.

So if you have values ["Tigers (1/3)", "Tigers (2/3)", "Tigers (3/3)"], and a search for "Tigers"...

You will only ever get 1 value that is highlighted. So either "<em>Tigers</em> (1/3)", "<em>Tigers</em> (2/3)", or "<em>Tigers</em> (3/3)". You' never get the entire thing with highlights.

I do believe it's that way in the Admin dashboard as well.

**Comment by Kilowogg** [comment]
Yes, we only see one value. :/
The only difference is that it's not cut.

**Comment by JasonStoltz** [comment]
Oh, OK. So you mean they show up like this? "XXXXX (X/X"?

**Comment by JasonStoltz** [comment]
Still important

**Comment by flyinliamryan** [comment]
Using Search UI with Swiftype site search and I'm having the same issue with hyphens and title and body fields not displaying. An example would be if someone typed "COVID-19".

Changing the title field to raw instead of snippet resolves it but lose highlighting. The body field is too large so I have let that as a snippet.

The national-parks demo doesn't seem to have this problem.

react-search-ui: 1.3.2

**Comment by JasonStoltz** [comment]
Making a note of this here, we use this snippet of code internally. We should apply this as a fix in search-ui:

```
/**
 * Due to a bug in ES Snippeting, certain results that end in characters
 * like a closing bracket (']') will be returned with the closing bracket
 * missing.
 *
 * Note that this ONLY happens on snippet fallbacks, if there is
 * a highlight in the snippet, this does not occur.
 *
 * This component simply detects the missing bracket and adds one to
 * the end of the  provided string. You should ONLY use this in
 * cases where you expect a result to missing a bracket in a
 * field:
 *
 * ex: {
 *   title: {
 *     snippet: "Elasticsearch.Net and NEST: the .NET clients [master"
 *   }
 * }
 *
 */
export default function SnippetFix({ snippet }) {
  if (!snippet) return "";

  const regex = /\[[^\s\]]+$/;
  if (snippet.match(regex)) {
    return snippet + "]";
  }

  return snippet;
}

```

**Comment by JasonStoltz** [comment]
I actually don't think a fix for this in search-ui is a good solution. I'm going to see if I can track down an ES issue related to this and see if we can prioritize a fix that way.

**Comment by JasonStoltz** [comment]
@Kilowogg What version of App Search are you using? Are you using the cloud version on app.swiftype.com, a version you installed, or a version located on cloud.elastic.co?

**Comment by JasonStoltz** [comment]
I've confirmed this issue on all versions of App Search. I opened an issue with the App Search team. I am closing this issue for now as we will not address it directly in Search UI.
