### ISSUE TITLE
Configurable endpoint for self-hosted Site/App Search?

### ISSUE THREAD

**Issue by omegahm** [elastic/search-ui#48]
Should this URI (https://github.com/elastic/search-ui/blob/master/packages/search-ui-site-search-connector/src/SiteSearchAPIConnector.js#L17) be configurable so that you could point it to a self-hosted or development version of the Site/App Search API?

**Comment by JasonStoltz** [comment]
Yes, absolutely, thanks for entering an issue.

**Comment by JasonStoltz** [comment]
This is supported in the App Search connector via the "endpointBase" parameter. This is not currently supported in the Site Search connector.
