### ISSUE TITLE
Search index selection

### ISSUE THREAD

**Issue by brilhana** [elastic/search-ui#483]
I have an Elasticsearch cluster running with multiple indexes and would like to be able to select a specific index before searching my documents. Is there any way to do so using SearchProvider or SearchBox?

**Comment by JasonStoltz** [comment]
You can build that input component and store that state separate from SearchProvider and SearchBox. You'd then reference that state whenever you build your query in `onSearch`: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#connectors-and-handlers
