### ISSUE TITLE
[Question] - Swiftype App Search vs Elastic App Search

### ISSUE THREAD

**Issue by celloudiallo** [elastic/search-ui#484]
Hi,

this might not be the best place to ask this but am curious What's the difference between swiftype app search and elastic app search...I know swiftype is an elastic company.

are they both the same service? if yes, how do you decide which one to sign-up for?

**Comment by JasonStoltz** [comment]
Sorry for the product confusion. There is only 1 product, and that is [Elastic App Search](https://www.elastic.co/app-search/), which was formerly known as Swiftype App Search.

You can download Elastic App Search and run it yourself, or you can spin up an instance on Elastic Cloud.

**Comment by celloudiallo** [comment]
thanks for the clarification Jason.
