### ISSUE TITLE
Facet within a facet

### ISSUE THREAD

**Issue by joerav** [elastic/search-ui#486]
We have a field that we want to use that filter all results by that type. When use as a facet it works great but we want this to work like an accordion that contains child facets underneath. Do you have example where in react you can use one facet value and show related facets underneath?

**Comment by joerav** [comment]
Im not sure how to create the url by hand.

**Comment by JasonStoltz** [comment]
This ticket includes a description of the approach you would take for this, and a working example of this using App Search, but not Search UI. https://github.com/elastic/search-ui/issues/285

There will be a bit of work figuring out how to make this work with Search UI, but it should be possible.

**Comment by JasonStoltz** [comment]
Going to close this as I haven't heard back, and the work is captured in #285.
