### ISSUE TITLE
Facet.js as a functional component

### ISSUE THREAD

**Issue by joerav** [elastic/search-ui#488]
I am using https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/src/containers/Facet.js and need a version that is a functional component. Without it being a functional component I can’t use React Hooks to keep track of the state when I click the facet and have it update a sibling component. Do you have a version already this way? Basically upon click of the facet, the sort options need to update.

**Comment by JasonStoltz** [comment]
This appears to be related to this issue: https://github.com/elastic/search-ui/issues/276. Definitely something we'd like to fix.
