### ISSUE TITLE
conditionalFacets Error 

### ISSUE THREAD

**Issue by gallbrook** [elastic/search-ui#489]
When attempting to use conditional facets as per documentation on https://github.com/elastic/search-ui/blob/master/ADVANCED.md#advanced-configuration. 
 I am getting the following error:
**Options contains invalid key: conditionalFacets**
```
searchQuery: {
    facets: {
      contact_type: { type: "value", size: 30 },
      name:{ type:"value", size:100},
     park:{type:"value", size:10}
    },
    disjunctiveFacets: ['contact_type'],
    disjunctiveFacetsAnalyticsTags:['junk'],
    conditionalFacets:{ name: filters => isParkSelected() }
  },
```
Am I missing something?

**Comment by JasonStoltz** [comment]
Hey @gallbrook, this unfortunately appears to be a bug.
