### ISSUE TITLE
BooleanFacet checked value does not update when removeFilter is used

### ISSUE THREAD

**Issue by jasontk19** [elastic/search-ui#490]
If using the `addFilter` or `removeFilter` functions modify a filter value for a facet that is using a BooleanFacet view, the checkbox is not updated to reflect the current value of the filter since the input is not setting a `checked` attribute value on the input like is done in the MultiCheckbox view component.  

For example:
![booleanFacet](https://user-images.githubusercontent.com/1480000/81227236-178c9680-8fba-11ea-8050-469e57411634.gif)

This can easily be fixed by adding `checked={isSelected}` to this input:
![booleanFacetFixed](https://user-images.githubusercontent.com/1480000/81227330-4145bd80-8fba-11ea-8a4e-4549d43b0341.gif)

Happy to open a PR for this if that's helpful.

**Comment by JasonStoltz** [comment]
Fixed by https://github.com/elastic/search-ui/pull/491
