### ISSUE TITLE
AWS ElasticSearch

### ISSUE THREAD

**Issue by Rafcin** [elastic/search-ui#492]
AWS Elasticsearch leaves more to wonder than to work with, and I can't seem to solve how to setup a connector with AWSE. 
My current setup with is:
```
    const connector = new AppSearchAPIConnector({
      searchKey: "apiKey",
      engineName: "index*",
      endpointBase: "EndpointURL"
    });
```
and I either have a connection error or a CORS policy issue. However when I try the same thing with appbaseio the connector connects fine without CORS issues.

**Comment by JasonStoltz** [comment]
Hey @Rafcin, you are using the `AppSearchAPIConnector` which is specifically for Elastic App Search. 

We don't have a connector for Elasticsearch, but we do provide some instructions for using search-ui with Elasticsearch here: https://github.com/elastic/search-ui#how-do-i-use-this-with-elasticsearch.
