### ISSUE TITLE
The demo site doesn't seem to work

### ISSUE THREAD

**Issue by DotNetRockStar** [elastic/search-ui#495]
Hi there.  I am interested in using the search UI but it seems like the demo site doesn't work right.

https://search-ui-stable.netlify.app/?size=n_20_n

I am using the latest Chrome.  Is this just an issue with the demo site or a bug with the latest build perhaps?  

Thanks in advance

**Comment by JasonStoltz** [comment]
Oh that's weird. Can you try again? It is working for me.

**Comment by JasonStoltz** [comment]
Couldn't reproduce, going to close this unless someone else can reproduce it.
