### ISSUE TITLE
An unexpected error occurred: Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by xiaofengleo** [elastic/search-ui#497]
I follow the  README.md to set up an Elasticsearch instance and have the file national-es-bulk-index.json indexed.

I think I build the index correctly. 
I run several queries, I get correct results. 

For example, 
curl -X GET "localhost:9200/national-parks/_search?q=teton"  -u elastic:Y0QOpHyZXcCQ0amo7uon

The responding is:
{"took":10,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":2,"relation":"eq"},"max_score":5.8680367,"hits":[{"_index":"national-parks","_type":"_doc","_id":"ZFSgV3IBAqaHJ50nMkrM","_score":5.8680367,"_source":{"description":"Grand Teton is the tallest mountain in the Teton Range. The park's historic Jackson Hole and reflective piedmont lakes teem with endemic wildlife, with a backdrop of craggy mountains that rise abruptly from the sage-covered valley.","nps_link":"https://www.nps.gov/grte/index.htm","states":["Wyoming"],"title":"Grand Teton","id":"park_grand-teton","visitors":3270076,"world_heritage_site":false,"location":"43.73,-110.8","acres":310043.96,"square_km":1254.7,"date_established":"1929-02-26T06:00:00Z"}},{"_index":"national-parks","_type":"_doc","_id":"o1TDV3IBAqaHJ50ni0o9","_score":5.8680367,"_source":{"description":"Grand Teton is the tallest mountain in the Teton Range. The park's historic Jackson Hole and reflective piedmont lakes teem with endemic wildlife, with a backdrop of craggy mountains that rise abruptly from the sage-covered valley.","nps_link":"https://www.nps.gov/grte/index.htm","states":["Wyoming"],"title":"Grand Teton","id":"park_grand-teton","visitors":3270076,"world_heritage_site":false,"location":"43.73,-110.8","acres":310043.96,"square_km":1254.7,"date_established":"1929-02-26T06:00:00Z"}}]}}

Then I run:
ELASTICSEARCH_HOST=https://elastic:Y0QOpHyZXcCQ0amo7uon@127.0.0.1:9200/national-parks npm start

the browse jumps to http://localhost:3000/?size=n_20_n, and display only a search box, without the facet search and the list.
I tried to type in one keyword in the search box, then an error occurred, says
"An unexpected error occurred: Unexpected token A in JSON at position 0".
The screenshots are attached below for our reference.

I googled with this error, and found some discussions regarding this topic, but not in the setting like mine.

I appreciate if anybody can provide a clue.

Thank you.
Best regards,
Xiaofeng Liao

<img width="1440" alt="Screen Shot 2020-05-27 at 10 57 05 PM" src="https://user-images.githubusercontent.com/2759916/83071448-6e433880-a06d-11ea-9d55-2527a3fb67fb.png">
<img width="1440" alt="Screen Shot 2020-05-27 at 10 58 44 PM" src="https://user-images.githubusercontent.com/2759916/83071588-a9de0280-a06d-11ea-8aa2-f63bd5e6eae1.png">

**Comment by bigrig2212** [comment]
I'm getting same error with the netlify function... pushed up to netlify and getting error there too...

**Comment by y0zg** [comment]
Hi @bigrig2212 @JasonStoltz @xiaofengleo ,
Did you have a chance to figure out what is the root cause? 
Just received the same error

Thank you!

**Comment by JasonStoltz** [comment]
Any time a bad response is returned, you could end up seeing this message. Check the server logs to see if there is a more specific error.

**Comment by ZakKa89** [comment]
I've had this issue when something in my config wasn't right. For example, I can't search on fields of type keyword:
I'm about to open a new issue for this

`error - TypeError: Cannot read properties of undefined (reading 'total')
    at getSummaryFromResponse (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/transformers/index.js:30:41)
    at ElasticSearchResponseTransformer.transformResponse (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/transformers/index.js:63:25)
    at SearchkitRequest.<anonymous> (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/index.js:126:37)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/index.js:15:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/api/search'
}`
