### ISSUE TITLE
Use this library as native JS or in knockout?

### ISSUE THREAD

**Issue by nntoan** [elastic/search-ui#502]
Hi there,

Just newbie to this, as per title I'm wondering if it's possible to use this as a standalone library for native JS?

From the README.md

> Flexible front-end - Not just for React. Use with any JavaScript library, even vanilla JavaScript.
Flexible back-end - Not just for Elastic App Search. Use with any backend.

But I can't find any information regards this one in the documentations

Cheers

**Comment by JasonStoltz** [comment]
Hey, yes, the core of search-ui is packaged with as plain old JavaScript: https://github.com/elastic/search-ui#is-search-ui-only-for-react.
