### ISSUE TITLE
No results display seems to be buggy

### ISSUE THREAD

**Issue by dsacramone** [elastic/search-ui#508]
So, I am having a bit of an issue and it also exhibits the problem in the codesandbox:
https://codesandbox.io/s/national-parks-example-kdyms?fontsize=14

Type in the following ("runner salad hardknocks is real cold") real slow, one character per second. You will a result set come up, then a no results, then "no results" will disappear even though it is obvious there are no matches, then a result set, then it will go away and I would expect a "no results" display but it doesn't show up again.

**Issues**: "No results" Display is transient and should show on ALL no match inputs.
**Expectation**: For each character if there is "no result" it should show display. Backspacing should behave the same.

**Comment by JasonStoltz** [comment]
I don't think I understand.

Is this in the autocomplete dropdown?

Do you actually see a "No Results" message? I don't ever see a "No Reuslts" message.

I type the following, one character at a time, and watch the autocomplete dropdown.

"runner salad hardk" - The results change with each character I type.

When I enter one more character, "n" to make "runner salad hardkn", the autocomplete dropdown goes away entirely.

It stays that way until I get to "runner salad hardknocks i", and then reappears with results.

Is this the behavior you are talking about?
