### ISSUE TITLE
Control of query parameters

### ISSUE THREAD

**Issue by hammund0** [elastic/search-ui#509]
Hello,

I'm a big fan if this react library, makes adding search very easy.

I have read through the readme's on this repository but could not find the answer I was looking for.

I have a couple of questions and would really appreciate an answer :)

1. Is it possible to not show the size parameter on search `&size=n_20_n` etc
2. I have to add a custom query string parameter on the search results page, this gets removed by this plugin and would like it to stay. How can I make this plugin not strip out custom query parameters?

Thank you

**Comment by JasonStoltz** [comment]
These are two great suggestions. I would like to implement both of these, but for the time being, neither is possible.

**Comment by BackToTheCode** [comment]
+1
