### ISSUE TITLE
Support for "or" filters

### ISSUE THREAD

**Issue by DickyKwok** [elastic/search-ui#510]
I would like to search for results whose ID is 123 OR within specific distance, but now I can only get results when I search with ID 123 AND within specific distance. Can we have the OR filters feature in the future?

```
const config = {
  trackUrlState: false,
  initialState: {
    filters: [
      {
        field: "id",
        values: ["123"],
        type: "any",
      },
      {
        field: "location",
        values: [{
          center: "22.502022, 114.078639",
          unit: "km",
          to: 200,
          from: 0,
        }],
        type: "any",
      },
    ],
  },
  apiConnector: connector,
};
```

**Comment by kumail-habib** [comment]
I need this functionality too

**Comment by carlosslalom** [comment]
I ran into the same use case. Any luck?

**Comment by JasonStoltz** [comment]
Thank you all for sharing this concern. I'd considered this before but then incorrectly decided there wouldn't be a need for it. I see now that was an incorrect assumption.

I believe there was a PR that was submitted previously that we ended up closing. Let me see what I can dig up.

**Comment by JasonStoltz** [comment]
Ah, here is the issue I was thinking of: https://github.com/elastic/search-ui/issues/411

**Comment by JasonStoltz** [comment]
I'm going to close this in favor of https://github.com/elastic/search-ui/issues/411, let's continue the conversation there.
