### ISSUE TITLE
'Layout' is not exported from @elastic/react-search-ui-views

### ISSUE THREAD

**Issue by gabeamaleoni** [elastic/search-ui#513]
Hi there, 

I am attempting to use this on a work project with React/TypeScrip. When I attempt to import:
`import { Layout } from "@elastic/react-search-ui-views";`

I get this error: `Module '"@elastic/react-search-ui-views"' has no exported member 'Layout'.ts(2305)`

Any ideas?

![image](https://user-images.githubusercontent.com/8764019/93540760-859e7e00-f909-11ea-942e-98402123b10a.png)

**Comment by zumwalt** [comment]
Thanks for raising this issue, @gabeamaleoni. Are you attempting to implement Search UI in a Typescript project? I haven't explored the problem you're dealing with in depth, but seeing `.ts` in the error response leads me to believe that you may be running up against Search UI's lack of Typescript definitions.
