### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#518]
Release candidate: 1.5.0-rc.0

The only thing included in this release is https://github.com/elastic/search-ui/pull/517

**Comment by JasonStoltz** [comment]
@davidsauntson This release is mainly for you. Do you mind trying out the RC in your project to make sure the rawResponse changes work as you expect?

**Comment by davidsauntson** [comment]
@JasonStoltz LGTM - thanks for this! 🎉

**Comment by JasonStoltz** [comment]
https://github.com/elastic/search-ui/releases/tag/v1.5.0
