### ISSUE TITLE
Smart URLs Overwriting Current Path

### ISSUE THREAD

**Issue by MaverickEdberg** [elastic/search-ui#519]
There should be a way to prevent SmartURLs from overwriting the current path. Our site has a landing page located at root `/`. We then redirect the user to a search page to display the results, e.g.: `/search?q=whatever`. When the results load, Smart URLs rewrites the current url to `/?q=whatever`. This breaks functionality for the user to navigate a specific set of search results, since `/?q=whatever` would take them back to the landing page. If there is a configuration option for this I apologize I could not find anything.

**Comment by JasonStoltz** [comment]
Can you simply disable the trackUrlState option https://github.com/elastic/search-ui/blob/master/ADVANCED.md#advanced-configuration ?

**Comment by MaverickEdberg** [comment]
Doing that would prevent the facets' values from being saved in the URL though, right? I definitely want the trackUrlState option's behavior, just without it resetting the user's current path to root `/` on change. Thoughts? Thanks for the help by the way.

**Comment by JasonStoltz** [comment]
OK, I see what you are saying. Search UI should not be changing any pathing. So it *shouldn't* be rewriting `/search` to `/`. Search UI will only attempt to adjust the query string, it doesn't touch the path. I am not sure why you are experiencing this.

**Comment by MaverickEdberg** [comment]
I believe it reverts back to the path that was active when it was first initialized, to be more specific (at least in my scenario, maybe I messed something up). I will keep looking at post back. Thanks again.

**Comment by MaverickEdberg** [comment]
I am 99% sure Smart URLs are reverting the url location back to what it was when initialized. Whether you want to look into this or not is up to you, I will be working around this by manually tracking url state. Feel free to close if you want. Thanks again!

**Comment by JasonStoltz** [comment]
Hey @MaverickEdberg. It could certainly be a bug with our url tracking, or, potentially some conflict with your particular routing set up. I can usually help work through these things with folks, but I'd need to be able to reproduce it. 

If you could put a code sandbox together that reproduces the issue, or even just give me some indication of how your routing works so that I can try to reproduce, that would help.

**Comment by JasonStoltz** [comment]
We're doing some work that could potentially fix whatever was wrong here: https://github.com/elastic/search-ui/issues/790
