### ISSUE TITLE
Support for autocomplete/suggestions under the search box

### ISSUE THREAD

**Issue by asjadathick** [elastic/search-ui#52]
Adding support for auto complete/suggestions into the search box component would be very handy and useful, especially with sitesearch/app search use cases

**Comment by JasonStoltz** [comment]
Definitely on the short term roadmap.

**Comment by JasonStoltz** [comment]
Implemented in Reference UI project, need to backport to this project: https://github.com/swiftype/app-search-reference-ui-react/pull/27
