### ISSUE TITLE
Problems with GUI migrating ES from V6 to V7

### ISSUE THREAD

**Issue by jenswitzel** [elastic/search-ui#522]
Hi out there

Our ES-Test Server is a V7 copy of an existing V6, and the index is rebuilt.
Lookup works in search-ui, offering a kind of title. But although i know, that types are deprecated, i cant find the part, where the resultlisting crashes. Any hints, what to do / add to the code or the npm-environment?

Kind regards
Jens

**Comment by JasonStoltz** [comment]
Hey @jenswitzel. I'd need quite a bit more information to help you solve this issue. Code references, steps to reproduce, error messages all help quite a bit.

**Comment by jenswitzel** [comment]
Hi @JasonStoltz 
thanks for answering so quickly. Well, it's a modified React-Code from this search-ui. We use a cgi/proxy to make authentification during query, and enrich the answer of ES. I think, the whole react-code is pretty to much to send. I can see, the answer of ES while logging/debuging inside the proxy; stuff to send to the react client. So GUI->Proxy->ES->Proxy works well ... it's just the answer, which can not be interpreted by the react code. Works against ES6.8.5, does not work with the answer of ES7.9.3.

ES Result is in log
[gui-proxy-es.log](https://github.com/elastic/search-ui/files/5511312/gui-proxy-es.log)

FireFox Console is here
[FireFox-Console.txt](https://github.com/elastic/search-ui/files/5511315/FireFox-Console.txt)

What else do you need?
Kind regards
Jens
:

**Comment by jenswitzel** [comment]
Found the BUG #-)

ES6 returns hits.total  => ES7 returns hits.total.value; 

Thanks
Jens
