### ISSUE TITLE
Is there a best practice how to display "Loading"-Wheel ?

### ISSUE THREAD

**Issue by jenswitzel** [elastic/search-ui#523]
Hi out there

Subject tells it: does anybody has an example? Loading state handling etc.?

Kind regards
Jens

**Comment by JasonStoltz** [comment]
Hey Jens, there are two pieces of relevant state that you can tie into to show a loader: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#application-state

`isLoading` and `wasSearched`.

So you could do something like:

```
<SearchProvider config={config}>
  <WithSearch>
    {({ isLoading }) => {
      if (isLoading) return <YourLoader />
    }}
  </WithSearch>
</SearchProvider>
```

**Comment by jenswitzel** [comment]
Works great! Thanks again :-)
