### ISSUE TITLE
Where do I find hostIdentifier and searchKey in Site Search?

### ISSUE THREAD

**Issue by peter-reonomy** [elastic/search-ui#524]
Where can I find my `hostIdentifier` and `searchKey` values? Tried looking in the Elastic (Swiftype) Site Search console but see only `API Key`, `Engine Slug` and `Engine Key`.

**Comment by JasonStoltz** [comment]
The Site Search Connector takes slightly different parameters: https://github.com/elastic/search-ui/tree/master/packages/search-ui-site-search-connector.
