### ISSUE TITLE
Support: are you supposed to be able to build it and run without npm?

### ISSUE THREAD

**Issue by hkirsman** [elastic/search-ui#526]
Would want to use it instead of https://www.searchkit.co/ but don't want to run any extra servers.

**Comment by JasonStoltz** [comment]
I'm not sure I understand your question. It is a React library, so you need to build a web app and run it somewhere, just like Search Kit.

**Comment by hkirsman** [comment]
So once you build it you don't need node server?

**Comment by JasonStoltz** [comment]
Once you've built a javascript based application, it just builds a javascript file, which you can include on any webpage. You do not need a node server for search-ui.

**Comment by hkirsman** [comment]
Thank you!
