### ISSUE TITLE
Facets with selected options disappear

### ISSUE THREAD

**Issue by Luiz-N** [elastic/search-ui#528]
Disjunctive or "sticky" facets/filters do not stick around as intended unless of type range.  

Here are steps to show this from [the example app](https://codesandbox.io/s/national-parks-example-kdyms?fontsize=14&file=/src/App.js).

1. Select "World Heritage site" option
2. Select any facet value of 0 (Distance of "nearby" for example)
3. All "value" facets (even one's configured as "disjunctive" such as "country" and ones with selected values such as "world heritage site") disappear when results come back.

All ranged facets marked as disjunctive stick around no matter what. I would expect the same to happen with value type facets. At a minimum shouldn't "value" type facets with selected values always stick around as well? Otherwise the user can't see what the filter state is anymore.

**Comment by JasonStoltz** [comment]
This is a good point @Luiz-N. I think it should behave the way you describe.
