### ISSUE TITLE
Results's key name to get the result ID is hardcoded

### ISSUE THREAD

**Issue by robertocarta** [elastic/search-ui#530]
Maybe I'm getting something wrong, but I noticed that the key to get the result id in Results is hardcoded to be result.id.raw - shouldn't this be configurable like title or url?

**Comment by JasonStoltz** [comment]
I don't think so. Why would you want to change that?

**Comment by robertocarta** [comment]
Because I'm not using elasticsearch as a backend and I have no reason to have results in the form of {...result, id: {raw: id}}

**Comment by JasonStoltz** [comment]
Got it. You have 2 options:

1. Simply format your results as they come in to have the `id.raw` field.
2. Create a custom view for results. There's a reasonable example and explanation on this [forum post](https://discuss.elastic.co/t/reference-ui-how-to-modify-whats-displayed-react-newbie/199471/2?u=jasonstoltz).
