### ISSUE TITLE
Way to realize "- Less" or "= All" expanding/reducing facet entries?

### ISSUE THREAD

**Issue by jenswitzel** [elastic/search-ui#532]
Hi out there

is there a way to build additional features like "+ More" at the end of the facets list? We need "- Less" and "= All" to expand/reduce the list.

Thanks for any hints
Jens

**Comment by JasonStoltz** [comment]
Ah, great ideas. We give you views out of the box, but they can all be swapped out for something custom. Read more here: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#component-views-and-html.
