### ISSUE TITLE
filtering results in a specific page

### ISSUE THREAD

**Issue by shadoo77** [elastic/search-ui#533]
Hallo every one,

I have a website built with elasticsearch ui app, and everything is okay till now but i'm now facing an issue :
I have mapped some data from my db an sync it to an engine in elastic app as **post-sections-engine**
there i have a property called post_section determines where the post belongs to (sport, weather, etc ... , and all posts)
In some page i need to render all posts but get there dublicted posts because all_posts includes all posts which existed also in sport posts and another sections, so the first 20 results contains e.g : 10 all_posts, 3 sport and 7 weather.
and maybe those 3 of the sport are dublicated,
What i want actually is when i navigate to a specific page just filter the results (without adding filter manually) and give me 20 results of all_posts (i do need the other sections for sport section and weather one).
Is there an easy way to do that in the elastic configurations or somewhere in the dashboard ?

Best regards
Shadi

**Comment by JasonStoltz** [comment]
Are you using Elastic App Search? Or Elasticsearch?

If you are using Elastic App Search, you probably want your data to be modeled like this:

```
[
  "id": 0,
  "title": "Some Sports Content",
  "post_section": ["sports", "fitness"]
],
[
  "id": 1,
  "title": "Apple Vs Android",
  "post_section": ["technology"]
],
[
  "id": 2,
  "title": "Is it called Soccer or Football?",
  "post_section": ["sports"]
]
```

So don't duplicate your documents, just add the appropriate "post_section" tags to the same document if it is duplicated in multiple places.

> What i want actually is when i navigate to a specific page just filter the results (without adding filter manually)

I don't know exactly what you mean by "without adding filter manually". In Search UI, if you are on a page and you want the results to always be filtered to "sports", then you could apply the filter like so:

```
<SearchProvider config={{
    searchQuery: {
      filters: [{ field: "post_section", values: ["sports"] }],
    }}>
</SearchProvider>
```

That way, in the context of that page, queries will always be filtered to just "sports", without a user needing to apply a filter manually.

**Comment by JasonStoltz** [comment]
https://github.com/elastic/search-ui/blob/master/ADVANCED.md#global-filters
