### ISSUE TITLE
fail to work with Next.js Client-side navigations ( next/router, next/link )

### ISSUE THREAD

**Issue by jason-den** [elastic/search-ui#534]
Hi. I'm using `search-ui` with my `Next.js` project. 
But I found that when I navigate away from the search page to another page using the `Client-side navigations`, I cannot go back by using the browser "back" button (I've only tried chrome.)

> It seems to be the only lib that support elastic-app-search. Is it correct?

How to replicate: 
1. Run this [demo repo]( https://github.com/jason-den/next-search-ui-demo)
2. visit search page `localhost:3001/search`
3. click `go home page` at the top of sidebar
4. when home page complete rendering, click your browser `back` button like this: 
![image](https://user-images.githubusercontent.com/16683831/104660622-0b490380-571b-11eb-94f0-31f7aa7f3f63.png)

Problematic result: The URL do change to `localhost:3001/search?......` but page remains in home page.
![image](https://user-images.githubusercontent.com/16683831/104660778-4c411800-571b-11eb-98cf-edd765743092.png)

I'm not sure this issue come from `search-ui`, not from Next.js. I guess this issue has something relate to `Smart URL` -- which I want to understand more but couldn't find much documents. 

> BTW I also tried `search-ui` with `react router`, they worked well with each other. 

Any hint?

**Comment by JasonStoltz** [comment]
Hi @jason-den. I ran your demo, I was able to reproduce.

Unfortunately, I don't have any hunches as to what's wrong.

Interesting to note though... when I set a breakpoint in search.jsx, it is never run. It's like the next router never successfully detects the route change.

When I remove Search UI, the issue is gone.

Something to do with query string in the URL and next? When search-ui initializes we rewrite `/search` to /search?size=n_20_n`. I don't know, just thinking out loud.

**Comment by CallumSlavin** [comment]
I have an identical issue on my own Next.js project. What I noticed was that when I ran 'console.log(history)', unlike on other pages, the history.state was undefined. Could this be related?

**Comment by CallumSlavin** [comment]
What I have also noticed is that this issue only seems to occur for me when using the Link component for page transitions.

**Comment by jason-den** [comment]
@CallumSlavin yep. if you replace all the related link with <a> tag you will probably be fine. But it doesn't work with " Next.js Client-side navigations"

**Comment by jason-den** [comment]
For personal project it's an acceptable work around. but for project that has lots on link on that page using <Link /> on same page, it's not acceptable.

**Comment by JasonStoltz** [comment]
Thanks again for raising this.

**Comment by ctestamarck** [comment]
We're running into this issue too. One thing I've noticed is that the history states pushed by NextJS have this parameter: `__N: true` 
Perhaps Next is ignoring any state changes which don't have that parameter, or others (asPath, url)? 

Maybe some kind of function/parameter could be added so that the state could be modified before search-ui pushes it?

**Comment by jason-den** [comment]
@Yurii-Adamenko Nice workaround.

**Comment by ctestamarck** [comment]
Thank you for posting that workaround @Yurii-Adamenko . Unfortunately I haven't been able to get it working when using the searchQuery property. If I comment out the searchQuery part then everything works as expected (except for a bug where the Searchbox will lose focus when a searchAsYouType search is applied): `<SearchProvider
        config={{
          apiConnector: connector,
          /*searchQuery: {
            disjunctiveFacets: ['make', 'model', 'year', 'collection_name', 'block_run_date'],
            facets: {
              year: { type: 'value', size: 250 },
              block_run_date: { type: 'value', size: 250 },
              make: { type: 'value', size: 250 },
              model: { type: 'value', size: 250 },
              collection_name: { type: 'value', size: 100 },
              reserve: { type: 'value' },
              is_charity: { type: 'value' },
            },
            filters: globalFilters,
          },*/
          initialState: {
            resultsPerPage: qstate.size ? qstate.size : 20,
            filters: qstate.filters ? qstate.filters : ifilters,
            sortField: qstate['sort-field'] ? qstate['sort-field'] : 'lot_number',
            sortDirection: qstate['sort-direction'] ? qstate['sort-direction'] : 'asc',
            current: qstate.current ? qstate.current : 1,
            searchTerm: qstate.q ? qstate.q : '',
          },
          trackUrlState: false,
          onSearch: (state, queryConfig, next) => {
      
            const searchString = stateToQueryString(state);
            router.replace(`${window.location.pathname}?${searchString}`, null, { shallow: true });
          
            return next(state, queryConfig);
          },
          alwaysSearchOnInitialLoad: false,
        }}
      >`

If I uncomment the searchQuery part, it causes an infinite loop where search keeps re-running.  The only place I'm using the NextJS router, useEffect, or useState is for setting the initial state here: 
`useEffect(() => {
    if (window.location.search) {
      setIState(parse(window.location.search.substring(1)));
    }
  }, []);` 

So I'm fairly confident there's nothing else interfering with the search state.  Has anyone been able to get it working with a searchQuery? Thanks in advance for any help.

**Comment by ctestamarck** [comment]
I've actually just found a workaround for the above searchQuery bug. If I apply those facets and filter in the beforeSearchCall function, it works correctly. 
```
beforeSearchCall: (existingSearchOptions, next) => {

        const newConfig = {
          ...searchConfig,
          ...existingSearchOptions,
          filters: {
            all: [{ all: [{ auction_id: eventId }] }, ...existingSearchOptions.filters.all],
          },
        };

        return next(newConfig);
      },
```

However, the SearchBox still loses focus whenever a search is applied.

**Comment by weynhamz** [comment]
We have a same issue. 

I believe the cause is that Search UI tempers and normalizes the URL to manage the state, for some interactions with the Search UI, the URL will be rewritten by Search UI after the initial loading, which messed up with the Next.js history management.

Possibly related to enhancement in this issue. https://github.com/elastic/search-ui/issues/790
