### ISSUE TITLE
nest filter  / combined filter

### ISSUE THREAD

**Issue by jason-den** [elastic/search-ui#535]
Hi. I'm curious how to implement [nesting filters](https://www.elastic.co/guide/en/app-search/current/filters.html#filters-nesting-filters) with search-ui?
The `addFilter` and `setFilter` both require a `name` to specify the field to filter on. I have no idea how to compose a combined filter.
Would you give an example?

**Comment by JasonStoltz** [comment]
I don't think `addFilter` will allow you to add a nested filter.

**Comment by jason-den** [comment]
So, does it mean `search-ui` doesn't support combined filtering? 
All I need is some combined `and` and `or` for two fields. 
For example:
We have items labeled as category [A, B, C] subcategory [A-1, A-2, B-1, B-2, ect]
I want to filter item that fit ( category==A `and` subcategory== A-1 ) `or` ( category==B )
Under current API, I got no idea how to achieve this.

**Comment by JasonStoltz** [comment]
Ok, I see what you are saying. And I unfortunately don't think this is something you'll be able to accomplish with Search UI.

**Comment by jason-den** [comment]
Thank you Stoltz for you time. 
Just one more question, is Search UI the only popular lib ( I mean, at least more than 100 starts ) that support Elastic App Search? ( not elastic stack )

**Comment by JasonStoltz** [comment]
Yes. To my knowledge, there are no others.
