### ISSUE TITLE
Using Search Provider With GatsbyJS Results in Empty Root Element

### ISSUE THREAD

**Issue by austinjherman** [elastic/search-ui#536]
## Intro
I'm not sure if my implementation is wrong, or if this is a bug, or if this is more of a feature request. This is also a Gatsby-specific implementation. I'll try to keep this short so let me know if any additional information is needed.

## The Problem
When I wrap my root element with the `SearchProvider` component, running `gatsby build` results in an empty root element.

## What I Think Should Happen
After wrapping my root element with the `SearchProvider` component and running `gatsby build`, the root element should have HTML inside of it.

## Reproduction Instructions / Implementation Detail
See the README of https://github.com/austinjherman/elastic-search-test. There are two branches. `master` is a vanilla `gatsby-starter-default` with an updated readme. `elastic-search-test` contains the implementation of the `SearchProvider` component.

## Stack Info
```bash
 System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
    Safari: 14.0.1
  npmPackages:
    "@elastic/react-search-ui": "^1.5.0",
    "@elastic/search-ui-site-search-connector": "^1.5.0",
    "gatsby": "^2.26.1",
    "gatsby-image": "^2.5.0",
    "gatsby-plugin-manifest": "^2.6.1",
    "gatsby-plugin-offline": "^3.4.0",
    "gatsby-plugin-react-helmet": "^3.4.0",
    "gatsby-plugin-sharp": "^2.8.0",
    "gatsby-source-filesystem": "^2.5.0",
    "gatsby-transformer-sharp": "^2.6.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0"
```

**Comment by austinjherman** [comment]
Alright so it turns out this is pretty easy to work around on the consumer side, so I'll close this. For the record, to make it work:

I can omit the `<SearchProvider>` component from `gatsby-ssr.js` so that it's only used in `gatsby-browser.js`. 

So in `gatsby-browser.js`:
```javascript
exports.wrapRootElement = ({ element }) => (
    <SearchProvider config={searchProviderConfig}>
        {element}
    </SearchProvider>
);
```

Then, when using the `<SearchBox>` component, I can make sure to only render when `window` is available (to avoid errors regarding the search driver). i.e.
```javascript
{typeof window !== "undefined" && (<SearchBox .../>)}
```

**Comment by samuel99** [comment]
@austinjherman  Thank you for actually coming back and provide an answer when you found it. Had the exact same error now!
