### ISSUE TITLE
Question - does search-ui support "boost" on searching?

### ISSUE THREAD

**Issue by jason-den** [elastic/search-ui#537]
Hi I'm doing my search [relevance tuning](https://www.elastic.co/guide/en/app-search/current/relevance-tuning-guide.html)
Just want to quickly check does search-ui support [boost on searching](https://www.elastic.co/guide/en/app-search/current/boosts.html)?

If it doesn't, does it somehow allow me to customise the param on requesting APP search API? 
I expect in near future I need to implement "Proximity Boost on geolocation" and "Value Boost".

**Comment by jason-den** [comment]
Only now I realised that there is a [forum](https://discuss.elastic.co/c/enterprise-search/app-search/72)

**Comment by JasonStoltz** [comment]
@jason-den It does support boosts via adding params to the app search API request.

**Comment by jason-den** [comment]
Hi Stolz. Thanks for replying. 
Would you elaborate more on how to "add params to the app search API request"? 
From the in the SearchProvider - context - actions", I can only see "addFilter" and "setSearchTerm" that can influence the searching. I've no idea how to customise the params.

**Comment by JasonStoltz** [comment]
Yep. [here](https://github.com/elastic/search-ui/blob/master/ADVANCED.md#advanced-configuration) is the section in the docs that discusses this.

**Comment by jason-den** [comment]
Hmmm. I searched `boost` with the whole page and there is nothing found.
Do you mean I can add `boost` param as an object into the `searchQuery` just like `facets `? 
Or I shall add it into `configurationOptions` as the same level with `searchQuery`?

**Comment by JasonStoltz** [comment]
Yes. Exactly, you can modify the searchQuery to add a boost.

**Comment by jason-den** [comment]
Thanks. I will try.
