### ISSUE TITLE
Using SearchUI with “pure“ ElasticSearch instance?

### ISSUE THREAD

**Issue by julianklotz** [elastic/search-ui#538]
Hey there, 

I am trying to figure out how to build a solid search frontend and was wondering I it’s possible to use Search UI.
In my setup, I’m currently running an ElasticSearch (OSS) instance.

From what I can tell, there are only connectors for [AppSearch and SiteSearch](https://github.com/elastic/search-ui/tree/master/packages).

Is it possible to use the SearchUI package(s) without relying on App or SiteSearch? Has anybody tried setting up a “normal” ES instance with SearchUI? 

Any help is appreciated.

Have a great Monday!

**Comment by JasonStoltz** [comment]
Hey @julianklotz, I think a few folks have done this. We have an example here: https://github.com/elastic/search-ui#how-do-i-use-this-with-elasticsearch

**Comment by julianklotz** [comment]
thanks a lot!
