### ISSUE TITLE
Seperate <Searchbox> from Landing Page (all together)

### ISSUE THREAD

**Issue by jenswitzel** [elastic/search-ui#544]
Hi out there

We're ready to go with our UI (embedded into a Web-Template via SSI) - works great. :-)

Now we want to seperate:
- all pages, including the Searchbox with it's autosuggest => just offer the input on top of our templates 
- the all in one index.shtml as a landing page for ES-Search including all facettes and results

How would you manage this? I need to catch the "Enter" or "Search"-Button on all pages and forward them to the landing page.

Thanks
Jens

**Comment by JasonStoltz** [comment]
Hey, not sure if this is what you're asking, but here is an example of adding a search box to a website header: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#example-using-autocomplete-in-a-site-header
