### ISSUE TITLE
how to encrypt the json response (and when to decrypt)

### ISSUE THREAD

**Issue by jason-den** [elastic/search-ui#545]
As the following picture shows, by default, any user can get the raw data of all items through the search page inspection.
I'm not aiming iron-coating security, but just feel uncomfortable to expose all the data that straight forward. 
Is there a way to somehow seal it? 
> I know storing a decryption key on client side is not secure either, but at least we add one more layer and make the data harder to access?

![image](https://user-images.githubusercontent.com/16683831/109912744-cc89ff80-7d00-11eb-9ec6-083fbb046cb0.png)

**Comment by JasonStoltz** [comment]
I frankly don't understand your concern here. Regardless, this question is outside of the scope of search-ui, so I'm going to refer to refer you to the App Search discuss board that Elastic runs, which may be a more productive space to ask your question: https://discuss.elastic.co/c/enterprise-search/app-search/72
