### ISSUE TITLE
Connecting to Elastic App Search on Elastic Cloud

### ISSUE THREAD

**Issue by 684efs3** [elastic/search-ui#546]
On Elastic Cloud's App Search (SaaS), there is no hostIdentifier, only the API endpoint. However, if I try connecting using the searchKey, engineName, and endpointBase (like below as an example), no data is returned. 

```
const connector = new AppSearchAPIConnector({
  searchKey: "search-371auk61r2bwqtdzocdgutmg",
  engineName: "search-ui-examples",
  endpointBase: "http://cd4ec84f6052435eafe7b135fb890257.ent-search.westus2.azure.elastic-cloud.com"
});
```

How can I connect  Elastic Cloud's App Search (SaaS)?

**Comment by JasonStoltz** [comment]
Hey @684efs3 , what you're doing looks correct. Double check that the `endpointBase` and `searchKey` are valid by navigating to the "Credentials" screen inside of your Enterprise Search > App Search deployment. The value you should use as endpointBase will be listed as "API Endpoint".

If it still doesn't work, check out the Network tab in your browser and see what sort of http errors you are getting.
