### ISSUE TITLE
onSearch not called

### ISSUE THREAD

**Issue by ballabusta** [elastic/search-ui#548]
Hi,

I am trying to run the elasticsearch example with no connector. I have commented out the autocomplete part, implemented the onSearch function and passed it in the config. For some reason, it isn't stepping into the onSearch after I type a term inside the searchbox.

Do you have an idea why ? I wonder if I am missing something.

**Comment by JasonStoltz** [comment]
IU'm not sure what is going on there. Can you post some code for us to see?

**Comment by ballabusta** [comment]
Jason, thank you for your quick answer.
I found the issue.. fsevents install failed because of xcode (on catalina). I was able to fix the issues. Looks like it is now working as expected.
Kudos for what you built here!
