### ISSUE TITLE
Update results from another component

### ISSUE THREAD

**Issue by dgastudio** [elastic/search-ui#550]
Hello
Sorry, I don’t have much experience with react.

I have search ui up and running. Data are displayed in table. But my system requires dynamic updates so I’m using socket.client for it

What I need is when a specific message from a socket is received, reload the results and facets

but I’m totally stuck

any advice or code example?

Thank you

**Comment by JasonStoltz** [comment]
Read here for some more info on `setSearchTerm`: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#headless-core
