### ISSUE TITLE
setFilter range

### ISSUE THREAD

**Issue by dgastudio** [elastic/search-ui#558]
Hello
I want to change range filter
```
let filter ={
    "field": "created",
    "values": {
        "from": 1621544400,
        "to": 1621630800
    },
    "type": "all"
}
```

but, setting it as setFilter(filter.field, filter.values) doesn't work

i have tried to set filter also by this way
```

    setFilter(
        "created",
        {
          "from": filter.values.from,
          "to": filter.values.to,
          "name": "created"
        }
    )
```

but in both cases, resulting query is 
```
{
    "bool": {
        "must": [
            {
                "match_all": {}
            }
        ],
        "filter": [
            {
                "bool": {
                    "filter": {
                        "range": {
                            "created": {}
                        }
                    }
                }
            }
        ]
    }
}
```
can you please advise how to pass values correctly?

**Comment by dgastudio** [comment]
with debug enabled
before of settings filter
Search UI: State Update
```
[
    {
        "field": "created",
        "values": {
            "from": 1621198800,
            "to": 1621285200
        },
        "type": "all"
    }
]
```
Search UI: State Update
after setting the filter
```
[
    {
        "field": "created",
        "values": [
            {
                "from": 1621355976,
                "to": 1621528776
            }
        ],
        "type": "all"
    }
]
```

as i can see, filters values are moved in to array

**Comment by dgastudio** [comment]
https://github.com/elastic/search-ui/blob/cb774e2ab1e6831ff40523c62d76b57d4c71ed5f/packages/search-ui/src/actions/setFilter.js

replacing  values: [value], by  values: value, works fine

it's a bug or i'm doing something wrong

**Comment by JasonStoltz** [comment]
Hey @dgastudio, you are calling setFilters correctly. I just verified on master that I can run a similar call to setFilter with no issues. Are you still having an issue? Sorry, I was a little confused by your question.

**Comment by dgastudio** [comment]
Hello Jason and thank you for your response.

```
  setFilter(
        "created",
        {
          "from": filter.values.from,
          "to": filter.values.to,
          "name": "created"
        }
    )

```
as you can see, the VALUE is an object
but, in setFilter, is wrapped by array

So, the sent request doesn't work for me..

i had to add a validation typeof(values) === 'object' to make it work

**Comment by JasonStoltz** [comment]
I'm sorry, because I still don't understand what the issue is.

You are calling `setFilter` correctly, with an object.

It should be sent in your API request like:

```
filters: {
  "all": [
    {
      "all": [
        {
          "created": {
            "to": 1621528776,
            "from": 1621355976
          }
        }
      ]
    }
  ]
}
```

**Comment by dgastudio** [comment]
strange, maybe it's because i'm using https://github.com/elastic/search-ui/tree/master/examples/elasticsearch

anyway, i'll try it again
thank you very much for your advice?

**Comment by JasonStoltz** [comment]
Ahhh, ok. Sorry, we were talking two different technologies, I didn't pick up on the fact that you are using Elasticsearch. Yes, it's possible you might run into some issues with that. If they need to be updated anywhere, I would think it'd be here: https://github.com/elastic/search-ui/blob/master/examples/elasticsearch/src/buildRequestFilter.js

**Comment by dgastudio** [comment]
It was an issue with elasticsearch .

Thank you for you help, have a nice day!
