### ISSUE TITLE
Restore deleted engine by accident ?

### ISSUE THREAD

**Issue by shadoo77** [elastic/search-ui#559]
Hello
I deleted an engine by accident, is there a way to restore it again ?
And if not , how can i recreate an engine with the same name ?
because it refuses , it says : **Name cannot be reused**, i really needed
Thanks a lot

**Comment by JasonStoltz** [comment]
@shadoo77 Try posting this one to https://discuss.elastic.co/. I think you'll have better luck getting an answer there.
