### ISSUE TITLE
Clearing search term by calling setSearchTerm doesn't allow you to search the same term again

### ISSUE THREAD

**Issue by PrabhdeepSingh** [elastic/search-ui#561]
I'm experiencing a weird bug and not sure if something I'm doing wrong or if it's search-ui.

I created a ClearSearchAndFilters component using the withSearch and on button click I'm calling setSearchTerm('', { shouldClearFilters: true }); which works but if I search for the same term and select it in the suggested terms, it doesn't do the search.

```
import React from 'react';
import { withSearch } from '@elastic/react-search-ui';

function ClearSearchAndFilters({ resultSearchTerm, filters, setSearchTerm }) {
	if (resultSearchTerm.length > 0 || filters.length > 0) {
		return (
			<button
				type="button"
				className=""
				onClick={() => {
					setSearchTerm('', { shouldClearFilters: true });
				}}
			>
				Clear
			</button>
		);
	}

	return <></>;
}

export default withSearch(({ resultSearchTerm, filters, setSearchTerm }) => ({
	resultSearchTerm,
	filters,
	setSearchTerm
}))(ClearSearchAndFilters);
```

Here is a .zip file with a .webm video of what I'm dealing with 
[Search-UI setSearchTerm Bug.zip](https://github.com/elastic/search-ui/files/6535606/Search-UI.setSearchTerm.Bug.zip)

**Comment by JasonStoltz** [comment]
Hmmm, that's strange. Is there any way you could set `debug: true` in your search configuration to try to debug a little bit?

It will log all actions that occur, and the before state, and the after state.

It'd be helpful if you can identify the action where something is going wrong, like where the "after" state does have the expected results, etc.

**Comment by JasonStoltz** [comment]
Or if you have a sandbox or something where I could reproduce this behavior.

**Comment by PrabhdeepSingh** [comment]
Sure, I can try the debug: true and as for a sandbox no, but I can try putting one together. If it's helpful I can always send you a link to our site where this problem is occurring?

**Comment by JasonStoltz** [comment]
Yes, that would be helpful.

**Comment by PrabhdeepSingh** [comment]
Here's a link to our site where the problem is occurring: https://www.iansresearch.com/portal
I plan on debugging/setting up a sandbox with the issue tomorrow.

**Comment by JasonStoltz** [comment]
Still relevant
