### ISSUE TITLE
Remove id from the Results component

### ISSUE THREAD

**Issue by HesterG** [elastic/search-ui#562]
I am wondering that whether there is a way to remove id from the Results component, thanks

**Comment by JasonStoltz** [comment]
There's no super simple way to do this, you'd need to create your own result component. https://github.com/elastic/search-ui/blob/master/ADVANCED.md#component-views-and-html

I have a ticket in for a feature that would enable you to do this, but it's not implemented yet: 
https://github.com/elastic/search-ui/issues/426

I'm going to close this in favor of #426.
