### ISSUE TITLE
All results are shown when page is refreshed

### ISSUE THREAD

**Issue by HesterG** [elastic/search-ui#563]
My project is a React web app created by `create-react-app`, and i am following the [official document](https://www.elastic.co/blog/how-to-build-great-react-search-experiences-quickly) to integrate search-ui into it. When my page is refreshed, looks like all documents are shown automatically even when i do not search for them, which is not desirable. I guess this is because it treats the empty string as a search query when i refreshed the page and shows all results. I am wondering if there is a way to prevent this default action, thanks.

**Comment by JasonStoltz** [comment]
The `alwaysSearchOnInitialLoad` configuration should help here. It is `true` by default. https://github.com/elastic/search-ui/blob/master/ADVANCED.md#advanced-configuration
