### ISSUE TITLE
Show filters button is not displayed when using bootstrap.min.css in app

### ISSUE THREAD

**Issue by elangovansword** [elastic/search-ui#564]
The Show filters button is not displaying when resizing the browser window after adding  bootstrap css.

When importing css style sheet 
`import 'bootstrap/dist/css/bootstrap.min.css';`

or 

Adding in index file as 
```
<link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous"
  />
```
### Before  adding  bootstrap css
<img width="797" alt="Screen Shot 2021-06-03 at 2 01 58 PM" src="https://user-images.githubusercontent.com/78472485/120615508-fbd21900-c475-11eb-8a40-cd05058abe4f.png">

### After  adding  bootstrap css
<img width="799" alt="Screen Shot 2021-06-03 at 2 01 29 PM" src="https://user-images.githubusercontent.com/78472485/120614217-a1848880-c474-11eb-80ad-79f158d7bf86.png">

**Comment by JasonStoltz** [comment]
@elangovansword Hello 👋. Most likely bootstrap is adding some global style overrides that interfere with the custom CSS stylesheet from search-ui. There should be no expectation that if you're adding a CSS library like bootstrap, that the search-ui styles will be 100% compatible. If you can identify an improvement for our stylesheet that will avoid this conflict I am happy to accept a PR.
