### ISSUE TITLE
oauth authentication

### ISSUE THREAD

**Issue by shazzrick** [elastic/search-ui#571]
@JasonStoltz 
is it possible to use oauth authentication in search-ui/example/sandbox/ , coz i only see api auth to app search and site search there

**Comment by JasonStoltz** [comment]
I don't believe so. API auth is the only option currently.

**Comment by shazzrick** [comment]
![image](https://user-images.githubusercontent.com/73170995/123649655-90e2ea80-d847-11eb-942f-7d6697fe93e2.png)

**Comment by shazzrick** [comment]
i meant how to configure it with workplace search coz it asks for engine key and name which workplace search doesnt have
so what parameters do we need to pass in to configure workplace search in custom UI

**Comment by JasonStoltz** [comment]
Ah, gotcha. There are 2 [connectors](https://github.com/elastic/search-ui#2-connectors) available currently, 1 for App Search, and one for Swiftype Site Search. They will not work with Workplace Search, and there is no connector for Workplace Search.

There may at some point be a connector for Workplace Search, but at the time of writing this, there is not. You could still manually connector Search UI to Workplace Search by [implementing your own connector](https://github.com/elastic/search-ui/blob/master/ADVANCED.md#build-your-own-connector).
