### ISSUE TITLE
How to use headless core for range ?I am familiar with headless core concept but couldn't find any reference regarding range ?

### ISSUE THREAD

**Issue by yg-yash** [elastic/search-ui#575]
i am using the headless core approach since i have custom ui for elastic search since i dont wanna build query for everything i am using this approach .
Is there any way i can query range for price or any number component?

**Comment by JasonStoltz** [comment]
addFilter action
https://github.com/elastic/search-ui/blob/master/ADVANCED.md#actions

Follow the link there to https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/src/types/FilterValue.js

And then you can see FilterValueRange referenced: https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/src/types/FilterValueRange.js

So you can apply a range like:
```
addFilter(
  'foo',
  {
  from: 100,
  to: 1000,
  name: 'some name for this range'
  }
)
```

**Comment by yg-yash** [comment]
@JasonStoltz 

thanks so much for this was banging my head 

one suggestion i think this should be in documentation

and i have one more will be raising a new ticket for that

**Comment by JasonStoltz** [comment]
Good idea.
