### ISSUE TITLE
how to show selected filter 

### ISSUE THREAD

**Issue by PradeepGorule14** [elastic/search-ui#578]
Hi everyone I'm new in elastic search UI and I want to  show the selected filters. I checked everything but did not get any proper idea how to implement so could you please help me with this

**Comment by JasonStoltz** [comment]
If you're using Facet components, they will show selected filters.

If you literally want to show all selected filters outside of Facet components than you would have to access the `filters` object directly through `WithSearch`: https://github.com/elastic/search-ui/blob/master/ADVANCED.md#headless-core-concepts.
