### ISSUE TITLE
Question about debugging in Visual Studio Code

### ISSUE THREAD

**Issue by MJonker** [elastic/search-ui#589]
Hi,

I am getting started with the search-ui components and have the elasticsearch-example from the search-ui up and running in Visual Studio Code.
I can create a launch.json to configure the environment for debugging.
Although the debugger starts, any breakpoint that I set becomes 'unbound'.
I have tried to add the outFiles option, but that does not help.

```
{
            "type": "node",
            "request": "launch",
            "name": "search-ui debug",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run-script", "start"],
            "outFiles": [ "${workspaceRoot}/src/*.js" ]
            }
```
I hope someone can share a working launch.json to help get started with debuggin.
In other React Apps I don't have this problem.

I have also asked the question here: https://discuss.elastic.co/t/debugging-the-elasticsearch-example-in-search-ui/286594/2 but they suggested to try it here.

**Comment by yi-fan-song** [comment]
I don't think you'll be able to debug most React code with `"type": "node"`. node is the server side runtime, and react code runs most of the time in the browser unless you're running on next.js or similar.

Try attaching your vscode to the chrome debugger with something like this:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "search-ui debug",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src"
        }
    ]
}
```
You'll have to start the dev server in a terminal before debugging. Maybe you can tweak this config to start it for you, but I'm not too familiar with debugging js with vscode.
