### ISSUE TITLE
Ranges don't behave as expected, price to 6000 should match a document with that price. 

### ISSUE THREAD

**Issue by martynball** [elastic/search-ui#595]
Hey, not sure if anything can be done about this as I couldn't find anything mentioned on the Elastic API. But for example let's say I pass the following filter:

```json
{
  "filters": {
    "all": [
      {
        "any": [
          {
            "price": {
              "from": -1,
              "to": 6000
            }
          }
        ]
      }
    ]
  },
  "page": {
    "size": 24,
    "current": 1
  }
}
```

I'd expect for documents with a `price` of 6000 to be returned, however only documents below that are. My only idea would be to add a buffer, but this isn't ideal!

**Comment by JasonStoltz** [comment]
Could you just add 1 to the "to" field in order to make it inclusive?

**Comment by JasonStoltz** [comment]
This is a totally valid issue, but it's more of an issue with App Search than search-ui. I'm going to close it for now. We track issues for App Search internally, I'll enter an issue about it there.

**Comment by JasonStoltz** [comment]
Actually, FWIW, this is consistent with the underlying Elasticsearch API, which *includes* the from value and *excludes* the to value: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html.

**Comment by martynball** [comment]
> Actually, FWIW, this is consistent with the underlying Elasticsearch API, which _includes_ the from value and _excludes_ the to value: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html.

Thanks for looking at this, I will check our implementation and add fixes based on the above.
