### ISSUE TITLE
Huge shoutout to @ckeboss and @mtlewandowsk89

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#596]
Just wanted to put a huge shoutout *somewhere* to @ckeboss and @mtlewandowsk89 for their help with https://github.com/elastic/search-ui/pull/592.

I'm over the moon to have a community contribution like this.

Thank you!

**Comment by ckeboss** [comment]
Glad we were able to get it over the finish line. Would also want to include @mtlewandowsk89 for getting this started also.
