### ISSUE TITLE
Dependency on old rc-pagination causes Webpack build errors

### ISSUE THREAD

**Issue by kanadaj** [elastic/search-ui#598]
Due to having a dependency on rc-pagination 1.x (which uses `babel-runtime` explicitly), trying to use the search UI in webpack along with `core-js` 3 and `@babel/runtime-corejs3` and `@babel/plugin-transform-runtime` (not sure this one is even needed for repro) causes a `Module not found` issue:

```
Module not found: Error: Can't resolve 'core-js/library/fn/symbol/iterator' in 'H:\Work\Project\node_modules\babel-runtime\core-js\symbol'
 @ ./node_modules/babel-runtime/helpers/typeof.js 5:16-53
 @ ./node_modules/babel-runtime/helpers/possibleConstructorReturn.js 5:15-43
 @ ./node_modules/rc-pagination/es/Pagination.js 5:0-89 40:16-42
 @ ./node_modules/rc-pagination/es/index.js 1:0-39 1:0-39
 @ ./node_modules/@elastic/react-search-ui-views/es/Paging.js 6:0-41 18:42-54
 @ ./node_modules/@elastic/react-search-ui-views/es/index.js 6:0-45 6:0-45
 @ ./node_modules/@elastic/react-search-ui/es/containers/ErrorBoundary.js 21:0-63 43:25-38
 @ ./node_modules/@elastic/react-search-ui/es/containers/index.js 1:0-59 1:0-59
 @ ./node_modules/@elastic/react-search-ui/es/index.js 5:0-29 5:0-29
```

Adding an explicit reference to `rc-pagination@3.1.14` seems to fix this. Maybe bump the package version?

**Comment by zhuhaow** [comment]
I can see rc-pagination is on the road map to be replaced https://github.com/elastic/search-ui/issues/308, but it has been quite long since the decision had been made and there's little progress. 

I think we should at least keep the packages used up-to-date at some level before they are replaced.

**Comment by JasonStoltz** [comment]
Good thought, we could simply update our dependencies in the meantime.

**Comment by ivanteso** [comment]
Hello, any update on this one?

**Comment by JasonStoltz** [comment]
We're updating some dependencies now. I'll see if we can get this one on the list @yakhinvadim.
