### ISSUE TITLE
ResultsPerPage component should have configurable options

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#60]
Currently, the options "20", "40", and "60" are hardcoded as options in the ResultsPerPage components: https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/src/containers/ResultsPerPage.js#L38.

This should be configurable, as users may want options other than these defaults.

**Comment by m-sureshraj** [comment]
I would like to work on this issue. How can I assign this issue to myself?

**Comment by JasonStoltz** [comment]
@m-sureshraj For now, I'd say just comment here (like you've done) and enter a PR.

**Comment by m-sureshraj** [comment]
PR - https://github.com/elastic/search-ui/pull/224
