### ISSUE TITLE
TypeError: __vite_ssr_import_1__.default is not a constructor

### ISSUE THREAD

**Issue by 684efs3** [elastic/search-ui#600]
I am using the sample ElasticSearch (national parks)[https://codesandbox.io/s/kdyms]. I am using this inside Astro, which is a framework that uses Vite. Astros lets you use React inside it.

I keep getting this error:

```
ypeError: __vite_ssr_import_1__.default is not a constructor
```

and it points to the the line:

```
const connector = new AppSearchAPIConnector
```

Any ideas on how to fix this?

**Comment by joemcelroy** [comment]
Sounds like an issue with how astro imports packages on server-side and causing an issue with search-ui. Did you manage to fix it?
