### ISSUE TITLE
Single Node and NPM version

### ISSUE THREAD

**Issue by tarekziade** [elastic/search-ui#607]
We currently have several versions of Node.js declared to work in this project:

- `package.json` :   `14.17.0`
- Circle CI : `10.16`
- `CONTRIBUTING.md` : `10.16`

It would be nice to have a single source of truth for the Node version, so when we change it we don't miss a spot.
I guess `package.json` could be it, and other places point to it

**Comment by JasonStoltz** [comment]
Good point. It should be at least 14.17.0. Thanks for pointing that out.

**Comment by joemcelroy** [comment]
i updated the .circleci node version in a previous PR. Will update the contributing doc version too.
