### ISSUE TITLE
Server-side filter value / facet value searches

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#621]
**Is your feature request related to a problem? Please describe.**
If you have a facet with something like 1 million potential values, it's infeasible for a user to find a particular Facet Value option to apply.

They need some sort of mechanism to search for Facet Values server-side.

**Describe the solution you'd like**

We'd need something on a connector to support additional data fetches like this. It might be to an entirely separate index, like one that specifically holds data on these facet values.

We'd also need updated facet or filter components that support making this additional API call.

I'm not entirely sure what the final solution might look like,  but I discussed it with a user here: https://discuss.elastic.co/t/is-it-possible-to-implement-a-custom-search-box-text-field-for-filtering-by-entity-labels-with-autocomplete/295818/3.

**Describe alternatives you've considered**

**Additional context**
Algolia supports this natively, for reference: https://www.algolia.com/doc/api-reference/api-methods/search-for-facet-values/.

**Comment by joemcelroy** [comment]
im closing this ticket until the API supports such feature.
