### ISSUE TITLE
Why use this instead of ReactiveSearch? What are the differences? Is there a comparison table somewhere?

### ISSUE THREAD

**Issue by tombburnell** [elastic/search-ui#627]
Why use this instead of ReactiveSearch? What are the differences? Is there a comparison table somewhere?

**Comment by joemcelroy** [comment]
hey Tom, I see you have asked this question on discuss too. I will copy in my response here for those who are also interested. Also just a friendly reminder that github issues are for code related questions and therefore closing this ticket.

It depends on the route that you're taking with Elasticsearch and how involved you want to get with the code. I would say they're largely the same (from a feature standpoint) but serve different use-cases.

Search-ui (https://github.com/elastic/search-ui/) is a frontend framework that allows you to build Search experiences on the frontend easily. Its designed in mind for [Elastic Enterprise Search | Elastic](https://www.elastic.co/enterprise-search). This pairing is great for companies who want search with little code. Then you have an option with building your own connector to use for any backend ( for example your own API). The advantage there is its awesome for those who want to get started quickly with enterprise search but then transition to their own API. Writing your own connector, you do not need to rewrite the frontend again to transition between enterprise-search and Elasticsearch or another technology.

Search-ui is also backed by Elastic and being actively developed for.

Another reason is Reactivesearch out of the box calls Elasticsearch directly from the browser and requires Elasticsearch to be exposed publicly. We don't advise you to expose Elasticsearch for security reasons (though this does depend on the situation).

Theres another called Searchkit https://searchkit.co/

Hope this helps.
Joe
