### ISSUE TITLE
Multiple Search UIs on the same page - how to decouple?

### ISSUE THREAD

**Issue by 684efs3** [elastic/search-ui#629]
I have two Search UIs on a page (using NextJS). One is a general search box and the other has facets. When I click on the facets of search UI 2, and then click on my search box to do a global search, the search box will automatically apply the facets of search UI 2.

Is there a way to decouple the two Search UIs? Thank you very much!

**Comment by JasonStoltz** [comment]
As long as you wrap each of these in entirely different `SearchProviders`, they should be completely decoupled.

The one thing that they *would* share is URL state. In the `SearchProvider` for the global search, try turning off `trackUrlState` and see if that solves your issue.

**Comment by 684efs3** [comment]
Worked - thank you Jason!
