### ISSUE TITLE
Driver ignore additional properties within the facets. 

### ISSUE THREAD

**Issue by martynball** [elastic/search-ui#630]
**Is your feature request related to a problem? Please describe.**

Within my component I return the facets from an API, these have additional settings for the UI as well as the settings for this package. If I provide these additional properties this package crashes and throws an error. 

**Describe the solution you'd like**

Ignore additional properties so additional sanitisation isn't needed?

**Describe alternatives you've considered**

This is the fix I perform currently, with an example of a facet object:
```json
{
  "name": "engine_l",
  "type": "range",
  "ranges": [...],
  "label": "Engine size",
  "order": 14,
  "append": "litre",
  "view": "range-dropdown",
  "ranges": { "from": 0.1, "to": 3 },
  "pluralize": "number",
  "buffer": 0.1,
  "stepping": [
    { "from": 0, "to": 1, "step": 1 },
    { "from": 1, "to": 2, "step": 0.2 },
    { "from": 2, "to": 3, "step": 0.5 },
    { "from": 3, "step": 1 }
  ]
}
```
```javascript
const driver = new SearchDriver({
    searchQuery: {
        facets: Object.assign({}, ...Object.entries(this.facets)
            .map(([k, v]) => ({[k]: (({name, type, ranges}) => ({name, type, ranges}))(v)})))
    }
});
```

**Comment by joemcelroy** [comment]
Thanks @martynball. Are you building your own facet components to use this additional metadata? Are you using the `Facet` container, overriding the view or building a new component entirely? 

Reason why im asking is what type of change would be needed by the components to allow you to utilize this metadata too.
