### ISSUE TITLE
Component Imports Change Discussion

### ISSUE THREAD

**Issue by joemcelroy** [elastic/search-ui#632]
### Current Situation

```jsx

import { Facet } from '@elastic/react-search-ui';
import { BooleanFacet } from "@elastic/react-search-ui-views";

const App = () => (
    <SearchProvider config={config}>
        <Sidebar>
            <Facet
                label="Test"
                field="test"
            />
            <Facet
                label="Test2"
                field="test2"
                view={BooleanFacet}
            />
        </Sidebar>
    </SearchProvider>
)

```

Behind the scenes, Facet is importing the display component from views. If a view prop is not provided, it uses the default which is (`MultiCheckboxFacet`) and imported within `@elastic/react-search-ui-views`.

Today `@elastic/react-search-ui` has a dependency on `@elastic/react-search-ui-views`.

If you want to customise the Facet display, you override the via the `view` prop

```jsx

import { Facet } from '@elastic/react-search-ui';

const App = () => (
    <SearchProvider config={config}>
        <Sidebar>
            <Facet
                label="Test"
                field="test"
                view={myCustomFacetComponent}
            />
            <Facet
                label="Test2"
                field="test2"
            />
        </Sidebar>
    </SearchProvider>
)

```

The challenges here are:
- Even if the developer does not want to use our view components, they are being imported into their app, adding to the bundle size.
- The props for the container may not match the props for the view component, leading to a disconnect between the API the developer uses (`Facet`) and the view's API (`MultiCheckboxFacet` in this example)
- Difficult for us to ship multiple view packages without the developer needing to do this. Below example will be bundling all three packages too (`@elastic/react-search-ui`, `@elastic/react-search-ui-views`, `@elastic/react-search-ui-eui-views`)

```jsx

import { Facet } from '@elastic/react-search-ui';
import { MultiCheckboxFacet, BooleanFacet } from '@elastic/react-search-ui-eui-views';


const App = () => (
    <SearchProvider config={config}>
        <Sidebar>
            <Facet
                label="Test"
                field="test"
                view={MultiCheckboxFacet}
            />
            <BooleanFacet
                label="Test"
                field="test"
                view={BooleanFacet}
            />
        </Sidebar>
    </SearchProvider>
)

```

### Proposal
Rather than importing the container, we import the views themselves. This way the developer is interacting directly with the component's API rather than via the container.
The change required for developers who want to upgrade is to change the package import. This will be viewed as a breaking change. 

Example below

```jsx

// import { Facet } from '@elastic/react-search-ui';
import { Facet, MultiCheckboxFacet, BooleanFacet } from '@elastic/react-search-views';

const App = () => (
    <SearchProvider config={config}>
        <Sidebar>
            <Facet
                label="Test"
                field="test"
                view={myCustomFacetComponent}
            />
            <MultiCheckboxFacet
                label="Test"
                field="test"
            />
            <BooleanFacet
                label="Test"
                field="test"
            />
        </Sidebar>
    </SearchProvider>
)

```
The advantage is now the developer has a direct access to the API for the different Facet components giving a better development experience.

If they override the view, they still can use the `Facet`

#### Multiple View packages

With a simple change to the package name, the developer can switch between views (notice the package import is now from `react-search-ui-eui-views`) 

```jsx

// import { Facet } from '@elastic/react-search-ui';
import { Facet, MultiCheckboxFacet, BooleanFacet } from '@elastic/react-search-ui-eui-views';

const App = () => (
    <SearchProvider config={config}>
        <Sidebar>
            <MultiCheckboxFacet
                label="Test"
                field="test"
            />
            <BooleanFacet
                label="Test"
                field="test"
            />
        </Sidebar>
    </SearchProvider>
)

```

And the props for the display component has the opportunity to be terse to the display component (for example we could allow passing down eui specific props without touching the container)

**Comment by yakhinvadim** [comment]
I like this. I think it's worth making a breaking change. 

I'm not totally clear how the containers would pass the props to the views, do you have a vision for it?

**Comment by joemcelroy** [comment]
@yakhinvadim so today the containers pass props to the views. Facets for example, you are using `Facet` which is a container and the container uses its default or the custom view you passed as a prop. The props you provide to `Facet` container, some of them are passed down to the view component. 

The proposal is a flip around. You use the a component which behind the scenes uses the container. For example the developer uses `<MultiCheckboxFacet />` component rather than `<Facet view={MultiCheckboxFacet} />`
