### ISSUE TITLE
Downloaded .zip w/Search-UI frontend does not successfully install

### ISSUE THREAD

**Issue by csffsc** [elastic/search-ui#655]
Okay, so I am using the hosted service by elastic search, running v8.0.  Search-UI was created with the GUI inside of elastic app search, every field but the thumbnail field was used.  Download the .zip and extract, check my version of NPM and Node with:
> % npm -v
> 8.5.3
> % node -v
> v16.14.0

With that I go on to install with npm install, and after about a minute of building, I see a few pages of Warnings that the specified packages are deprecated, and then a very long 10-20 page output of errors that prevent npm start from being available.

> % npm start
> > app-search-reference-ui-react@1.2.0 start
> > react-scripts start
> sh: react-scripts: command not found

I'm attaching the log output to this issue.

Interestingly enough:
1.  I can make the search-ui code work if I extract it, put it in a GitHub repo, and then build it with https://codesandbox.io
2. I can also successfully run locally the example sandbox code using npm install, npm start the code found here: https://github.com/elastic/search-ui/tree/master/examples/sandbox

error log output -  [2022-03-08T01_58_05_997Z-debug-0.log](https://github.com/elastic/search-ui/files/8211444/2022-03-08T01_58_05_997Z-debug-0.log)

**Comment by joemcelroy** [comment]
hey @csffsc - so looking at the error log output, the dependency install via NPM is failing to install libsass on m1 machines. See https://github.com/sass/node-sass/issues/3033. Please try installing node 14 under rosetta and try installing dependencies again. 

In meantime we need to swap node-sass dep for something more universal like sass. Il create an issue for this soon.

**Comment by csffsc** [comment]
Thanks @joemcelroy!  

For anyone else that encounters this issue, I followed the "install" and "switch architecture" headings of this page: https://www.jurnalanas.com/node-js-mac-m1/ to successfully install Node v14.

NPM install still had a fair amount of warnings for outdated dependencies, however there were no errors and npm start works!

**Comment by JasonStoltz** [comment]
@joemcelroy Do you know which library has a dependency on node-sass ?
