### ISSUE TITLE
Many configurations are missing from type definition of SearchProvider for SearchDriver

### ISSUE THREAD

**Issue by zhuhaow** [elastic/search-ui#671]
Many configurations for `SearchDriver` are missing from `SearchProviderProps` in [current typedefs](https://github.com/elastic/search-ui/blob/master/packages/react-search-ui/src/SearchProvider.tsx#L17) as we are using whitelist instead of blacklist. So many configs such as `trackUrlState`, `alwaysSearchOnInitialLoad` are missing.

**Comment by joemcelroy** [comment]
thanks for flagging @zhuhaow. Will add them soon. Any other areas that are missing?

**Comment by zhuhaow** [comment]
AFAIK this is the only one.

I'm just using a small set of the features search UI provides, so there could be more.

**Comment by joemcelroy** [comment]
Yeh - I believe we do have good coverage of types as all the tests were also converted to typescript. SearchProvider slipped through because these particular attributes weren't tested. 

Happy to accept a PR for change otherwise il submit / publish the updates!

**Comment by zhuhaow** [comment]
I was trying but I can install python2 on my M1 mac. I'm sure it's possible but I don't want to investigate that. It would be great if you could fix it.
