### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by Linh-Vo** [elastic/search-ui#678]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1130" alt="Screen Shot 2022-03-21 at 20 31 26" src="https://user-images.githubusercontent.com/22366774/159271025-eeb06575-e60b-4f3f-befd-127d143991d2.png">

**Which backends and packages are you using:**
Backend: [App Search, Elasticsearch, Site Search, Workplace Search, custom]
Packages: [react-search-ui, search-ui-app-search-connector, etc.]

**Comment by joemcelroy** [comment]
thanks for report. Could you tell me what version of typescript you are on? Would it be possible for you to update it (4+). I think the issue here is the syntax is not supported in earlier versions of typescript.

**Comment by Linh-Vo** [comment]
My current typescript version is 3.9.5
I will try to upgrade it to 4+. Let you know soon!
thanks

**Comment by joemcelroy** [comment]
thanks for highlighting though, I will make it compatible with older versions of typescript in meantime :)

**Comment by Linh-Vo** [comment]
I upgrade to 4+ version, but I faced another error with: import {withSearch} from '@elastic/react-search-ui';

**Comment by joemcelroy** [comment]
hi @Linh-Vo - missed your last comment. Did you manage to resolve it? I cant see why that would result in an error.

**Comment by joemcelroy** [comment]
Closing this issue for now. LMK if you encounter the issue and ill investigate.

**Comment by omonk** [comment]
@joemcelroy - I am getting this with the latest version of the package `1.14.0`, TS version `3.9.10` as well. Was there ever any work done to support older versions of typescript?
