### ISSUE TITLE
Error `setState` is called before `WithSearch` is mounted

### ISSUE THREAD

**Issue by zhuhaow** [elastic/search-ui#679]
A minimal react component with just

```
<SearchProvider ...><WithSearch ...>{() => <></>}</WithSearch></SearchProvider>
```

would cause error

```
Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the WithSearch component.
SearchProvider
Search
main
div
MyApp
PureComponent@
ReactDevOverlay
_classCallCheck@
AppContainer
Root
```

I think the reason I'm seeing this is I'm using next.js with HMR enabled. But I can't find a way to disable HMR so I didn't test.

The root cause is probably https://github.com/elastic/search-ui/blob/1a92543da3dc076eb3945f766f8775f4434dafef/packages/react-search-ui/src/withSearch.tsx#L83 where the `unmounted` is not set to `true` in `componentDidMount` but in constructor when initialized, which doesn't seem right anyway.

I'm also wondering what is the use of the `unmounded` flag since the subscription seems properly unsubscribed https://github.com/elastic/search-ui/blob/1a92543da3dc076eb3945f766f8775f4434dafef/packages/react-search-ui/src/withSearch.tsx#L79.

Wondering what is the right way to fix this. I can create a PR for this since the node-sass is already updated so I can use my M1 Mac to build the project.

**Comment by joemcelroy** [comment]
Thanks for the fix. The reason for the `unmounted` flag is the subscription handler is called every time there is an update of state, usually occurred from a result response. The user may of navigated away from the page but a network request is still in progress. This flag is to abort the state update when that occurs. Isn't pretty but easiest way.

BTW you can use [dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) to only render on client. 

Im going to write tests for this and verify this change is ok.

**Comment by zhuhaow** [comment]
Thanks for the explanation.

I checked the code from https://github.com/elastic/search-ui/blob/1a92543da3dc076eb3945f766f8775f4434dafef/packages/search-ui/src/SearchDriver.ts#L513-L524

It seems like the `unmounted` flag may not be needed in this case as the execution of js functions won't be interleaved. The subscription callback won't be called any more after `unsubscribeToStateChanges` is called when component is unmounted.

**Comment by joemcelroy** [comment]
Yeh that is true. Il try removing this flag and add tests to verify. Il base it off your changes and if you spare a moment, please review.

Thanks again :)

**Comment by zhuhaow** [comment]
That would be perfect

**Comment by joemcelroy** [comment]
So had a look this morning, thought I would of been able to remove this check as the tests were fine with this approach but found in practice it is still needed. Even though the lifecycle functions are being called to subscribe / unsubscribe, when the searchdriver calls to update, theres still subscriptions for components which are in the process of being unmounted.  I believe this is down to how react batches its changes in production.

I had a look at other "connect" HOC components from popular libraries like redux and they have similar logic of keeping a separate reference of the components lifecycle. 

I slightly adjusted the variable name + adjusted tests. Going to merge this and hopefully solves your problem in nextjs.

**Comment by zhuhaow** [comment]
Great, thanks.
