### ISSUE TITLE
Fuzzy Suggestions in App Search

### ISSUE THREAD

**Issue by DeepakSharda** [elastic/search-ui#686]
While building a geocoding search engine where village names and POI names (spellings) are so phonetic similar matching the correct query is difficult.

Elasticsearch App search supports fuzzy search but this is when user selects one of the drop down results. 

If we could give fuzzy search while search as you type so it will be a great additional features.

**Comment by JasonStoltz** [comment]
Hey, thank you for the feedback on App Search. Since it doesn't necessarily pertain to Search UI, I'm going to close this issue. A good place to raise this would be on our [Discuss](https://discuss.elastic.co/c/enterprise-search/84) forums.
