### ISSUE TITLE
Wrong type definition for callbacks in `SearchDriverOptions`

### ISSUE THREAD

**Issue by zhuhaow** [elastic/search-ui#687]
`SearchDriverOptions` is defined as 

https://github.com/elastic/search-ui/blob/af029f57260d3b4d03bd8a0bb47d541e8ee00024/packages/search-ui/src/SearchDriver.ts#L91-L106

where some of the event callbacks has wrong type definitions.

I didn't go over all of them, but take `onSearch` for example https://github.com/elastic/search-ui/blob/af029f57260d3b4d03bd8a0bb47d541e8ee00024/packages/search-ui/src/SearchDriver.ts#L96 the real call is here https://github.com/elastic/search-ui/blob/af029f57260d3b4d03bd8a0bb47d541e8ee00024/packages/search-ui/src/SearchDriver.ts#L412

where the first parameter type is wrong (should be `RequestState`), second and third (the `next`) parameters are missing.

**Comment by joemcelroy** [comment]
thanks for reporting this! Yeh i found similar problems when I was building the APIConnector interface and missed this. Il try fix the types for this soon.

**Comment by joemcelroy** [comment]
merged the changes @zhuhaow LMK if you spot anything more. Will be released soon as 10.2.0

Thanks

**Comment by joemcelroy** [comment]
1.10.2 is now released. LMK of any issues :)

**Comment by zhuhaow** [comment]
Thanks for the fix
