### ISSUE TITLE
Keyboard Getting Dismissed in some Android Devices

### ISSUE THREAD

**Issue by frantoqui** [elastic/search-ui#694]
**Describe the bug**
I found a weird problem with this amazing library, in some Android devices like Xiaomi, when I type keyboard gets dismissed, my code is the one below, there is nothing weird with this, I also tried using only SearchBox with the same result.

**Which backends and packages are you using:**
Backend: [App Search]
Packages: [react-search-ui]

`import React, {useState} from "react";
import { useParams } from "react-router-dom";

import AppSearchAPIConnector from "@elastic/search-ui-app-search-connector";

import {
	ErrorBoundary,
	Facet,
	SearchProvider,
	Results,
	PagingInfo,
	ResultsPerPage,
	Paging,
	Sorting,
	WithSearch, SearchBox
} from "@elastic/react-search-ui";
import { Layout } from "@elastic/react-search-ui-views";
import "@elastic/react-search-ui-views/lib/styles/styles.css";
import SearchProduct from '../../components/SearchProduct'

import {
	buildAutocompleteQueryConfig,
	buildSearchOptionsFromConfig,
	buildSortOptionsFromConfig,
} from "./config/config-helper";
import {getDefValues, getImagePath, getCurrentCatalog} from "../../common/functions";

const connector = new AppSearchAPIConnector({
	searchKey: process.env.REACT_APP_SEARCHKEY,
	engineName: process.env.REACT_APP_ENGINENAME,
	endpointBase: process.env.REACT_APP_ENDPOINTBASE,
	cacheResponses: true
});

export default function Search() {
	const [colors, setColors] = useState([]);
	const {param} = useParams();
	let storeid = getCurrentCatalog();

	const config = {
		searchQuery: {
			disjunctiveFacets: ["minprice","colors", "sizes", "categories"],
			facets: {
				minprice: {
					type: "range",
					ranges: [
						{ from: 0, to: 50, name: "1Bs - 50Bs" },
						{ from: 50, to: 150, name: "50Bs - 150Bs" },
						{ from: 150, to: 250, name: "150Bs - 250Bs" },
						{ from: 250, name: "> 250Bs" }
					]
				},
				categories: { type: "value" },
				colors: { type: "value" },
				sizes: { type: "value" },
			},
			...buildSearchOptionsFromConfig()
		},
		autocompleteQuery: buildAutocompleteQueryConfig(),
		apiConnector: connector,
		alwaysSearchOnInitialLoad: true,
		initialState: {
			searchTerm: param
		},
		trackUrlState: false,
		suggestions: {
			types: {
				documents: {
					fields: ["productname"]
				}
			}
		}
	};
	function toggleCheckbox(element, e, item)
	{
		element.checked = !element.checked;
		if(element.target.checked) {
			e.onSelect(item.value)
		} else {
			e.onRemove(item.value)
		}
	}

	const addOrRemoveColor = (array, item) => {
		const exists = array.includes(item)

		if (exists) {
			setColors(array.filter((c) => { return c !== item }))
		} else {
			const result = array
			result.push(item)
			setColors(result)
		}
	}
	const windowWidth = window.innerWidth
	return (
		<SearchProvider config={config}>
			<WithSearch mapContextToProps={(
				{ wasSearched,searchTerm, setSearchTerm, setResultsPerPage,addFilter, setFilter, removeFilter}) =>
				({ wasSearched, searchTerm, setSearchTerm, setResultsPerPage,addFilter, setFilter, removeFilter})}>
				{context => {
					const searchTerm = context.searchTerm;
					const setSearchTerm = context.setSearchTerm;
					const results = context.results;
					context.setResultsPerPage( 20 );
					const wasSearched = context.wasSearched;
					const addFilter = context.addFilter;
					const removeFilter = context.removeFilter;
					const setFilter = context.setFilter;
					addFilter('storeid', storeid);
					addFilter('productqty', {from:1, name:'instock', to: 99999});
					//console.log("results",results);
					return (
						<div>
						{windowWidth>799?
							<p className="h1-responsive" style={{textAlign:'center'}}>Buscar</p>
						:""}

							<ErrorBoundary>
								<Layout
									header={
										<div className="search-style-2">
											<form style={{justifyContent: "center"}} onSubmit={(event) => {
												event.preventDefault();
											}}>
												<input type="text" name="search_input"
													   onChange={e => {
														   setSearchTerm(e.target.value)
													   }}
													   autoComplete={"off"}
													   value={searchTerm}

													   placeholder={getDefValues().searchLabel}/>
											</form>
										</div>

									}
									sideContent={
										<div>
											{wasSearched && (
												<Sorting
													label={"Ordenar Por"}
													sortOptions={buildSortOptionsFromConfig()}
												/>
											)}
											<Facet
												field="minprice"
												label="Precio"
												filterType="any"
												isFilterable={false}
												view={(e) => {
													//console.log("minPrice", e);
													return(
														<fieldset className={"sui-facet"}>
															<legend className={"sui-facet__title"}>
																Precio
															</legend>
															{e.options.map((item) => {
																if(item.count > 0)
																return (
																	<div className={"sui-multi-checkbox-facet"}>
																		<label htmlFor={"minprice_facet_" + item.value.name}
																			   className="sui-multi-checkbox-facet__option-label">
																			<div className={"sui-multi-checkbox-facet__option-input-wrapper"}>
																				<input
																					className="sui-multi-checkbox-facet__option-input-wrapper"
																					key={'minprice_filter_'+item.value.name}
																					id={'minprice_filter_'+item.value.name}
																					type="checkbox"
																					className="sub-menu-checkbox"

																					onChange={(ckb) => {
																						toggleCheckbox(ckb, e, item)
																					}}
																				/>
																				<span className={"sui-multi-checkbox-facet__input-text"} style={{paddingLeft: "10px"}}>{item.value.name}</span>
																			</div>
																			<span className="sui-multi-checkbox-facet__option-count">{item.count}</span>
																		</label>

																	</div>
																)
															})}
														</fieldset>
													)

												}}
											/>
											<Facet
												field="categories"
												label="Categorías"
												filterType="any"
												isFilterable={true}
												view={(e) => {
													//console.log("Categorias", e);
													return(
													<fieldset className={"sui-facet"}>
														<legend className={"sui-facet__title"}>
															Categor&iacute;as
														</legend>
														{e.options.map((item) => {
															return (
																<div className={"sui-multi-checkbox-facet"}>
																	<label htmlFor={"category_facet_" + JSON.parse(item.value).categoryname}
																		   className="sui-multi-checkbox-facet__option-label">
																	<div className={"sui-multi-checkbox-facet__option-input-wrapper"}>
																		<input
																			className="sui-multi-checkbox-facet__option-input-wrapper"
																			key={'categories_filter_'+JSON.parse(item.value).categoryname}
																			id={'categories_filter_'+JSON.parse(item.value).categoryname}
																			type="checkbox"
																			className="sub-menu-checkbox"

																			onChange={(ckb) => {
																				toggleCheckbox(ckb, e, item)
																			}}
																		/>
																		<span className={"sui-multi-checkbox-facet__input-text"} style={{paddingLeft: "10px"}}>{JSON.parse(item.value).categoryname}</span>
																	</div>
																	<span className="sui-multi-checkbox-facet__option-count">{item.count}</span>
																	</label>

																</div>
															)
														})}
														{e.showMore && (
															<span className="sui-multi-checkbox-facet__option-count"  onClick={e.onMoreClick} >+ Ver Más</span>
														)}
													</fieldset>
												)

												}}
											/>
											<Facet
												field="colors"
												label="Color"
												filterType="any"
												isFilterable={true}
												view={(e) => {
													//console.log("Options", e)
													return(
														<>
															<fieldset className={"sui-facet"}>
																<legend className={"sui-facet__title"}>
																	Color
																</legend>
																<div style={{display: 'flex', flexWrap: 'wrap'}}>
																{e.options.map((item) => {
																	//console.log("color", item)
																	return (
																		<div className={"sui-multi-checkbox-facet"}>
																			<input
																				className="sui-multi-checkbox-facet__option-input-wrapper"
																				key={'color_filter_' + JSON.parse(item.value).label}
																				id={'color_filter_' + JSON.parse(item.value).label}
																				type="checkbox"
																				style={{display: "none"}}
																				className="sub-menu-checkbox"

																				onChange={(ckb) => {
																					//console.log(ckb)
																					ckb.checked = !ckb.checked;
																					addOrRemoveColor(colors,item.value)
																					if(ckb.target.checked) {
																						e.onSelect(item.value)
																					} else {
																						e.onRemove(item.value)
																					}
																					//toggleCheckbox(ckb, e, item)
																				}}
																			/>
																			<label
																				htmlFor={'color_filter_' + JSON.parse(item.value).label}
																				className="sui-multi-checkbox-facet__option-label">
																				<img
																					key={"img" + JSON.parse(item.value).label}
																					name={"color_filter_label_" + JSON.parse(item.value).image}
																					id={"color_filter_label_" + JSON.parse(item.value).image}
																					style={{
																						width: "40px",
																						height: "40px",
																						marginLeft: "10px",
																						borderWidth: "1px",
																						borderColor: "red",
																						borderStyle: colors.includes(item.value) ?"solid":"none"
																					}}
																					src={getImagePath(JSON.parse(item.value).image)}
																				/>
																			</label>
																		</div>

																	)
																})}
																</div>
																{e.showMore && (
																	<span className="sui-multi-checkbox-facet__option-count"  onClick={e.onMoreClick} >+ Ver Más</span>
																)}
															</fieldset>
														</>
													)

												}}
											/>

											<Facet
												field="sizes"
												label="Tallas"
												filterType="any"
												isFilterable={true}
												view={(e) => {
													//console.log("Tallas", e);
													return(
														<fieldset className={"sui-facet"}>
															<legend className={"sui-facet__title"}>
																Tallas
															</legend>
															{e.options.map((item) => {
																return (
																	<div className={"sui-multi-checkbox-facet"}>
																		<label htmlFor={"category_facet_" + JSON.parse(item.value).label}
																			   className="sui-multi-checkbox-facet__option-label">
																			<div className={"sui-multi-checkbox-facet__option-input-wrapper"}>
																				<input
																					className="sui-multi-checkbox-facet__option-input-wrapper"
																					key={'categories_filter_'+JSON.parse(item.value).label}
																					id={'categories_filter_'+JSON.parse(item.value).label}
																					type="checkbox"
																					className="sub-menu-checkbox"

																					onChange={(ckb) => {
																						toggleCheckbox(ckb, e, item)
																					}}
																				/>
																				<span className={"sui-multi-checkbox-facet__input-text"} style={{paddingLeft: "10px"}}>{JSON.parse(item.value).label}</span>
																			</div>
																			<span className="sui-multi-checkbox-facet__option-count">{item.count}</span>
																		</label>

																	</div>
																)
															})}
															{e.showMore && (
																<span className="sui-multi-checkbox-facet__option-count"  onClick={e.onMoreClick} >+ Ver Más</span>
															)}
														</fieldset>
													)

												}}
											/>

										</div>
									}
									bodyContent={

										<Results
											style={{display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center', backgroundColor:'white'}}
											resultView={(product) => {

												return(
													<SearchProduct
														key={"searchView-" + product.result.productid.raw}
														product={product.result}
													/>
												)
											}}
										/>
									}
									bodyHeader={
										<React.Fragment>
											{wasSearched && <PagingInfo
												view={(e) => {
													return(
														<text>Mostrando {e.start} de {e.end} para: {e.searchTerm}</text>
													)
												}
												}/>}
											{wasSearched && <ResultsPerPage />}
										</React.Fragment>
									}
									bodyFooter={<Paging />}
								/>
							</ErrorBoundary>
						</div>
					);
				}}
			</WithSearch>
		</SearchProvider>
	);
}
`

**Comment by joemcelroy** [comment]
hey! Have you tried one of the codesandbox examples (https://kdyms.csb.app/) to see if its a problem with our code or your setup? Sounds like something is defocusing the input as you type.
