### ISSUE TITLE
Remove "stable" demos

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#731]
We have the concept of "stable" demos: https://github.com/elastic/search-ui/blob/master/CONTRIBUTING.md#stable-demos.

It is "sandbox" code deployed with 3 different configurations. They are on my personal Netlify account. Every time the "stable" branch is updated, they are automatically deployed.

I think we should destroy all of these.

If we choose to, we could consolidate to 1 stable sandbox demo that is deployed from stable on Vercel, but that is not a must. We could also simply rely on CodeSandbox. That would actually probably be preferable so that we can add helpful development configuration to the sandbox that doesn't get deployed as part of our demo.

My proposal:
- Remove the "stable demos" section from the docs.
- On the main page where we mention a live demo, point to a CodeSandbox demo.
- We can also delete the "stable" branch and remove updating the "stable" branch from the deployment instructions.

After all of that is done, I will delete all of these from Netlify.

**Comment by yakhinvadim** [comment]
> so that we can add helpful development configuration to the sandbox that doesn't get deployed as part of our demo.

Could you explain this part a bit more? Not sure I understand.

**Comment by JasonStoltz** [comment]
Oh I just meant if the sandbox was separate from the demo, then you could put some non-sense things in there that might help with development but you wouldn't want to show in a demo. Like some weird sorting options that cover some edge cases but would muddy up a demo. Or some debugging information, etc.

**Comment by yakhinvadim** [comment]
PR: https://github.com/elastic/search-ui/pull/741

Did everything except for this:
> We can also delete the "stable" branch and remove updating the "stable" branch from the deployment instructions.

The Codesandbox demos will still point at stable branch.

The Netlify demos can be removed once the PR above is merged and new docs are deployed.

**Comment by JasonStoltz** [comment]
I can remove them.

**Comment by JasonStoltz** [comment]
Done.
