### ISSUE TITLE
Add an examples section to the docs

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#733]
Any existing code sandbox examples should be added to an Examples section.

Add examples of common use cases for Search UI:

- [x] - Search as you type
- [ ] - Advanced autocomplete
- [ ] - Using an autocomplete in a page header that links to a SERP

**Comment by yakhinvadim** [comment]
I think I get 1 and 3, but could you expand what you mean by 2?

**Comment by yakhinvadim** [comment]
More examples from thread: https://elastic.slack.com/archives/CDW125ZRQ/p1651758334612439

- Move https://docs.elastic.co/search-ui/guides/customizing-styles-and-html codesandbox to examples
- facets example to visualize disjunctive vs non-disjunctive
- separate global header https://codesandbox.io/s/search-ui-national-parks-example-with-seperate-global-nav-ren2l
- result grouping 
- conditional facets
