### ISSUE TITLE
Missing show less button on FacetViewProps

### ISSUE THREAD

**Issue by MigHerCas** [elastic/search-ui#736]
Hello! We're implementing a search results page, and when trying to collapse the Facet options that have been expanded using `onMoreClick` method along `showMore` property, we wonder which would be the best implementation. So far, we haven't found any way to reset `showMore` back to true, after collapse is triggered.

Thanks in advance.

**Comment by JasonStoltz** [comment]
Yeah, we're missing that right now. This is redundant of this issue so I'm going to close it. https://github.com/elastic/search-ui/issues/642
