### ISSUE TITLE
[Elasticsearch-connector] Cloud Id Support

### ISSUE THREAD

**Issue by joemcelroy** [elastic/search-ui#761]
As a user, I should be able to connect my Search UI application to a cloud instance of Elasticsearch by configuring an Elasticsearch Connector with a Cloud ID, rather than a host URL.
Use Cloud ID as default in example code

**Comment by joemcelroy** [comment]
lifted code from elasticsearch-js https://github.com/elastic/elasticsearch-js/blob/main/src/client.ts#L127-L134

```js
      const { id } = opts.cloud
      // the cloud id is `cluster-name:base64encodedurl`
      // the url is a string divided by two '$', the first is the cloud url
      // the second the elasticsearch instance, the third the kibana instance
      const cloudUrls = Buffer.from(id.split(':')[1], 'base64').toString().split('$')

      opts.node = `https://${cloudUrls[1]}.${cloudUrls[0]}`
      
```

**Comment by joemcelroy** [comment]
Searchkit PR https://github.com/searchkit/searchkit/pull/1128

**Comment by yakhinvadim** [comment]
Search UI PR: https://github.com/elastic/search-ui/pull/780
