### ISSUE TITLE
Organize filter values of the same field as an array of primitive values in the requestAdapter

### ISSUE THREAD

**Issue by wentaoxu415** [elastic/search-ui#763]
**Is your feature request related to a problem? Please describe.**
As of now, the filter values of the same field are organized as an array of objects due to how the [`rollup`](https://github.com/elastic/search-ui/blob/9524308d07164380b53d0ca2f8661454affb0980/packages/search-ui-app-search-connector/src/requestAdapters.ts#L22) function is written in the `search-ui/requestAdatapters.tsx` file. This creates an issue where each filter value gets counted as 1 filter toward Elasticsearch's 32 filters limit and makes it much easier to hit this limit.

As [this section of the App Search's documentation](https://www.elastic.co/guide/en/app-search/current/filters.html#filters-arrays-vs-objects) recommends, the filter values of the same field should be organized as an array of primitive values so that you can have have up to 1024 filter values under the same field and this would still count as 1 filter, which would allow the end-users to construct more complex queries

**Describe the solution you'd like**
Refactor the rollup function in the requestAdapters function to combine filter values of the same field as an array of primitive objects, not as an array of objects.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by joemcelroy** [comment]
Thanks for highlighting @wentaoxu415 ! I will find out the reason why rollup was put into place.
