### ISSUE TITLE
Upgrade react-input-autosize

### ISSUE THREAD

**Issue by spalger** [elastic/search-ui#769]
The latest version of `@elastic/react-search-ui` supports React 17, but the `react-input-autosize` dependency wasn't updated. v3.0.0 is the latest and it's [only real change](https://github.com/JedWatson/react-input-autosize/blob/master/HISTORY.md#v300--2020-12-11) is to support React 17. Could we get an update to remove one more version warning in the Kibana repo?

**Comment by yakhinvadim** [comment]
Thanks for the report, Spencer. I'll bring this up with the team tomorrow.

**Comment by yakhinvadim** [comment]
@spalger How can I reproduce the warning? I tried `yarn kbn bootstrap` but didn't see it there.

**Comment by spalger** [comment]
I had to trigger the warning by upgrading to React 17 in a branch

**Comment by yakhinvadim** [comment]
We plan to release this early next week and then upgrade the dependency in Kibana. I'll post the update here.

**Comment by yakhinvadim** [comment]
[The upgrade](https://github.com/elastic/kibana/pull/135363) didn't go as smoothly as I hoped, we need to dig into TypeScript errors. Ok if we do it next week?

**Comment by spalger** [comment]
Sure thing, thank you

**Comment by spalger** [comment]
Whoops!

**Comment by yakhinvadim** [comment]
@spalger This is done! We updated Search UI in Kibana, it shouldn't import react-input-autosize anymore.

**Comment by spalger** [comment]
Awesome, thank you!
