### ISSUE TITLE
Have a "Default" state as well as an "Initial" state.

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#77]
When initializing a SearchProvider, there are two different scenarios for passing in state.

Default sate: The default state of the application. The default state is the state that is displayed if no request has been made, and the state that the application is returned to after a "reset" action is performed. An example would be setting a default sort on data.

Initial State: The initial state would be used for something like SSR, or pre-loading a previous search state. It would have priority over the Default state, but would be ephemeral, in that if a "reset" action was performed, it would return to the Default State, NOT the Initial State. Another way of thinking about this is the same way we read values from the query string, the query string would be another means of providing an Initial State.

**Comment by JasonStoltz** [comment]
Relates to:
https://github.com/elastic/search-ui/issues/13
https://github.com/elastic/search-ui/issues/14
https://github.com/elastic/search-ui/issues/78

**Comment by constancecchen** [comment]
Does this also relate to #194? I may be misreading, but it feels like it does!

**Comment by JasonStoltz** [comment]
@constancecchen They are two independent concepts, but the code could end up overlapping.

I honestly haven't thought this one through thoroughly. It's basically rethinking how the `initialState` parameter works in the SearchProvider. I suspect there are some additional cases around pre-populating that it may or may not handle.

For instance, if you want to a pre-populate a filter when initializing the page, that's totally possible with `initialState` right now. But what if a user presses a "clear filters" button ... should that filter be unapplied, or should it persist?

If it persists, then that's like the "default state"... i.e., the state you return to if you're starting from the beginning of the flow again. If it does NOT persist, then that's like "initial state", it's like you restored the application to a previous point in time, but it's not the beginning of the flow.

Again, this definitely needs some more thought.

**Comment by JasonStoltz** [comment]
It's totally possible that the `initialState` parameter we have now is totally sufficient and works as expected. In which case we could probably just close this issue. That may eventually be the resolution, but I think we should just give `initialState` one last check to make sure it is useful.

**Comment by constancecchen** [comment]
Ahh okay - I think I see. I sorta see the use case for both a default and initial state, but I'm also inclined to think that an `initialState` that acts as a default state and is both what initially loads and is what gets used on reset/clear is sufficient (I may be totally off-base there, though).

Out of curiosity - do we have a "Clear Filters" button planned for Search UI?

**Comment by JasonStoltz** [comment]
@constancecchen We do not. However, we do have a `clearFilters` action, so we could very easily create one. It's actually the example we use for "Build Your Own Component": https://github.com/elastic/search-ui/blob/master/ADVANCED.md#build-your-own-component
