### ISSUE TITLE
[Elasticsearch-connector] setFilter not working

### ISSUE THREAD

**Issue by llermaly** [elastic/search-ui#777]
**Describe the bug**
The setFilter action is not building the right Elasticsearch queries.

**To Reproduce**

Trigger setFilter for a long field

```
    setFilter("precio", {
      name: "precio",
      from: rangePrices[0],
      to: rangePrices[1],
    });
```

**Expected behavior**
A "range" query should trigger because the filter value is an object, but a term query is triggered instead. Also, the term query throws an error because "term" does not support "name" which is required in setFilter.

**Screenshots**

**Which backends and packages are you using:**
Backend: Elasticsearch
Packages: search-ui-elasticsearchsearch-connector,

**Comment by JasonStoltz** [comment]
Thank you for the bug report. We'll get this fixed shortly.

**Comment by joemcelroy** [comment]
this took longer than expected as was OOO. Challenge here is the different way Searchkit (the SDK which transforms the UI requests into elasticsearch queries) applies filters for range queries when they're facets. Currently its not possible to apply explicit range filters to range facets but it uses the name thats been given to the option.

### Example Facet Configuration
```
{
      visitors: {
        type: "range",
        ranges: [
          { from: 0, to: 10000, name: "0 - 10000" },
          { from: 10001, to: 100000, name: "10001 - 100000" },
          { from: 100001, to: 500000, name: "100001 - 500000" },
          { from: 500001, to: 1000000, name: "500001 - 1000000" },
          { from: 1000001, to: 5000000, name: "1000001 - 5000000" },
          { from: 5000001, to: 10000000, name: "5000001 - 10000000" },
          { from: 10000001, name: "10000001+" }
        ]
      }
}
```

### How to apply the filter

```
    setFilter("visitors", {
      name: "10001 - 100000",
      from: 10001,
      to: 100000,
    });
```

## Applying a range to a field that isn't a facet

With the changes in the attached PR, you will be able to apply filters to the search using `value`, `numeric range` and `date range`, just how you would expect. The important part is that it must not be a facet as the behaviour of applying filters for facets is different. 

```
    setFilter("precio", {
      name: "precio",
      from: rangePrices[0],
      to: rangePrices[1],
    });
```  

I hope this helps when it lands into a release, hopefully this week.
