### ISSUE TITLE
Can we save some own query params when using `trackUrlState` ?

### ISSUE THREAD

**Issue by pudgecit** [elastic/search-ui#787]
Hey guys, I just notice if we put customize query params in url, that would be overridden by `search-ui`
for example, the original url is https://wrjpz.csb.app/app-search?size=n_20_n&filters%5B0%5D%5Bfield%5D=states&filters%5B0%5D%5Bvalues%5D%5B0%5D=California&filters%5B0%5D%5Btype%5D=any 
and we change this to (just add `abc=123`)
https://wrjpz.csb.app/app-search?abc=123&size=n_20_n&filters%5B0%5D%5Bfield%5D=states&filters%5B0%5D%5Bvalues%5D%5B0%5D=California&filters%5B0%5D%5Btype%5D=any
when the page is loaded, the `abc=123` is lost, so is there has a way that could keep our customize query params? Thank you.

**Comment by JasonStoltz** [comment]
No, not yet. Query customization is in our plan to address, we just haven't gotten there quite yet.

**Comment by pudgecit** [comment]
> No, not yet. Query customization is in our plan to address, we just haven't gotten there quite yet.

Thank you for your replying, may I ask one more question? so seems we need to set the `trackUrlState` to the false, and implement the "saving state into url" feature by ourselves, do you think this solution could be work?
1. I found [this answer](https://github.com/elastic/search-ui/issues/534#issuecomment-826858275), and maybe we can save the state in `onSearch` function.
2. and set some initialize states.

but still, worry about if we would miss some area cases.

**Comment by JasonStoltz** [comment]
I unfortunately don't have a good answer for ya here. We don't currently have a way to maintain additional parameters in the URL. I suspect it would not be hard to implement though, our URL tracking logic would simply need to remember what parameters were on the URL prior to taking control, and ensure that they are maintained.

**Comment by JasonStoltz** [comment]
Tracking this work here: https://github.com/elastic/search-ui/issues/790

**Comment by pudgecit** [comment]
Thanks

**Comment by JasonStoltz** [comment]
Answered and closing in favor of tracking the work here: https://github.com/elastic/search-ui/issues/790
