### ISSUE TITLE
Support custom headers in the Elasticsearch API connector

### ISSUE THREAD

**Issue by TomCaserta** [elastic/search-ui#795]
**Is your feature request related to a problem? Please describe.**

I would like to put elasticsearch behind an API gateway that will check for arbitrary headers such as Authorization etc. The `@elastic/search-ui-elasticsearch-connector` unfortunately does not seem to provide any way of adding custom headers to the requests that it makes to the elasticsearch API.

**Describe the solution you'd like**

I would like to be able to add `additionalHeaders` to the `ConnectionOptions` of the `ElasticsearchAPIConnector` constructor which, when a request is made, will add these headers to the requests the connector makes.

**Describe alternatives you've considered**

Proxying the request via node and creating a custom connector ala: 

https://docs.elastic.co/search-ui/api/connectors/elasticsearch#nodejs-integration

However this seems overkill for the usecase I am describing.

**Comment by joemcelroy** [comment]
now released under v1.16.0
