### ISSUE TITLE
Refreshing results not working as expected

### ISSUE THREAD

**Issue by wentaoxu415** [elastic/search-ui#799]
**Describe the bug**
I would like to refresh the results after a user updates a document field so that the refreshed results can reflect the updates. To trigger a refresh, I am calling the action`setSearchTerm(resultSearchTerm, {shouldClearFilters: false}` with several seconds delay using debounce so that the Elastic index get through its refresh interval. 

My expected behavior was that this should fetch the updated document, however, the retrieved documents are stale and do not reflect the updates. Meanwhile, refreshing the page results in fetching the updated document.

**Expected behavior**
Calling `setSearchTerm(resultSearchTerm, {shouldClearFilters: false}` with several seconds delay should fetch the recently updated documents.

**Screenshots**

**Which backends and packages are you using:**
Backend: App Search
Packages: search-ui `1.10.0`

**Comment by yakhinvadim** [comment]
Hm, could you try adding `cacheResponses: false` to the connector configuration, like [here](https://docs.elastic.co/search-ui/api/connectors/app-search)? Not confident it'll help, but worth a try.

**Comment by wentaoxu415** [comment]
Thanks for the suggestion @yakhinvadim! It indeed turned out to be the `cacheResponses` value in the config and setting this false fixed my issue.

Closing the issue now as it is resolved
