### ISSUE TITLE
Add the ability to override URLManager's methods

### ISSUE THREAD

**Issue by yakhinvadim** [elastic/search-ui#808]
Specifically the ability to override our [paramsToState](https://github.com/elastic/search-ui/blob/master/packages/search-ui/src/URLManager.ts#L66) and [stateToParams](https://github.com/elastic/search-ui/blob/master/packages/search-ui/src/URLManager.ts#L84) default behavior.

Issue forked from https://github.com/elastic/search-ui/issues/790

**Comment by joemcelroy** [comment]
this has been implemented. See documentation https://docs.elastic.co/search-ui/api/core/configuration#routing-options
