### ISSUE TITLE
When running `yarn` in the `app-search-reference-ui-react-master` folder according to the `elasticsearch` documentation, there are a lot of warnings

### ISSUE THREAD

**Issue by namespace-Pt** [elastic/search-ui#814]
I'm trying to build a simple search engine using a self-managed `elasticsearch` and `search-ui`. After downloading the source code, I found there are a lot of warnings when running `yarn` under the project folder, are they expected?
![image](https://user-images.githubusercontent.com/61188463/180591818-6ae5dfb2-c565-485e-8ed2-4c0c751d4f88.png)

**Comment by JasonStoltz** [comment]
Many of these errors may be related to our old version of rc-pagination: https://github.com/elastic/search-ui/issues/598.
