### ISSUE TITLE
Why do you need to enter the password after you cooperate? Thank you

### ISSUE THREAD

**Issue by brucelee19960413** [elastic/search-ui#829]
![issue](https://user-images.githubusercontent.com/94457606/181916480-75d902cd-e06e-4a8f-9e15-221324bad9da.png)
I want to open it up to all users. This is a public search！
I want to open it up to all users. This is a public search
I want to open it up to all users. This is a public search
![1e30ced25226806bf65eca46d47d9e8](https://user-images.githubusercontent.com/94457606/181916500-dc929f88-038e-48e4-834c-571560bd326b.png)

**Comment by joemcelroy** [comment]
Hi there,

Which connector are you using? Likely the search API you're calling requires basic authentication credentials. Closing as it isn't related with search-ui and more down to your setup.
