### ISSUE TITLE
Creating a Kibana discover style field value filter

### ISSUE THREAD

**Issue by process0** [elastic/search-ui#849]
When exploring data in Kibana, it is possible to select the value of a field in a document and filter on it, e.g. `status: Ready`. I would like to recreate this capability with custom components. Ideally, I would like to have a drop down selecting the field and an input to specify the value, all tracked with URL states, so I can deep link within my application.

The only solution I can think of, without having to specify every field, is to fetch the index mapping.  Is doing this possible with this library?  I'm using the AppSearchAPIConnector.

**Comment by JasonStoltz** [comment]
There's nothing in the AppSearchAPIConnector that would support that. You'd have to make a separate API call to fetch all available mappings directly [using the App Search API](https://www.elastic.co/guide/en/app-search/current/schema.html#schema-read). I'd do that on page load and use that to build that filter component you describe.
