### ISSUE TITLE
Geo-Bounding Box Query in App Search

### ISSUE THREAD

**Issue by ethanhoroschak** [elastic/search-ui#855]
**Is your feature request related to a problem? Please describe.**
We need to Geo-Bounding Box Query to filter results in a certain area and would like to use App Search to optimize our search experience.

**Describe the solution you'd like**
Addition of Geo-Bounding Box Query functionality to App Search api.

**Describe alternatives you've considered**
We've built our search using ElasticSearch api and have implemented Geo-Bounding Box Query, however, we'd like to use App Search for the search tuning features and ease of use .

**Comment by JasonStoltz** [comment]
Hey @ethanhoroschak, I'll pass this request onto the App Search team. It's something that would need to be implemented there, not in this search-ui library. Thanks for dropping this issue!
