### ISSUE TITLE
typescript complains when passing cacheResponses to the connector

### ISSUE THREAD

**Issue by gerardosabetta** [elastic/search-ui#860]
**Describe the bug**
The type `AppSearchAPIConnectorParams` Does not include `cacheResponses` nor any of the props that get passed to the instantiated `ElasticAppSearch`.

**Expected behavior**
type `AppSearchAPIConnectorParams` should `&` the props that `createClient` allow you to pass in

**Screenshots**

![image](https://user-images.githubusercontent.com/55319644/192346450-6e15642b-21ea-43ef-8beb-2cb5a5b1f629.png)

**Which backends and packages are you using:**
Backend: [App Search]
Packages: [react-search-ui, search-ui-app-search-connector, etc.]

**Comment by JasonStoltz** [comment]
Hey, good catch! This should be a quick fix.

**Comment by gerardosabetta** [comment]
Thanks @joemcelroy !
