### ISSUE TITLE
Search Operator Support

### ISSUE THREAD

**Issue by mwinter80** [elastic/search-ui#862]
Is it possible to get basic search operator support as with a (simple) query string?:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

I can see when I print the request that by default quite a wide net is cast with several multi_match queries. If there is no simple way to configure the connector to use a query string query, is there an advised best practice for altering the request to provide support for search operators.

Thanks in advance

**Comment by joemcelroy** [comment]
hey @mwinter80 - For the elasticsearch connector you can override the query clauses it uses. See documentation for more information https://docs.elastic.co/search-ui/api/connectors/elasticsearch#customise-the-elasticsearch-request-body
