### ISSUE TITLE
How I can apply filter with contain operation instead of full-match

### ISSUE THREAD

**Issue by netphager** [elastic/search-ui#871]
Hello, for example if I have a string like "My name is John" I would like to apply a filter that checks if the string contain John, curretly the filters are working with full match only.

I'm using addFilter() method for adding filters.

**Comment by JasonStoltz** [comment]
Unfortunately can't do a contains filter with Search UI.

Are you using the App Search connector or the Elasticsearch connector?

**Comment by netphager** [comment]
Hi, thanks for the reply I'm using Elasticsearch connector

**Comment by netphager** [comment]
Hey, guys still didn't answer to my question ?
