### ISSUE TITLE
ElasticsearchAPIConnector with user:password

### ISSUE THREAD

**Issue by orenorgad** [elastic/search-ui#872]
How should I use the elastic credentials approach with ElasticsearchAPIConnector?
When trying to set -> host: https://user:pass@hostname I'm getting the following error:

<div class="sui-search-error">An unexpected error occurred: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: https://user:pass@hostname/catalog/_search</div>

I'm not using elastic cloud so I don't have an API key, but I also don't want to leave my elasticsearch open to public without authentication. What should I do?

Thanks,

**Comment by joemcelroy** [comment]
Hi there!

You could build an API that sits in between the frontend and Elasticsearch. Elasticsearch <> API having limited connection

https://docs.elastic.co/search-ui/guides/nextjs-integration
