### ISSUE TITLE
How can i add filter on autocompleteResults elastic search-ui react js

### ISSUE THREAD

**Issue by fkvivid** [elastic/search-ui#875]
first my SearchProvider config have initialState filters its look like
```
initialState: {
    filters: [
        {
          field: 'category',
          values: ['shoes'],
          type: 'all',
        },
    ],
},
```

In my question when i'm typing some text in searchbox autoCompleteResuts give me values without my initialState filters so how can i add filter on autocompleteResults 

here is onsearch
<img width="673" alt="Screen Shot 2022-10-12 at 17 17 58" src="https://user-images.githubusercontent.com/73453260/195303346-97eec5bc-f577-441b-aa5f-4f3d53dfe13b.png">

i just want something like this thank you 😁

```
autocompleteQuery: {
    results: {
        initialState: {
            filters: [
                {
                  field: 'category',
                  values: ['shoes'],
                  type: 'all',
                },
            ],
        },
    },
  }
```

**Comment by JasonStoltz** [comment]
`autocompleteQuery` is the right place to configure this, but try doing it without "initialState".

```
autocompleteQuery: {
    results: {
            filters: [
                {
                  field: 'category',
                  values: ['shoes'],
                  type: 'all',
                },
            ],
    },
  }
```

**Comment by fkvivid** [comment]
thank you i really appreciate you help @JasonStoltz
