### ISSUE TITLE
How to connect to azure elastic search with the custom connector?

### ISSUE THREAD

**Issue by ZakKa89** [elastic/search-ui#878]
I have the following code (values simplified for security reasons)

```
import ElasticsearchAPIConnector from '@elastic/search-ui-elasticsearch-connector'

const connector = new ElasticsearchAPIConnector({
  // host: 'https://blabla.westeurope.azure.elastic-cloud.com:443',
  cloud: {
    id: 'nedappredev_elasticsearch:base63encodedstring'
  },
  index: 'products',

```

But I can't connect like this. With the Javascript API, I simply pass the id and password, but the searchConnector doesn't allow me to use password authentication. How can I use a password? Or do I have to setup an API key in this case, even though it's optional?

## Working example of js api connection
 How we successfully connect to the azure elastic search instance with the JS API (works like a charm):

```
import { Client } from '@elastic/elasticsearch'

const client = new Client({
  cloud: { id: process.env.ELASTIC_CLOUD_ID },
  auth: {
    username: 'elastic',
    password: process.env.ELASTIC_PASSWORD
  }
}
```

**Comment by joemcelroy** [comment]
Hi there,

API Key is optional in the configuration but that depends how you're connecting to Elasticsearch. I strongly advise if you're using Elastic cloud, you setup a read only API key for use to connect.

**Comment by ZakKa89** [comment]
Ok, thanks I'll try with an API Key. Still have questions...

1. You state "depends how you're connecting to ElasticSearch" So on what does it depend? 

2. Why can't I use a password like with the Javascript API of elastic-search? Security concern?

**Comment by joemcelroy** [comment]
Hey!

> * You state "depends how you're connecting to ElasticSearch" So on what does it depend?
> *

You could be hosting elasticsearch other than on Elastic cloud. It could be an on-premise instance? 

> Why can't I use a password like with the Javascript API of elastic-search? Security concern?

If the search request is made through the browser directly to elasticsearch, this password will be exposed from within the browser for anyone to see
