### ISSUE TITLE
[feature request] Randomization of results that are matching criteria

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [elastic/search-ui#880]
Hello!

We use Elastic for a bunch of things in our application, one of the use cases is to show a 'more products like this' section, we apply some filters, but unfortunately the order of the products always returns the same, even though we want the matching products to show up in a random order.

In order to resolve this without causing type issues, we are currently applying the following adjustment to the requestBody through the ElasticConnector. Not ideal, but since `queryConfig.sortField` is just a string, we prevent type issues. 

```
      if (queryConfig.sortField === 'random') {
        requestBody.sort = {
          _script: {
            script: 'Math.random()',
            type: 'number',
            order: 'asc',
          },
        };
      }
```
      
Do you consider a 'rand' sort direction option within the SortOption solution to be something useful within the library itself? I'm happy to create a PR but let me know if you are interested first

**Comment by ehibes** [comment]
I need the same feature. @RobbyUitbeijerse Is there another way to fetch random results ?
