### ISSUE TITLE
[Elasticsearch Connector] Queries with applied filters don't require the query to match

### ISSUE THREAD

**Issue by asgorobets** [elastic/search-ui#884]
### Description
When using Search UI with Elasticsearch Connector to build a search experience with keyword search, I've noticed that some fltered queries return more results than the unfildered (both have same keyword query applied). With some investigation I found the issue.
The problem is when using **bool** query with **should** match clauses + filter

According to [docs](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/query-dsl-bool-query.html):

> You can use the minimum_should_match parameter to specify the number or percentage of should clauses returned documents must match.
> If the bool query includes at least one should clause and no **must** or **filter** clauses, the default value is 1. Otherwise, the default value is 0.

In our case we have 4 should clauses from [MultiMatchQuery](https://github.com/searchkit/searchkit/blob/next/packages/searchkit-sdk/src/query/MultiMatchQuery.ts) + one filter which makes minimum_should_match  = 0 (default). This effectively makes any keyword search return just the fltered results and ignores the keyword

**Steps to reproduce the behavior**

1. Configure search ui with Elasticsearch Connector with a test index with full text search data and filterable keyword fields. For example title, description and page_type (article / page)
2. Make a search by keyword and observe number of results matching
3. Make a search with same keyword + filter and observe results matching might be bigger than in step (2). Even though a filter should limit results, not expand them

**Expected behavior**
Expected results is that keyword search should match at least one keyword, but more keywords is better, and this should not be dependent on fiters applied.

**Possible solution**
In order to fix this issue, one should specify minimum_should_match greater than 0. This is certainly possible to workaround in postProcessRequestBodyFn (second argument passed to connector), but the default experience is broken.
Maybe Search UI can apply a minimum_should_match = 1 by default for all queries, and let the user override it if desired in connector settings or even document how to do it in postProcessRequestBodyFn

Example code:
```
const postProcessRequestBodyFn = (requestBody) => {
  if (requestBody?.query?.bool) {
    requestBody.query.bool.minimum_should_match = 1;
  }
  return requestBody;
};
```

**Which backends and packages are you using:**
Backend: Elasticsearch 8.4
Packages: react-search-ui 1.18.0, search-ui-elasticsearch-connector 1.18.0

**Comment by joemcelroy** [comment]
Hi @asgorobets 

Agreed and its been highlighted before. Thanks for suggesting a workaround using minimum should match.

The path we want to do is:
- update Searchkit (what elasticsearch-connector uses behind the scenes) to use just a single multi-match best fields clause and keep things simple. 
- Better support on overriding the query part of the query DSL rather than through `postProcessRequestBodyFn`

**Comment by joemcelroy** [comment]
Created a ticket for this https://github.com/elastic/search-ui/issues/887
