### ISSUE TITLE
Correct release version 1.8.2?

### ISSUE THREAD

**Issue by rutger-gerritsen** [elastic/search-ui#885]
@joemcelroy The version went from v1.18.1 to v1.8.2. Should it be v1.18.2? Or did I miss something?

The Enterprise Search team at Elastic maintains this library and are happy to help. Try posting your question to the [Elastic Enterprise Search](https://discuss.elastic.co/c/enterprise-search/84) discuss forums. Be sure to mention that you're using Search UI and also let us know what backend your using; whether it's App Search, Site Search, Workplace Search, Elasticsearch, or something else entirely.

**Comment by joemcelroy** [comment]
This is my fault, typo on the version and due to the process being manual, was missed. Just pushed 1.18.2 and going through the steps to rectify. 

Thanks so much for highlighting this!

Joe
