### ISSUE TITLE
[Elasticsearch-connector] Simplify the query relevance clauses

### ISSUE THREAD

**Issue by joemcelroy** [elastic/search-ui#887]
Currently the Clauses uses the Searchkit OOTB which is a complex number of multi and prefix clauses. We should simplify this to  
just using the multi-match clause. We should provide better documentation or better API support for customers to override the query.

**Comment by asgorobets** [comment]
This is still important to fix, as current implementation hides a lot of details that make filters unusable, more info here https://github.com/elastic/search-ui/issues/884
