### ISSUE TITLE
Can't search for fields of type 'keyword':   Searchkit error when search_fields has a field of type keyword in searchQuery

### ISSUE THREAD

**Issue by ZakKa89** [elastic/search-ui#888]
**Describe the bug**

- Once you add a field to search_fields object in searchQuery, that is of type 'keyword', a server error occurs and nothing is returned (empty object). 
- Searching for fields of type 'text' works fine
- Note that the autocomplete doesn't exactly have the same issue. The autocomplete gives me the responseState correctly, just with 0 suggestions
- Note that I wanted to see if I could get any other type of error by simply removing the index and the same error is thrown. We really need better error handling. 

**The server error (nextJS serverside) **
```
error - TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.getFacetsFromResponse (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/core/FacetsFns.js:42:36)
    at ElasticSearchResponseTransformer.transformResponse (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/transformers/index.js:61:27)
    at SearchkitRequest.<anonymous> (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/index.js:126:37)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zakaria/Repos/nedap_portal/portal/node_modules/@searchkit/sdk/lib/cjs/index.js:15:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/api/search'
}
```
**To Reproduce**

1. Setup with nextJs like this https://docs.elastic.co/search-ui/guides/nextjs-integration
2. put an index in elasticSearch like so:

```
PUT products
{
    "mappings": {
      "dynamic":"strict",
        "properties": {
            "itemType": {
                "type": "keyword"
            },
            "productId": {
                "type": "keyword"
            },
            "productTitle": {
                "type": "text"
            }
        }
    }
}

```

3. push data in elasticSearch
4. setup the serach-ui config like this:

```
  searchQuery: {
    search_fields: {
      productId: {},
    },
```

**Expected behavior**

either:
- A search that still works, even though it will only return exact matches. 
- if type 'keyword'  is not supported, give me a correct error message in the response

**Screenshots**

**Which backends and packages are you using:**
Backend: [Elastic Search cloud]

Using the next.js setup from the docs: 

```
    "@elastic/react-search-ui": "^1.17.1",
    "@elastic/react-search-ui-views": "^1.17.1",
    "@elastic/search-ui": "^1.17.1",
    "@elastic/search-ui-elasticsearch-connector": "^1.17.1",
```

**Comment by ZakKa89** [comment]
Note that I wanted to see if I could get any other type of error by simply removing the index from elasticSearch and the same error is thrown. We really need better error handling.

**Comment by JasonStoltz** [comment]
> if type 'keyword' is not supported, give me a correct error message in the response

I think this is the path we'd take here. Thank you for raising this bug.

**Comment by joemcelroy** [comment]
Not a solution but a workaround is to override the default query https://docs.elastic.co/search-ui/api/connectors/elasticsearch#customise-the-elasticsearch-request-body

Searchkit will generate a default query which fails when you use keyword fields. With overriding the query, this will allow you to override and use something more simple like multi_match https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html

**Comment by ZakKa89** [comment]
My 'workaround' was switching to App Search. Search-UI simply works best with App Search at the moment.

**Comment by JeroenAdam** [comment]
I got the same issue when trying to add a runtime field of type keyword to the search fields.
The error is a 400 Bad Request (from ES) with response:

"reason": "failed to create query: Can only use phrase prefix queries on text fields - not on [flattopics] which is a runtime field of type [keyword]"

**Comment by joemcelroy** [comment]
searchable fields should be used with text type fields. If you do need to use keyword fields, I suggest you control the query performed to elasticsearch. See documentation for this. https://docs.elastic.co/search-ui/api/connectors/elasticsearch#customise-the-elasticsearch-request-body

**Comment by ZakKa89** [comment]
The imain ssue isn't that we can only use search UI with text type fields. The package should give a proper error (see my expected behaviour)

I've modified the request body to implement many features, but it shouldn't be given as a solution IMO. It's fairly complex and not well documented.

**Comment by joemcelroy** [comment]
thats fair feedback and we should give better error messaging when this happens.
