### ISSUE TITLE
How to add global filter in config?

### ISSUE THREAD

**Issue by ZakKa89** [elastic/search-ui#890]
# How to add global filter in config?

https://docs.elastic.co/search-ui/api/core/configuration#filters-global-filters

The docs mention global filters, but doesn't mention how. It just shows the filters object. I can add filters fine in the `searchQuery` object, that works great, but I believe that isn't what is meant with global filters? 

I'm asking because I'm looking for a way to add predefined filters for both onSearch results and onAutocomplete suggestions. 

I am using the elasticsearch connector

**Comment by Mites88** [comment]
You put it on  `searchQuery` property in config object, ie

```js
    searchQuery: {
      ...otherOpts,
      filters: [
        { field: 'places.keyword', type: 'any', values: ['Italy'] },
      ],
    }
```

**Comment by ZakKa89** [comment]
In that case it's not what I'm looking for. I was already aware I could add filters to the searchQuery, but I was hoping that with 'global' it will also have an effect on the autocomplete.

**Comment by Mites88** [comment]
I totally missed that from your original post. 

Unfortunately I can't help with that one. Will be watching this thread.

**Comment by JasonStoltz** [comment]
>'global' the docs just mean that they user does not apply them

Yes. Another term for it could be "base filters".
