### ISSUE TITLE
What is the difference between App Search and Elastic Search?

### ISSUE THREAD

**Issue by ZakKa89** [elastic/search-ui#893]
# Why am I asking this?
I'm thinking of switching to App Search because the ElasticSearch connector has too many issues (see all the bugs I posted). 

# What is the Difference between App Search and Elastic Search (within the context of search-ui)? 

I googled, I read your documentation, but can't find an answer to this question. Your documentation states that App Search makes things easier, and that Elastic Search can be more flexible. But that's very vague:
https://docs.elastic.co/search-ui/tutorials/connectors

# What are the limitations of App Search?
This is the most important part. I want to be able to create multiple indexes, and I have to push data into it from multiple sources.

**Comment by ZakKa89** [comment]
From what I understand, the idea behind App Search is to give developers a more complete, full-stack solution with UI. Instead of just backend (because it works together with search-ui). However, if search-ui also supports Elastic Search, I don't see the difference anymore except for that the App Search connector is stable.

**Comment by ZakKa89** [comment]
Some differences I've found: 

- App Search only supports lowercase/snake_case fields.
- With App Search, you can upload documents without setting up an index and mapping first. It will do so automagically
- With App search, instead of mappings there is a schema. Like mentioned in the previous point, this schema will be generated automagically from the data. However it is still possible to create a schema yourself.

**Comment by JasonStoltz** [comment]
It's a big topic. The big thing you get with App Search is the ability to configure relevance through a UI dashboard. A business user can customize stuff like synonyms, pinned results, boosts, etc all without touching code. The App Search Search API ultimately generates an Elasticsearch Search API call for ya. The main drawback you get with that is that it constrains what query features you can actually use.

You can almost think of App Search as a layer on top of Elasticsearch.

The feature sets should eventually converge and the idea of "App Search" will eventually go away, but we're not there yet. It'd be a gradual process over the course of multiple future releases.

I can't enumerate all of the differences here, but I'm happy to answer more specific questions.

**Comment by ZakKa89** [comment]
Amazing answer thank you!

**Comment by JasonStoltz** [comment]
@ZakKa89 Features as in features of the Elasticsearch API features. For instance, if you have App Search setup, you can use the explain API to see what the underlying Elasticsearch API call will look like: https://www.elastic.co/guide/en/app-search/current/search-explain.html.

That's your constraint! So if you wanted to do something other than a `multi_match`, or adjust the fuzziness, or if you wanted to use two query strings on different fields, you can't do it! Or if, for example, you wanted to do some advanced aggregations, you just can't do it. The App Search API translates `facets` into a very specific terms aggregation.
