### ISSUE TITLE
SearchProvider does not respond to a driver change

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/search-ui#894]
My application runs in 2 modes - authenticated and non-authenticated.  Once a user logs in , a new signed search key gets created and the driver must be updated on SearchProvider.   Currently, when I update the `driver` property, nothing happens so I am currently working around by [forcing a remount of the SearchProvider component](https://stackoverflow.com/questions/35792275/how-to-force-remounting-on-react-components).

**Comment by PhaedrusTheGreek** [comment]
I also should point out that I just noticed there may be some breaking change / performance hit with a solution here, since the driver itself seems to update fairly frequently.  In the meantime I'm only going to force the remount when the engine itself changes.

**Comment by TomCaserta** [comment]
Also looking for this behaviour to be changed or at least configurable. My usecase is that I need to reload the `headers` passed through to the driver periodically to update an authentication token. Maybe for my usecase theres a better solution though but still I'd expect any driver change to actually change the underlying driver in the SearchProvider.
