### ISSUE TITLE
Parameter default_operator

### ISSUE THREAD

**Issue by jesielviana** [elastic/search-ui#900]
I need to put the default_operator query parameter, but the connector doesn't have the feature.

See more about query parameters: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-search.html#search-search-api-query-params

**Comment by joemcelroy** [comment]
I would advise you to use the [elasticsearch request body function](https://docs.elastic.co/search-ui/api/connectors/elasticsearch#customise-the-elasticsearch-request-body) to modify the elasticsearch request for these parameters.
