### ISSUE TITLE
snippet / highlighting

### ISSUE THREAD

**Issue by tavaradhan** [elastic/search-ui#906]
hi,
I am experimenting with ElasticsearchAPIConnector using SearchUI on a small document base. I want to get the full field returned with highlights. The field is less than 1000 characters long. I tried using highlight with number_of_fragments as zero, but I seem to not have success in getting the full field. I see that if i include snippet in the result_fields (holdover from using appsearch connector, which i am trying to replace with the ElasticsearchAPIConnector), I get highlighted snippet, but it is truncated (whereas when using appsearch, I set size as 900 and was able to get the full field back with highlights).

If I go to dev console in kibana, and query with a search term and highlight with number_of_fragments =0, then I get the proper result in kibana dev console (i.e. highlighted full field is returned along with raw field)

any pointers? @JasonStoltz 

warning: I am a newbie at this, and hence, might be making simple/newbie type mistakes too.

thanks
varadhan

**Comment by joemcelroy** [comment]
Hi there, I would advise you to use the [customise request body function](https://docs.elastic.co/search-ui/api/connectors/elasticsearch#customise-the-elasticsearch-request-body) and update the highlighting options yourself as a workaround.

Elasticsearch-connector uses [searchkit](www.github.com/searchkit/searchkit) under the hood and would need a PR to update the options there.
