### ISSUE TITLE
Nested objects are not rendered when `elasticsearch-connector` is used

### ISSUE THREAD

**Issue by efegurkan** [elastic/search-ui#907]
**Is your feature request related to a problem? Please describe.**
Nested objects are not rendered by Search UI when `elasticsearch-connector` is used. I created two demo applications using the same index, one with `app-search-connector` and other with `elasticsearch-connector`.

![Screenshot 2022-12-14 at 15 34 33](https://user-images.githubusercontent.com/1410658/207627012-52d2a145-8480-454d-9eab-704f38a481bc.png)

When `app-search-connector` is used search UI is able to render the same index, but missing subfields

![Screenshot 2022-12-14 at 15 34 36](https://user-images.githubusercontent.com/1410658/207627642-a712c0b5-7a1b-4b7f-a63a-d38476200e9d.png)

It would be nice to have both are working the same way.

**Additional context**
This came as an investigation from a user support request.
```
"@elastic/search-ui-app-search-connector": "^1.18.3",
"@elastic/search-ui-elasticsearch-connector": "^1.18.3",
```

Index created by following on Kibana Dev Tools
```
PUT search-ui-test
{
  "mappings": {
    "properties": {
      "nested_field":{
        "type": "nested",
        "properties": {
          "field1":{
            "type":"keyword"
          },
          "field2":{
            "type":"text"
          }
        }
      },
      "keyword_field":{
        "type":"keyword"
      }
    }
  }
}

POST search-ui-test/_doc
{
  "nested_field":{
    "field1":"test1",
    "field2":"test2"
  },
  "keyword_field":"test"
}
```

Document on index viewed on Document viewer on Enterprise Search Content plugin
![Screenshot 2022-12-14 at 15 54 39](https://user-images.githubusercontent.com/1410658/207629199-44f6a234-0b61-42c5-bf8f-dd13a53ff6c7.png)

**Comment by JeroenAdam** [comment]
I'm having the same issue, using @elastic/search-ui-elasticsearch-connector

I'm having this object as a result from a query (copied from Kibana):

`          "topics" : [
            {
              "id" : 1,
              "label" : "Reading",
              "creationDate" : "2023-06-21"
            }
`

Shown in search UI as:

topic[object Object]

**Comment by JeroenAdam** [comment]
I've tried setting the fieldtype to flattened and reindexed, type shown as 'flattened' in Kibana, still shown in search UI as:
"topic": [object Object]

So the goal is to get the property 'label' from this object to show up in the UI.

Hello @joemcelroy, any suggestions?

**Comment by JeroenAdam** [comment]
I tried setting a runtime field definitions in the index mappings and it works for a regular search query (Kibana), now search UI dediced to ignore this field, it does not show up in the UI.
GET /resource/_mapping
`
{
  "resource" : {
    "mappings" : {
      "runtime" : {
        "flatsubject" : {
          "type" : "keyword",
          "script" : {
            "source" : "emit((doc['topics.label.keyword'].value))",
            "lang" : "painless"
          }
        }
      },
      "properties" : {
      ...
    }
  }
}
`

GET /resource/_search 
`
{
        "query": {
            "term": {
                "flattopics": "Reading"               
            }
        }
}
`
This last request works fine. The runtime field does its job.

Search UI decided not to show this field in the results.

**Comment by sebeliasson** [comment]
I also ran into this now. Any ideas on solution?

**Comment by darkread** [comment]
I build a app,user ES+Fscrawler+SearchUI，Fscrawler results is a nested object,I can make it with Search UI v1.8.0
but failed with v1.27.0(current version)
Is anyone fix it or give me a solution,please?

**Comment by darkread** [comment]
[Search UI v1.8](https://github.com/elastic/search-ui/tree/1.8)
I can insert map code line 39 of [buildState.js](https://github.com/elastic/search-ui/blob/1.8/examples/elasticsearch/src/buildState.js) to sovle it.
like this
![image](https://github.com/elastic/search-ui/assets/4532430/067db366-c52b-4f1f-a3fc-69b44863ee42)

**Comment by sarahg** [comment]
We need to be able to query subfields in order to work around an issue with the Web Crawler's default field mappings (see [related forum post](https://discuss.elastic.co/t/web-crawler-fields-indexed-without-position-data-cannot-run-phrasequery/366758/2)). Currently we can't run a query with spaces in it against any of the default fields created by the crawler because they get set up with mapping like this:

```
"body_content": {
   "type": "text",
   "index_options": "freqs"
}
```

The suggested workaround was to query a subfield within `body_content` (`body_content.stem`).

From this issue, it seems like it's not possible to query subfields with `search-ui-elasticsearch-connector`, is that accurate?
