### ISSUE TITLE
Document support (or lack of) for SSL-enabled Elasticsearch clusters that use custom certs

### ISSUE THREAD

**Issue by ppf2** [elastic/search-ui#908]
When connecting Search UI with an Elasticsearch cluster that is HTTPs enabled, it doesn't look like we support custom/self-signed certificates today.  The user will have to add the CA cert to root cert where the Search UI application is running.  It will be helpful to document this limitation/workaround.

**Comment by jzsplk** [comment]
have the same issue, It will be helpful to document this limitation/workaround.
