### ISSUE TITLE
Example links in documentation are broken. 

### ISSUE THREAD

**Issue by jackfrosty908** [elastic/search-ui#914]
**Describe the bug**
When clicking on the Example links in the documentation, they will take you codesandbox.io. However code sandbox shows the following error upon loading `INVALID_REQUEST - No commit found for SHA: master`

**To Reproduce**

1. Go to the  [examples](https://github.com/elastic/search-ui#examples) section of the wiki
2. Click on any of the links
    - [Search UI with Elasticsearch](https://docs.elastic.co/search-ui/tutorials/elasticsearch)
    - [Search UI with Elastic App Search](https://docs.elastic.co/search-ui/tutorials/app-search)
    - [Search UI with Elastic Workplace Search](https://docs.elastic.co/search-ui/tutorials/workplace-search)
4. You will be redirected to codesanbox.io
5. See error

**Expected behavior**
Links navigate user to working examples. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58316526/211409113-64e01a67-e4f0-45fa-b5d6-fa7712f60e58.png)

**Comment by joemcelroy** [comment]
thanks for the spot and PR to fix!

**Comment by JeroenAdam** [comment]
I still get the error as reported here, I went to https://docs.elastic.co/search-ui/overview and tried launching the demo for Elasticsearch.

**Comment by joemcelroy** [comment]
> I still get the error as reported here, I went to https://docs.elastic.co/search-ui/overview and tried launching the live demo for Elasticsearch. Currently links to https://codesandbox.io/s/github/elastic/search-ui/tree/master/examples/sandbox?from-embed=&initialpath=/elasticsearch&file=/src/pages/elasticsearch/index.js
> 
> I tried replacing 'master' with 'main' but then there is an error 'Could not fetch dependencies'.

thanks for reminding! our docs build failed. It now updated. thanks for flagging :)
