### ISSUE TITLE
addFilter with "any" type - not working?

### ISSUE THREAD

**Issue by lynch-a** [elastic/search-ui#922]
(i'm using Search UI with an ElasticSearchAPIConnector and VueJS)

hi, i'm trying to use Search UI to generate a query that lets me return results with something like a "WHERE IN" type sql query. I think I need to submit a query with a filter similar to this:

```
{
  "query" : {
    "bool" : {
      "filter" : {
        "terms" : {
          "id" : [1, 2, 3]
        }
      }
    }
  }
}
```

I am having trouble getting Search UI to generate this type of query. I am trying to use the `addFilter()` action with the `any` FilterType to perform this filtering:

`driver.addFilter("id", [1, 2], "any");`

when I run the above addFilter() and print out the driver state, everything looks alright (to my inexperienced eyes):

```{
    "current": 1,
    "filters": [
        {
            "field": "id",
            "values": [
                1,
                2,
            ],
            "type": "any"
        }
    ],
    "resultsPerPage": 20,
    "searchTerm": "",
    "sortDirection": "asc",
    "sortField": "",
    "sortList": null,
    "autocompletedResults": [],
    "autocompletedResultsRequestId": "",
    "autocompletedSuggestions": {},
    "autocompletedSuggestionsRequestId": "",
    "error": "",
    "isLoading": false,
    "facets": {
        ...snip...
    },
    "requestId": null,
    "results": [],
    "resultSearchTerm": "",
    "totalPages": 0,
    "totalResults": 0,
    "pagingStart": 1,
    "pagingEnd": 0,
    "wasSearched": true,
    "rawResponse": null
}
```

however, the search query that is sent to the backend with this state doesn't return any results:

```
{
    "aggs": {
        "facet_bucket_all": {
            "aggs": {
                ...snip...
            },
            "filter": {
                "bool": {
                    "must": []
                }
            }
        }
    },
    "size": 20,
    "_source": {
        "includes": [
            ...snip...
        ]
    },
    "query": {
        "bool": {
            "filter": [
                {
                    "bool": {
                        "filter": [
                            {
                                "term": {
                                    "id": 1
                                }
                            },
                            {
                                "term": {
                                    "id": 2
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "from": 0,
    "sort": [
        {
            "_score": "desc"
        }
    ]
}
```

if I set the filter as: `driver.addFilter("id", [1], "any");` it works fine and the query returns result where the "id" field matches "1". why does it seem like the "any" clause in my `addFilter()` is being ignored and not generating the right filter query when I am trying to match against multiple id  values?

thanks for any insight

**Comment by joemcelroy** [comment]
thats interesting! Yeh I see the bug:

For all filters that are not facets, we use [Searchkit's Filter](https://github.com/elastic/search-ui/blob/main/packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts#L148). The filter [doesn't support "any"  concepts](https://github.com/searchkit/searchkit/blob/v3.0.0/packages/searchkit-sdk/src/filters/Filter.ts#L5).

You could use baseFilters which will do an OR [query between values](https://github.com/elastic/search-ui/blob/main/packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts#L79)

They are specified in the queryConfig with `filters`

```
const searchConfig = {
  searchQuery: {
     filters: [{ field: "id", values: ["1", "2"] type: "any" }],
  }
}
```

Hope this helps!

**Comment by lynch-a** [comment]
I can get the intended results when I update the searchQuery `filters` directly as you advised but I don't know how if/how I can update that dynamically (i.e when a user interacts with my component).

For now I have just made the ID I want to filter a disjunctive facet and it's working well, but i'm looking forward to improvements with searchkit v4.

Thanks!
