### ISSUE TITLE
Issue with NextJS integration and “useNextRouting”: renders twice

### ISSUE THREAD

**Issue by julianklotz** [elastic/search-ui#925]
Dear community, I’d love to hear your feedback on an issue that I’ve been having with Search UI. I’ve been pleased to see that there’s an official way to integrate SearchUI with next/router as documented here: https://docs.elastic.co/search-ui/guides/nextjs-integration

After changing my old implementation, I noticed that SearchUI would run all state updates twice: one time before pushing/replacing the new state, and one time afterwards. This causes some flickering and jumping of elements. The reason for this behavior is that the NextJS uses a feature of React that triggers a re-render, documented and discussed here: https://github.com/vercel/next.js/discussions/18072

Ironically, the only way to fix this is using `window.history` (instead of next/router).

I changed the implementation of `writeUrl` inside the `useNextRouting()` hook as shown below.

1. What are your thoughts on this? Did you struggle with any similar issue?
2. Do you see any issues with this implementation?

If this looks good to you, I’d be happy to propose the required changes to the documentation.

```
import { SearchDriver } from "@elastic/search-ui"
import { useRouter } from "next/router"
import { useMemo } from "react"

export const useNextRouting = (config, basePathUrl) => {
    const router = useRouter()
    const { asPath } = router

    const getSearchParamsFromUrl = (url) => {
        // ...
    }

    const routingOptions = {
        readUrl: () => {
            // ...
        },
        writeUrl: (url, { replaceUrl }) => {
            const params = Object.fromEntries(new URLSearchParams(url).entries())
            const newParams = new URLSearchParams(params)
            const newPath = `${window.location.pathname}?${newParams.toString()}`

            if (replaceUrl) {
                window.history.replaceState({ ...window.history.state, as: newPath, url: newPath }, '', newPath)
            } else {
                window.history.pushState({ ...window.history.state, as: newPath, url: newPath }, '', newPath)
            }
        },
        routeChangeHandler: (callback) => {
            // ...
        }
    }

    return useMemo(() => {
        return {
            ...config,
            routingOptions
        }
    }, [router.isReady])
}
```

**Comment by joemcelroy** [comment]
I think the trouble you will encounter by using the window.history pushState directly rather than next/router is that navigating back to another next page will not re-render. 

Maybe worth forking the codesandbox next examples (https://codesandbox.io/s/nextjs-server-connector-example-69qutv?from-embed) and share an example of this router update. If you dont, ill try find some time to do so just so I haven't missed this solution :)

**Comment by julianklotz** [comment]
Thanks! Unfortunately, I don’t have permission to fork your code sandbox. I’ve been using window.history directly (with trackUrlState: false) for quite some time now (though, not using the new routingOptions) and never ran into trouble. When leaving the search page, you should, of course, use next/link. I believe this way the router stays in sync with window.history.

Please let me know if I can help!
