### ISSUE TITLE
Could not find a declaration file for module 'history'

### ISSUE THREAD

**Issue by gsabbih6** [elastic/search-ui#935]
Error: node_modules/@elastic/search-ui/lib/esm/URLManager.d.ts:1:25 - error TS7016: Could not find a declaration file for module 'history'. 'C:/Users/fzp281/Documents/GitHub/meshada-web/node_modules/history/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/history` if it exists or add a new declaration (.d.ts) file containing `declare module 'history';`

1 import { History } from "history";

I have installed history as suggested but no results

**Comment by joemcelroy** [comment]
hi @gsabbih6 - when you say no results, do you mean you cant get search-ui to display any results?
