### ISSUE TITLE
Is grouping supported?

### ISSUE THREAD

**Issue by gerardosabetta** [elastic/search-ui#939]
Hi I'm using appsearch and I see there is an option for grouping in the api reference https://www.elastic.co/guide/en/app-search/current/grouping.html

However I don't think there is an easy way to do this with the AppSearchAPIConnector. Are there plans to support grouping results?

**Comment by parliament718** [comment]
I've actually had success adding the "group" param you linked to in the AppSearch query, despite there being no mention of it in the docs. You simply need to bypass the type checks by casting to ```any``` or extending the `SearchQuery` type to include it.

Doing this adds a `_group` property on each search result with an array of items in the group.

But I'm unable to figure out how to sort by the group counts. What I would like to do something like this:

driver.setSearchQuery({
    group: { field: 'my_field' },
    sort: { '_group.length' : 'desc' }
})

Unfortunately this doesn't work : (

**Comment by gerardosabetta** [comment]
I've had success with creating my own connector that extends from the original AppSearchConnector and overrides the onSearch method. But I haven't seen any information on how to do this with the stock appsearchConnector
