### ISSUE TITLE
Doc: Disjunctive facets still remove available options if they have no results.

### ISSUE THREAD

**Issue by ppf2** [elastic/search-ui#947]
https://docs.elastic.co/search-ui/api/react/components/facet#example-of-an-or-based-facet-filter?edit

>"Disjunctive" facets are facets that do not change when a selection is made. Meaning, all available options will remain as selectable options even after a selection is made.

The current behavior is that disjunctive facets will still remove available options if those options have 0 hits. It will be helpful to clarify the behavior above in our docs.

**Comment by ZakKa89** [comment]
This confused me as well, and still kind of does. 

However: 
On the `Facet` component itself you can pass to the `filterType` prop either "all" or "any". If you want to be able to select multiple within the same Facet, pick all. That worked for my use case maybe it will for yours.

**Comment by ZakKa89** [comment]
I do think that it's needed to completely disable the removal of non available options! As of now there's no way to do that filterType "any"

**Comment by ZakKa89** [comment]
I do think that it's needed to completely disable the removal of non available options! As of now there's no way to do that filterType "any"

**Comment by ZakKa89** [comment]
I do think that it's needed to completely disable the removal of non available options! As of now there's no way to do that filterType "any"

**Comment by joemcelroy** [comment]
> I do think that it's needed to completely disable the removal of non available options! As of now there's no way to do that filterType "any"

This is not possible with the current App Search API to display facet values which are in the document index but isn't present in the search results. For those use-cases, I suggest hardcoding those options within the view component if they need to be present always.

**Comment by ZakKa89** [comment]
I know it's not possible, it's a feature request. 

In my humble opinion, it would be nice if the search-UI package could support this. It seems a fairly common use case. The value of using a library like this lies In not having to code these things ourselves.

**Comment by joemcelroy** [comment]
agreed. I suggest the feature improvement here is to make it much easier to customise the facet display, so that you can always show particular filters that are important to the search, even if they bring back no results.  Doing it from the API side is difficult.
