### ISSUE TITLE
Use custom query

### ISSUE THREAD

**Issue by miriam-orion** [elastic/search-ui#948]
Hello, 
according [to the docs](https://docs.elastic.co/search-ui/api/core/configuration#search-query-queryconfig), the search-ui has minor options to configure the search like turning a preset autocomplete on/ off or set the field weight. Or can I also insert a custom query that I finetuned in elasticsearch to consider things like localization, synonyms, ...?
Kind regards
Miriam

**Comment by miriam-orion** [comment]
Of course I found the answer just after posting the question. Sorry for that.
It is already described in a [Elasticsearch Connector chapter](https://docs.elastic.co/search-ui/api/connectors/elasticsearch#customise-the-elasticsearch-request-body).

**Comment by FaruqueBraimo** [comment]
Hi @miriam-orion , can u share your soluction?
