### ISSUE TITLE
How to control the searchTerm value in SearchBox component?

### ISSUE THREAD

**Issue by periphery25** [elastic/search-ui#950]
Hello,

We have an implementation where we perform a search on a page using `SearchBox` and then it opens a modal to show the results of that search. The modal has its own `SearchBox` component so the user can search again in the modal and this searchbox should be pre-populated with the searchTerm from the SearchBox on the page that opened the modal.

We are running into this weird issue where if the user enters the search quickly (Under 1 second) the search is performed on only part of the search term, such as a search for "science" will only search "sc". I am wondering how I can set the searchTerm in the SearchBox component in our modal to overcome this.

I console log the searchTerm on the original page and the full value appears even when only part of the term is searched. I have remedied this by adding a 1 second timeout before the modal opens but was hoping there is a way to handle this in the component. 

Just a note we use the `inputProps` prop in the SearchBox component to set placeHolder text, is there a way to set the actual search text with `inputProps`?

Thank you

**Comment by periphery25** [comment]
I appreciate the response @ZakKa89! I tinkered around `unmountComponentAtNode()` to try and achieve this but not luck, per chance do you use a different function to unmount a component like you suggested?

**Comment by ZakKa89** [comment]
I don't unmount it I just don't render the component at all if I have a modal open with another search instance like this:

Something like this is in my layout component where a search modal is rendered in my JSX. 

``` jsx
{searchModalIsOpen ? undefined : children }
```

or more concise way;

```jsx
{!searchModalIsOpen && children}

```

In that way if I have a modal open with another search instance, the search instance inside children wouldn't be rendered

**Comment by ZakKa89** [comment]
Please don't close

**Comment by periphery25** [comment]
@ZakKa89 We ended up having to leverage the `resultSearchTerm` discussed in [this Elastic article](https://docs.elastic.co/search-ui/api/core/state), this allowed us to get the actual searchTerm value, not part of it like I was experiencing before
