### ISSUE TITLE
Svelte + Typescript app search connector is not a constructor 

### ISSUE THREAD

**Issue by Finnepinnen** [elastic/search-ui#953]
**Describe the bug**
On build it says that the constructor does not exist.

**To Reproduce**
```
import AppSearchAPIConnector from "@elastic/search-ui-app-search-connector";

const connector = new AppSearchAPIConnector({
    searchKey: "...",
    engineName: "...",
    endpointBase: "...",
  });
```

Returns this error
`TypeError: AppSearchAPIConnector is not a constructor`

**Which backends and packages are you using:**
```
{
 ...
 "@elastic/search-ui": "^1.19.1",
 "@elastic/search-ui-app-search-connector": "^1.19.1",
 "svelte": "^3.54.0",
 "typescript": "^4.9.3",
 "vite": "^4.0.0",
}
```

**Comment by chriscressman** [comment]
Likely an [issue with ESM module support in Search UI](https://github.com/elastic/search-ui/issues/938).

In your example, inspect the `AppSearchAPIConnector` binding you imported. It likely has a `default` property, which is the constructor. You'll have to access the constructor using that property until the linked issue is resolved.

**Comment by Finnepinnen** [comment]
Yes, it looks like a default.

`import {default as AppSearchAPIConnector} from "@elastic/search-ui-app-search-connector";`

Resulted in the same error

**Comment by chriscressman** [comment]
Give this a try (sorry, I don't have a Svelte environment in which to test):

```JavaScript
import AppSearchAPIConnectorModule from '@elastic/search-ui-app-search-connector'

const { default: AppSearchAPIConnector } = AppSearchAPIConnectorModule;

AppSearchAPIConnector // reference to AppSearchAPIConnector class
```

**Comment by Finnepinnen** [comment]
It compiled but then crashed on run with the following error
`Uncaught (in promise) TypeError: a is not a constructor`
where a is the compiled name for the AppSearchAPIConnector

**Comment by joemcelroy** [comment]
hey @Finnepinnen 

could you share an example on minimal setup on codesandbox, so I can try this out? Want to see if changing the package.json exports will help this case. 

Joe

**Comment by Finnepinnen** [comment]
I tried to change the package.json to the proposed solution in #938 but then the import issues started internally in the package. Did you have any luck @joemcelroy? If you have a starting point I could try to help out pushing it forward.
