### ISSUE TITLE
Search-box custom view input lose focus on only Android browser

### ISSUE THREAD

**Issue by fkvivid** [elastic/search-ui#955]
**Describe the bug**

When i customize the searchbox view input focus losing ( keyboard disappeared ) every time i click
and i tried autofocus={true} keyboard showing but not able to click
```js
<SearchBox
      view={({ value, onChange, onSubmit }) => (
        <form onSubmit={onSubmit}>
          <input
            type="text"
            value={value}
            onChange={(e) => onChange(e.target.value)}
          />
          <input type="submit" value="Search" />
        </form>
      )}
  />
```

**Bug videos better than word**

https://user-images.githubusercontent.com/73453260/228726261-7360ddaf-b59d-4920-9d64-9412ad07d139.MOV

*After autofocus*

https://user-images.githubusercontent.com/73453260/228726296-71c9716b-167e-4530-b4d9-7970fc3acf51.MOV

**Comment by fkvivid** [comment]
works fine all device
only not working android real device

**Comment by jagnoha** [comment]
Any solution for this bug? Any update or alternative?
