### ISSUE TITLE
How to pre-select multiple values within a filter/facet? 

### ISSUE THREAD

**Issue by ZakKa89** [elastic/search-ui#957]
Currently you can use setFilter to programmatically select a filter value like so:

```js
  setFilter('item_status', 'MAINSTREAM', 'any')
```

I'm using that as a workaround to 'pre-select' certain values in the filter's UI. 

However, if you want to do multiple, it doesn't work and only sets the last one:

```js
  setFilter('item_status', 'MAINSTREAM', 'any')
  setFilter('item_status', 'SPARE-PART', 'any')
``` 

So in above use case, MAINSTREAM will not be selected but SPARE-PART will. 

<img width="263" alt="image" src="https://user-images.githubusercontent.com/24491661/229292133-632e0ff8-4888-4eaf-b827-76fd87b863c6.png">

Not sure if a bug, a feature that doesn't exist or if I'm doing something wrong? But the feature I'd want is to be able to pre-select certain filters in the config, but still be able to change these afterward. 

# But why not use the filter in the config?

Well, that filter technically works but doesn't update the UI at all. So it's not visible to the user... It's also a 'global' filter so it stays active. I tried to make sure: 

```js
  searchQuery: {
    // global filters are applied on API level
    filters: [
      {
        field: 'item_status',
        type: 'any',
        values: ['MAINSTREAM', 'SPARE-PART', 'STOCK-ITEM', 'MAKE-TO-ORDER', 'SPECIALS']
      }
    ],

```

That config will apply the filters but the values in the Facet will not be checked.

**Comment by ZakKa89** [comment]
Nah don't close this please

**Comment by ZakKa89** [comment]
Nah don't close this please

**Comment by llermaly** [comment]
@ZakKa89 have you tried setting item_status as a disjunctive facet? 

https://docs.elastic.co/search-ui/api/react/components/facet#example-of-an-or-based-facet-filter

**Comment by ZakKa89** [comment]
@llermaly yes it actually already is a disjunctive facet.

**Comment by ZakKa89** [comment]
Nah don't close this please
