### ISSUE TITLE
How to disable the "more+" toggle in facets? 

### ISSUE THREAD

**Issue by ZakKa89** [elastic/search-ui#958]
![image](https://user-images.githubusercontent.com/24491661/229859090-4b32c4de-cd3c-4b45-8c05-99ba24579b72.png)

Can I disable the more+ toggle? So just show all available values? If not, please view this as a feature request.

**Comment by markbussard** [comment]
Elastic search provides a "show" prop where you can define a number of filters to show before displaying the "More" button. You can view that here: https://docs.elastic.co/search-ui/api/react/components/facet
