### ISSUE TITLE
Cannot read properties of undefined (reading 'protocol') 

### ISSUE THREAD

**Issue by lephuhung** [elastic/search-ui#961]
I'm using appsearch ui created from enterprice search
Elastic + Kibana: 8.7
 "@elastic/react-search-ui": "^1.19.1",
 "@elastic/search-ui-app-search-connector": "^1.19.1",
 "react": "^17.0.2",
 "react-dom": "^17.0.2",
  "react-scripts": "5.0.0"
when i change number of result 20 to 40 or 60, server error: 
Compiled with problems:
ERROR
Cannot read properties of undefined (reading 'protocol')
TypeError: Cannot read properties of undefined (reading 'protocol')
    at http://localhost:3000/static/js/bundle.js:2090:47
    at Result (http://localhost:3000/static/js/bundle.js:1414:98)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:36696:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:39179:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:40233:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:27271:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:27315:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:27370:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:44366:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:43377:16)

Thank for reading

**Comment by chriscressman** [comment]
>  when i change number of result 20 to 40 or 60

Can you show how you are making this change?

**Comment by lephuhung** [comment]
> > when i change number of result 20 to 40 or 60
> 
> Can you show how you are making this change?

![b9397b9ffd6821367879](https://user-images.githubusercontent.com/20222030/231205906-2a6d2812-a611-436d-b078-c0c9f87f3b01.jpg)
here!!!

**Comment by chriscressman** [comment]
Thanks, I thought you were referring to a code change. I see now that you're using the generated application without any changes.

I should have time later to try to reproduce the issue.

**Comment by chriscressman** [comment]
I ran the following test and did not experience the issue:

1. Create deployment on Elastic Cloud
1. Create App Search engine using sample data
1. Generate and download Search UI application
1. Run application using commands below
1. Search for documents and change per page (no messages in console)

Commands I ran to start the app:

```bash
nvm install
nvm use
nvm install-latest-npm
npm install
npm start
```

This doesn't solve the problem but may help isolate the issue.

**Comment by joemcelroy** [comment]
what does it say in the network tab? Do you see a request being performed for the size change? Does it fail in an error?

**Comment by lephuhung** [comment]
> I ran the following test and did not experience the issue:
> 
> 1. Create deployment on Elastic Cloud
> 2. Create App Search engine using sample data
> 3. Generate and download Search UI application
> 4. Run application using commands below
> 5. Search for documents and change per page (no messages in console)
> 
> Commands I ran to start the app:
> 
> ```shell
> nvm install
> nvm use
> nvm install-latest-npm
> npm install
> npm start
> ```
> 
> This doesn't solve the problem but may help isolate the issue.

can you post package.json of project

**Comment by lephuhung** [comment]
> what does it say in the network tab? Do you see a request being performed for the size change? Does it fail in an error?

sorry for late, here is screenshot when i change number of page, elastic always return search.json 40, 60 per page, but front-end cannot render
![Screenshot from 2023-04-15 21-25-11](https://user-images.githubusercontent.com/20222030/232230465-49fe6a46-8ebf-4cf7-a3b7-77ccb818fae1.png)
![Screenshot from 2023-04-15 21-25-25](https://user-images.githubusercontent.com/20222030/232230470-b7be9ec9-73f2-4885-952f-e0a0d5a02d34.png)
![Screenshot from 2023-04-15 21-25-38](https://user-images.githubusercontent.com/20222030/232230473-1cda6023-75bf-42e1-95b6-906f12463964.png)

**Comment by lephuhung** [comment]
> I ran the following test and did not experience the issue:
> 
> 1. Create deployment on Elastic Cloud
> 2. Create App Search engine using sample data
> 3. Generate and download Search UI application
> 4. Run application using commands below
> 5. Search for documents and change per page (no messages in console)
> 
> Commands I ran to start the app:
> 
> ```shell
> nvm install
> nvm use
> nvm install-latest-npm
> npm install
> npm start
> ```
> 
> This doesn't solve the problem but may help isolate the issue.

hi, when i change engine.json is "endpointBase": "https://search-ui-sandbox.ent.us-central1.gcp.cloud.es.io",
  "engineName": "national-parks", everything is ok, not error, so i think my elastic server error with suggestion search so front-end will be error. Can you have project search-ui code by typecript?
