### ISSUE TITLE
ElasticsearchAPIConnector - Boolean / 0's come in as undefined

### ISSUE THREAD

**Issue by palkema** [elastic/search-ui#965]
**Describe the bug**
When using the ElasticsearchAPIConnector connector, the values in elastic that are stored as boolean or even integer's where the value = 0. These values return 0's from elastic, or falses from elastic, but the ElasticsearchAPIConnector connector actually takes these 0's or false values, and instead return nulls.

For integration or numeric values greater than 0's, it's great, no issues. And for boolean values where the value = true, it's fine.

But int's that are 0, or boolean's that are false, return nulls.

This actually wouldn't be a huge deal, except that in some instances you have a nullable field, so you want to specify pr distinguish between nulls and 0's or nulls and false values. 

**To Reproduce**

1. Go to elastic and create an index with int value's that =0, and boolean values that = false.
2. Set up an elastic project to output these values using the ElasticsearchAPIConnector and ElasticDriver.
3. View the return coming back from elastic, which shows that these false values come in as false, and the 0's come in as zeros. But not that the result object returned in the ElasticDriver, these values are blank.

Again this is problematic for instances where you want to distinguish between null's and false, or nulls and 0 values. This information is lost as a result of this bug.

**Expected behavior**
For boolean values that are false, false should be returned. For int values = 0's, these should return 0's.

**Which backends and packages are you using:**
Backend: Elasticsearch
Packages: @elastic/search-ui-elasticsearch-connector, @elastic/search-ui

**Comment by palkema** [comment]
I confirmed that about a month later, latest version, this issue is still an outstanding issue. Elastic numerical 0's are saved as undefined values, which is wrong, they should be 0's so that the UI can distinguish between fields where the data doesn't exist, and instances where the values are actual 0's.

**Comment by ZakKa89** [comment]
Just a fun fact: In App Search there is no boolean value at all possible in the schema so we just use strings instead "false" / "true".
