### ISSUE TITLE
Am I able to view the mapping file that provides for the examples?

### ISSUE THREAD

**Issue by Tigatok** [elastic/search-ui#968]
I am looking to see if I can find the mapping file that makes up the example index. I am trying to look at the anatomy of how the search examples are being configured. I can't seem to make a GET call to the _mapping endpoint using the credentials in the example.

<img width="985" alt="image" src="https://github.com/elastic/search-ui/assets/3906461/0d89cdfc-2a4f-42cb-9f34-115f996f1b34">

Let me know if this is allowed/public!

Thanks

**Comment by jackfrosty908** [comment]
Hey @Tigatok I'm also trying to find this out and stumbled across your question. Did you ever find this?

**Comment by Tigatok** [comment]
@jackfrosty908 I can't remember, honestly. What are you trying to do? I may be able to help out given a bit more context.

**Comment by jackfrosty908** [comment]
@Tigatok thanks for the response! I'm having issues getting a global filter to work via config. I thought it might have been an issue with my mapping as it works in sandbox demos provided. 

But I actually just found this ticket [here](https://github.com/elastic/search-ui/issues/892) which is the same issue I'm having. So going to have a go at modifying the query [via the connector](https://docs.elastic.co/search-ui/api/connectors/elasticsearch#customise-the-elasticsearch-request-body) to get the filter working properly.

**Comment by Tigatok** [comment]
@jackfrosty908 Glad you found what you needed!
