### ISSUE TITLE
Wrong type definition inside `FacetViewProps`

### ISSUE THREAD

**Issue by wentaoxu415** [elastic/search-ui#979]
**Describe the bug**
In the `FacetViewProps` type, the parameters for the callback functions (`onRemove`, `onChange`, `onSelect`) are typed as `FieldValue`.
https://github.com/elastic/search-ui/blob/main/packages/react-search-ui-views/src/types/index.ts#L68

However, those callback functions eventually call search driver actions for filters and the expected type there is `FilterValue` instead of `FieldValue`.
(Ex. See [`removeFilters`](https://github.com/elastic/search-ui/blob/main/packages/search-ui/src/actions/removeFilter.ts#L16)

**To Reproduce**
See the linked code files.

**Expected behavior**
The type definition for the parameters passed to those callback functions in the `FacetViewProps` should be updated to `FilterValue` type.

**Screenshots**
N/A

**Which backends and packages are you using:**
Packages: search-ui 1.20.0

**Comment by joemcelroy** [comment]
thank you. Happy to accept a PR for this change!

**Comment by wentaoxu415** [comment]
Awesome! Will send you a PR for this soon :)
