### ISSUE TITLE
React Hook alternative for `withSearch` / `WithSearch`  HOCs

### ISSUE THREAD

**Issue by wentaoxu415** [elastic/search-ui#980]
**Is your feature request related to a problem? Please describe.**
The `react-search-ui` library currently offers  `withSearch` / `WithSearch`  HOCs to access Search UI's core state and actions. However, this often leads to a lot of repeated code when you are wrapping the component with this HOC.

As you can see from the example below, you have to often repeat the desired core state and actions properties 3 times before you can finally make them available to a component.
```
const ComponentWithSearch = withSearch(
  ({
    isLoading,
    results,
    resultsPerPage,
    setResultsPerPage,
    filters,
    setFilter,
    clearFilters,
    removeFilter,
    searchTerm,
    setSearchTerm,
    resultSearchTerm,
    reset,
    totalResults,
  }) => ({
    isLoading,
    results,
    resultsPerPage,
    setResultsPerPage,
    filters,
    setFilter,
    clearFilters,
    removeFilter,
    searchTerm,
    setSearchTerm,
    resultSearchTerm,
    reset,
    totalResults,
  })
)(Component);

function Component(props) {
  const {
    isLoading,
    filters,
    setFilter,
    clearFilters,
    removeFilter,
    resultsPerPage,
    setResultsPerPage,
    searchTerm,
    setSearchTerm,
    reset,
    results,
    resultSearchTerm,
    totalResults,
} = props;
}
```

**Describe the solution you'd like**
In addition to the HOC approach, it would be nice if SearchUI can also provide a React Hook alternative as it could lead to a much more concise code.

With React Hook, the above example can now be simplified as the following and allow require you to specify the desired states and core actions once.

```
function Component(props) {
  const {
    isLoading,
    filters,
    setFilter,
    clearFilters,
    removeFilter,
    resultsPerPage,
    setResultsPerPage,
    searchTerm,
    setSearchTerm,
    reset,
    results,
    resultSearchTerm,
    totalResults,
} = useSearch(); // React Hook alternative
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by joemcelroy** [comment]
Agreed and its more inline with how developers are integrating search-ui into their app. We want to make it easy to build their own view components and a hook to access the core state / api would be really great.

We are planning on revamping search ui in the near future. Il keep this ticket in mind when we do start on this.

Another alternative if you're using Elasticsearch directly is https://github.com/searchkit/searchkit. With instantsearch hooks, you can do alot of what you mentioned already.

Joe

**Comment by wentaoxu415** [comment]
@joemcelroy Yeah I wish I had known about https://github.com/searchkit/searchkit earlier, but it was overlooked due to not being mentioned on the official Elastic documentation.

I see that searchkit was more of a community-grown open-source package where you were one of the primary contributors whereas SearchUI is more of Elasticsearch's official open-source package.

It will be nice for the official Elastic documentation to provide guidance on when to use `SearchUI` or `SearchKit` including suggestions around using the official `SearchUI`'s elasticsearch connector vs. community-grown `SearchKit`.

**Comment by rlueder** [comment]
Also described on #244
