### ISSUE TITLE
How to handle racing search requests?

### ISSUE THREAD

**Issue by wentaoxu415** [elastic/search-ui#981]
How does `SearchProvider` in `react-search-ui` currently handle racing search requests? Is there any way to configure this behavior?

To use an example, let's say that a user makes `search A` first and `search B` next within several seconds of each other. However, `search A` is a time-consuming search and it will almost always return later than `search B` even though its request is sent out first.

In this example, we could see either one of the following behaviors 
1. `search A` is returned but `SearchProvider` sees that `search A`'s request sent time is earlier than `search B` request time so it will ignore it.
2. `search A` is returned and `SearchProvider` will proceed to pass the results which will lead the app to override the `search B` results.

In my opinion, the preferred behavior is the first behavior as the most recent search request created by users should be the one that's used while any earlier search requests get ignored. Ideally, `SearchProvider` does this automatically, but if it's not, it will be nice if there's a way to pass the request sent time as metadata that you can also check at the time of the response to allow the client side to determine whether it wants to use that response or not.

I would love to get your team's guidance on this

**Comment by JasonStoltz** [comment]
This could have changed, but I believe we implemented request sequencing [here](https://github.com/elastic/search-ui/blob/c35ca17eaa2f561a1a1823ba3aa35a90dae0600b/packages/search-ui/src/SearchDriver.ts#L448). We id each request and cancel old requests if they return after a more recent request is made.

**Comment by wentaoxu415** [comment]
@JasonStoltz Thanks for pointing me to this code. I am glad to see that request sequencing is already being handled as part of the `search-ui` library.

However, I also see that request sequence check is only getting applied [here](https://github.com/elastic/search-ui/blob/main/packages/search-ui/src/SearchDriver.ts#L448) in the case of a successful response. Meanwhile, an error response does not go through that check which means that the error still gets passed downstream.

In my opinion, an error of old request should just get swallowed/handled so that it does not disrupt the UI while subsequent requests are getting made.

To raise a concrete example of what could go wrong, a timeout error of an old request can make the SearchContext / SearchProvider return error and falsely lead the UI to put up some kind of error state while subsequent requests are getting made successfully.

So what do you think to the idea of adding request check in the error handling as well? (Maybe [here](https://github.com/elastic/search-ui/blob/main/packages/search-ui/src/SearchDriver.ts#L516))
