### ISSUE TITLE
Custom routing in Elasticsearch connector

### ISSUE THREAD

**Issue by michaelbridge** [elastic/search-ui#987]
Elasticsearch supports [searching with custom routing](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html#_searching_with_custom_routing). This is critical functionality to enable sufficient scalability for large data sets.

Reviewing the source for `@elastic/search-ui-elasticsearch-connector` and `@searchkit`, I see no reference that would allow configuration of custom routing on a request-by-request basis, but perhaps there is a way to pass the param.

I am using an express wrapper as suggested [here](https://docs.elastic.co/search-ui/api/connectors/elasticsearch#nodejs-integration) (sample code below) to enforce certain filtering and permissions.

```
app.post("/search", async (req, res) => {
  const { query, options } = req.body;
  const response = await connector.onSearch(query, options);
  res.json(response);
});
```
I'd like to use this as an insertion point for modifying the routing parameter (i.e., `GET my-index-000001/_search?routing=user1` per the [example](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html#_searching_with_custom_routing)). Is this possible?

**Comment by joemcelroy** [comment]
Unfortunately not right now. 

You could do this in the express wrapper?

Joe

**Comment by michaelbridge** [comment]
It is possible but requires patching the underlying libraries (both this and the connector).
