### ISSUE TITLE
ErrorBoundary View Customization Not Working

### ISSUE THREAD

**Issue by OnerInce** [elastic/search-ui#990]
**Describe the bug**

ErrorBoundary View Customization Not Working. As described in the [docs](https://docs.elastic.co/search-ui/api/react/components/error-boundary), error attribute should be used as an custom error message IF an error occurred. However, whenever error attribute is set, error message is shown regardless whether there is an error

Tryting to provide a custom view using

`<ErrorBoundary view={ErrorView}>`

yields the same result as well.

**To Reproduce**

Use ErrorBoundary component with the error attribute. 

`<ErrorBoundary error='custom-error-message'>
    ......
  </ErrorBoundary>
`

**Expected behavior**
Having a custom error message IF an error happens.

**Comment by RaviTejaM9602** [comment]
Custom Error View and Message in <ErrorBoundary> Not Working as Expected

When using the <ErrorBoundary> component with a view prop to provide a custom error view (e.g., <ErrorBoundary view={ErrorView}> it is directly showing ErrorView component when page gets loaded first irrespective of error. 

I tried couple of ways but still I have the same problem with it. Could you please suggest me how can I show a generic message on UI when  error was occured in the application.
