### ISSUE TITLE
Out of date dependency "core-js" being used in @elastic/react-search-ui-views

### ISSUE THREAD

**Issue by judithtarot** [elastic/search-ui#991]
**Is your feature request related to a problem? Please describe.**

When the @elastic/react-search-ui-views  modules are being built this warning appears:

```
[1/5] 🔍  Resolving packages...
warning @elastic/react-search-ui > @elastic/react-search-ui-views > rc-pagination > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```

This makes me concerned that some of our users might be having a poor search experience.

**Describe the solution you'd like**

Upgrade the version of "rc-pagination" being used in "@elastic/react-search-ui-views".  It is asking for "^1.20.1" which is 4 years old and has that unrecommended dependency.  The current version of "rc-pagination" is "3.6.1"

**Describe alternatives you've considered**
I am using your js/react modules, and they usually work well, so I would like to be able to continue using them.

**Comment by joemcelroy** [comment]
fixed in 1.21.0
