### ISSUE TITLE
Custom Query | Default Query for React Js Search UI

### ISSUE THREAD

**Issue by FaruqueBraimo** [elastic/search-ui#993]
Hi , I'm interested in learning how to craft custom or default queries for a search UI. This might involve tasks such as retrieving specific data based on particular attribute values before rendering, or implementing queries that users themselves cannot execute directly from react js.

**Comment by rommelcanoy** [comment]
I am also facing a similar challenge in my project. Crafting custom queries for a search UI can indeed be a complex task. I'm interested in any insights or solutions that the community might have regarding this issue. Sharing knowledge and experiences related to this topic would be immensely helpful for developers like us.
