### ISSUE TITLE
Elasticsearch connector: Incorrect handling of falsy values

### ISSUE THREAD

**Issue by applicity** [elastic/search-ui#996]
### Description of the bug

The elasticsearch connector incorrectly handles non true values in the search results returned.  For example if we have a boolean field called important in our index, when we return a document which has a false value we get an empty object returned.

For example the returned document would look like this:

{ premium: {} }

We would expect this to return:

{ premium: { raw: false } }

Which is the structure of data being returned for a document with a true value, for example we get

{ premium: { raw: true } }

**To Reproduce**

1. Create an index with a boolean field
2. Add a document which has a false value for the boolean field
3. Return the document as a search result
4. The structure of the returned document will have an empty object 

**Expected behavior**

We would expect the field to contain the raw value of the field in all cases, rather than just truthy cases.  With the current behaviour we loose data for fields which have values of false, 0, "" etc.  

**Which backends and packages are you using:**
Backend: [Elasticsearch]
Packages: [react-search-ui, search-ui-elasticsearch-connector]

**Comment by applicity** [comment]
I have created a PR and tests which resolve this issue.

**Comment by joemcelroy** [comment]
thanks for the bug report and PR. Will try release soon.
